/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  ActionType,  AgentResponse,  AssistantResponse,  GenerateHarnessAction,  InsertNodeAction,  ObservationRequest,  RunSimulationAction,  SetInputAction,  ShowDiffAction,  VerifyAssertionAction } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AgentResponse {
      schemaVersion?: "1.0" | null
      message?: string | null
      action?: SetInputAction | RunSimulationAction | ShowDiffAction | InsertNodeAction | GenerateHarnessAction | VerifyAssertionAction | null
      done?: boolean | null
      plan?: string[] | null
      reasoning?: string | null
      observationRequest?: ObservationRequest | null
    }
    export interface AssistantResponse {
      schemaVersion?: "1.0" | null
      message?: string | null
      actions: (SetInputAction | RunSimulationAction | ShowDiffAction | InsertNodeAction | GenerateHarnessAction)[]
      suggestedFollowUps?: string[] | null
      shouldContinue?: boolean | null
    }
    export interface GenerateHarnessAction {
      actionId?: string | null
      type?: "GENERATE_HARNESS" | null
      circuitName?: string | null
    }
    export interface InsertNodeAction {
      actionId?: string | null
      type?: "INSERT_NODE" | null
      componentRef?: string | null
      suggestedLabel?: string | null
      connectFrom?: string | null
      connectTo?: string | null
    }
    export interface ObservationRequest {
      type?: "simulate" | "validate" | "inspect_signal" | null
      signalName?: string | null
      cycles?: number | null
    }
    export interface RunSimulationAction {
      actionId?: string | null
      type?: "RUN_SIMULATION" | null
      cycles?: number | null
      stimuli?: Record<string, number> | null
    }
    export interface SetInputAction {
      actionId?: string | null
      type?: "SET_INPUT" | null
      node?: string | null
      value?: number | null
    }
    export interface ShowDiffAction {
      actionId?: string | null
      type?: "SHOW_DIFF" | null
      originalCode?: string | null
      suggestedCode?: string | null
      explanation?: string | null
    }
    export interface VerifyAssertionAction {
      actionId?: string | null
      type?: "VERIFY_ASSERTION" | null
      targetCircuit?: string | null
      maxCycles?: number | null
    }
}