/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum ActionType {
  SET_INPUT = "SET_INPUT",
  RUN_SIMULATION = "RUN_SIMULATION",
  SHOW_DIFF = "SHOW_DIFF",
  INSERT_NODE = "INSERT_NODE",
}

export interface AgentResponse {
  schemaVersion: "1.0"
  message: string
  action?: SetInputAction | RunSimulationAction | ShowDiffAction | InsertNodeAction | null
  done: boolean
  plan?: string[] | null
  reasoning?: string | null
  
}

export interface AssistantResponse {
  schemaVersion: "1.0"
  message: string
  actions: (SetInputAction | RunSimulationAction | ShowDiffAction | InsertNodeAction)[]
  suggestedFollowUps?: string[] | null
  
}

export interface InsertNodeAction {
  actionId?: string | null
  type: "INSERT_NODE"
  componentRef: string
  suggestedLabel?: string | null
  connectFrom?: string | null
  connectTo?: string | null
  
}

export interface RunSimulationAction {
  actionId?: string | null
  type: "RUN_SIMULATION"
  cycles: number
  stimuli?: Record<string, number> | null
  
}

export interface SetInputAction {
  actionId?: string | null
  type: "SET_INPUT"
  node: string
  value: number
  
}

export interface ShowDiffAction {
  actionId?: string | null
  type: "SHOW_DIFF"
  originalCode: string
  suggestedCode: string
  explanation: string
  
}
