/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    AgentResponse: ClassViewer<'AgentResponse', "schemaVersion" | "message" | "action" | "done" | "plan" | "reasoning">;
    
    AssistantResponse: ClassViewer<'AssistantResponse', "schemaVersion" | "message" | "actions" | "suggestedFollowUps">;
    
    InsertNodeAction: ClassViewer<'InsertNodeAction', "actionId" | "type" | "componentRef" | "suggestedLabel" | "connectFrom" | "connectTo">;
    
    RunSimulationAction: ClassViewer<'RunSimulationAction', "actionId" | "type" | "cycles" | "stimuli">;
    
    SetInputAction: ClassViewer<'SetInputAction', "actionId" | "type" | "node" | "value">;
    
    ShowDiffAction: ClassViewer<'ShowDiffAction', "actionId" | "type" | "originalCode" | "suggestedCode" | "explanation">;
    
    
    ActionType: EnumViewer<'ActionType', "SET_INPUT" | "RUN_SIMULATION" | "SHOW_DIFF" | "INSERT_NODE">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "AgentResponse","AssistantResponse","InsertNodeAction","RunSimulationAction","SetInputAction","ShowDiffAction",
          ]),
          enums: new Set([
            "ActionType",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.AgentResponse = this.tb.classViewer("AgentResponse", [
          "schemaVersion","message","action","done","plan","reasoning",
        ]);
        
        this.AssistantResponse = this.tb.classViewer("AssistantResponse", [
          "schemaVersion","message","actions","suggestedFollowUps",
        ]);
        
        this.InsertNodeAction = this.tb.classViewer("InsertNodeAction", [
          "actionId","type","componentRef","suggestedLabel","connectFrom","connectTo",
        ]);
        
        this.RunSimulationAction = this.tb.classViewer("RunSimulationAction", [
          "actionId","type","cycles","stimuli",
        ]);
        
        this.SetInputAction = this.tb.classViewer("SetInputAction", [
          "actionId","type","node","value",
        ]);
        
        this.ShowDiffAction = this.tb.classViewer("ShowDiffAction", [
          "actionId","type","originalCode","suggestedCode","explanation",
        ]);
        
        
        this.ActionType = this.tb.enumViewer("ActionType", [
          "SET_INPUT","RUN_SIMULATION","SHOW_DIFF","INSERT_NODE",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}