/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LearnProgramCounterRouteImport } from './routes/learn/program-counter'
import { Route as LearnDualCpuRouteImport } from './routes/learn/dual-cpu'
import { Route as LearnCpuRouteImport } from './routes/learn/cpu'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ChallengesSnakeRouteImport } from './routes/challenges/snake'
import { Route as ChallengesNandToLogicRouteImport } from './routes/challenges/nand-to-logic'
import { Route as ChallengesBuildAnAluRouteImport } from './routes/challenges/build-an-alu'
import { Route as ChallengesBuildACpuRouteImport } from './routes/challenges/build-a-cpu'
import { Route as BlogSnakeInHardwareRouteImport } from './routes/blog/snake-in-hardware'
import { Route as BlogRv32iCpuRouteImport } from './routes/blog/rv32i-cpu'
import { Route as BlogPongInHardwareRouteImport } from './routes/blog/pong-in-hardware'
import { Route as BlogMcpBidirectionalBridgeRouteImport } from './routes/blog/mcp-bidirectional-bridge'
import { Route as BlogLogicFromNothingRouteImport } from './routes/blog/logic-from-nothing'
import { Route as BlogHowTpusWorkRouteImport } from './routes/blog/how-tpus-work'
import { Route as BlogHowNetworkSwitchesWorkRouteImport } from './routes/blog/how-network-switches-work'
import { Route as BlogComputingTrigInHardwareRouteImport } from './routes/blog/computing-trig-in-hardware'
import { Route as BlogChacha20InHardwareRouteImport } from './routes/blog/chacha20-in-hardware'
import { Route as BlogBuildingACpuRouteImport } from './routes/blog/building-a-cpu'
import { Route as BlogBreakoutInHardwareRouteImport } from './routes/blog/breakout-in-hardware'
import { Route as BlogAesInHardwareRouteImport } from './routes/blog/aes-in-hardware'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const LearnProgramCounterRoute = LearnProgramCounterRouteImport.update({
  id: '/learn/program-counter',
  path: '/learn/program-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDualCpuRoute = LearnDualCpuRouteImport.update({
  id: '/learn/dual-cpu',
  path: '/learn/dual-cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCpuRoute = LearnCpuRouteImport.update({
  id: '/learn/cpu',
  path: '/learn/cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSnakeRoute = ChallengesSnakeRouteImport.update({
  id: '/challenges/snake',
  path: '/challenges/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesNandToLogicRoute = ChallengesNandToLogicRouteImport.update({
  id: '/challenges/nand-to-logic',
  path: '/challenges/nand-to-logic',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesBuildAnAluRoute = ChallengesBuildAnAluRouteImport.update({
  id: '/challenges/build-an-alu',
  path: '/challenges/build-an-alu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesBuildACpuRoute = ChallengesBuildACpuRouteImport.update({
  id: '/challenges/build-a-cpu',
  path: '/challenges/build-a-cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSnakeInHardwareRoute = BlogSnakeInHardwareRouteImport.update({
  id: '/snake-in-hardware',
  path: '/snake-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogRv32iCpuRoute = BlogRv32iCpuRouteImport.update({
  id: '/rv32i-cpu',
  path: '/rv32i-cpu',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPongInHardwareRoute = BlogPongInHardwareRouteImport.update({
  id: '/pong-in-hardware',
  path: '/pong-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogMcpBidirectionalBridgeRoute =
  BlogMcpBidirectionalBridgeRouteImport.update({
    id: '/mcp-bidirectional-bridge',
    path: '/mcp-bidirectional-bridge',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogLogicFromNothingRoute = BlogLogicFromNothingRouteImport.update({
  id: '/logic-from-nothing',
  path: '/logic-from-nothing',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHowTpusWorkRoute = BlogHowTpusWorkRouteImport.update({
  id: '/how-tpus-work',
  path: '/how-tpus-work',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHowNetworkSwitchesWorkRoute =
  BlogHowNetworkSwitchesWorkRouteImport.update({
    id: '/how-network-switches-work',
    path: '/how-network-switches-work',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogComputingTrigInHardwareRoute =
  BlogComputingTrigInHardwareRouteImport.update({
    id: '/computing-trig-in-hardware',
    path: '/computing-trig-in-hardware',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogChacha20InHardwareRoute = BlogChacha20InHardwareRouteImport.update({
  id: '/chacha20-in-hardware',
  path: '/chacha20-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBuildingACpuRoute = BlogBuildingACpuRouteImport.update({
  id: '/building-a-cpu',
  path: '/building-a-cpu',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBreakoutInHardwareRoute = BlogBreakoutInHardwareRouteImport.update({
  id: '/breakout-in-hardware',
  path: '/breakout-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAesInHardwareRoute = BlogAesInHardwareRouteImport.update({
  id: '/aes-in-hardware',
  path: '/aes-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/editor': typeof EditorRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/logic-from-nothing': typeof BlogLogicFromNothingRoute
  '/blog/mcp-bidirectional-bridge': typeof BlogMcpBidirectionalBridgeRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/nand-to-logic': typeof ChallengesNandToLogicRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/logic-from-nothing': typeof BlogLogicFromNothingRoute
  '/blog/mcp-bidirectional-bridge': typeof BlogMcpBidirectionalBridgeRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/nand-to-logic': typeof ChallengesNandToLogicRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog': typeof BlogIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/editor': typeof EditorRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/logic-from-nothing': typeof BlogLogicFromNothingRoute
  '/blog/mcp-bidirectional-bridge': typeof BlogMcpBidirectionalBridgeRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/nand-to-logic': typeof ChallengesNandToLogicRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/editor'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/logic-from-nothing'
    | '/blog/mcp-bidirectional-bridge'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/nand-to-logic'
    | '/challenges/snake'
    | '/docs/$'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog/'
    | '/challenges/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/logic-from-nothing'
    | '/blog/mcp-bidirectional-bridge'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/nand-to-logic'
    | '/challenges/snake'
    | '/docs/$'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog'
    | '/challenges'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/editor'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/logic-from-nothing'
    | '/blog/mcp-bidirectional-bridge'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/nand-to-logic'
    | '/challenges/snake'
    | '/docs/$'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog/'
    | '/challenges/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  EditorRoute: typeof EditorRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ChallengesBuildACpuRoute: typeof ChallengesBuildACpuRoute
  ChallengesBuildAnAluRoute: typeof ChallengesBuildAnAluRoute
  ChallengesNandToLogicRoute: typeof ChallengesNandToLogicRoute
  ChallengesSnakeRoute: typeof ChallengesSnakeRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LearnCpuRoute: typeof LearnCpuRoute
  LearnDualCpuRoute: typeof LearnDualCpuRoute
  LearnProgramCounterRoute: typeof LearnProgramCounterRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/learn/program-counter': {
      id: '/learn/program-counter'
      path: '/learn/program-counter'
      fullPath: '/learn/program-counter'
      preLoaderRoute: typeof LearnProgramCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/dual-cpu': {
      id: '/learn/dual-cpu'
      path: '/learn/dual-cpu'
      fullPath: '/learn/dual-cpu'
      preLoaderRoute: typeof LearnDualCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/cpu': {
      id: '/learn/cpu'
      path: '/learn/cpu'
      fullPath: '/learn/cpu'
      preLoaderRoute: typeof LearnCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/snake': {
      id: '/challenges/snake'
      path: '/challenges/snake'
      fullPath: '/challenges/snake'
      preLoaderRoute: typeof ChallengesSnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/nand-to-logic': {
      id: '/challenges/nand-to-logic'
      path: '/challenges/nand-to-logic'
      fullPath: '/challenges/nand-to-logic'
      preLoaderRoute: typeof ChallengesNandToLogicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/build-an-alu': {
      id: '/challenges/build-an-alu'
      path: '/challenges/build-an-alu'
      fullPath: '/challenges/build-an-alu'
      preLoaderRoute: typeof ChallengesBuildAnAluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/build-a-cpu': {
      id: '/challenges/build-a-cpu'
      path: '/challenges/build-a-cpu'
      fullPath: '/challenges/build-a-cpu'
      preLoaderRoute: typeof ChallengesBuildACpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/snake-in-hardware': {
      id: '/blog/snake-in-hardware'
      path: '/snake-in-hardware'
      fullPath: '/blog/snake-in-hardware'
      preLoaderRoute: typeof BlogSnakeInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/rv32i-cpu': {
      id: '/blog/rv32i-cpu'
      path: '/rv32i-cpu'
      fullPath: '/blog/rv32i-cpu'
      preLoaderRoute: typeof BlogRv32iCpuRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/pong-in-hardware': {
      id: '/blog/pong-in-hardware'
      path: '/pong-in-hardware'
      fullPath: '/blog/pong-in-hardware'
      preLoaderRoute: typeof BlogPongInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/mcp-bidirectional-bridge': {
      id: '/blog/mcp-bidirectional-bridge'
      path: '/mcp-bidirectional-bridge'
      fullPath: '/blog/mcp-bidirectional-bridge'
      preLoaderRoute: typeof BlogMcpBidirectionalBridgeRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/logic-from-nothing': {
      id: '/blog/logic-from-nothing'
      path: '/logic-from-nothing'
      fullPath: '/blog/logic-from-nothing'
      preLoaderRoute: typeof BlogLogicFromNothingRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-tpus-work': {
      id: '/blog/how-tpus-work'
      path: '/how-tpus-work'
      fullPath: '/blog/how-tpus-work'
      preLoaderRoute: typeof BlogHowTpusWorkRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-network-switches-work': {
      id: '/blog/how-network-switches-work'
      path: '/how-network-switches-work'
      fullPath: '/blog/how-network-switches-work'
      preLoaderRoute: typeof BlogHowNetworkSwitchesWorkRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/computing-trig-in-hardware': {
      id: '/blog/computing-trig-in-hardware'
      path: '/computing-trig-in-hardware'
      fullPath: '/blog/computing-trig-in-hardware'
      preLoaderRoute: typeof BlogComputingTrigInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/chacha20-in-hardware': {
      id: '/blog/chacha20-in-hardware'
      path: '/chacha20-in-hardware'
      fullPath: '/blog/chacha20-in-hardware'
      preLoaderRoute: typeof BlogChacha20InHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/building-a-cpu': {
      id: '/blog/building-a-cpu'
      path: '/building-a-cpu'
      fullPath: '/blog/building-a-cpu'
      preLoaderRoute: typeof BlogBuildingACpuRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/breakout-in-hardware': {
      id: '/blog/breakout-in-hardware'
      path: '/breakout-in-hardware'
      fullPath: '/blog/breakout-in-hardware'
      preLoaderRoute: typeof BlogBreakoutInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/aes-in-hardware': {
      id: '/blog/aes-in-hardware'
      path: '/aes-in-hardware'
      fullPath: '/blog/aes-in-hardware'
      preLoaderRoute: typeof BlogAesInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogAesInHardwareRoute: typeof BlogAesInHardwareRoute
  BlogBreakoutInHardwareRoute: typeof BlogBreakoutInHardwareRoute
  BlogBuildingACpuRoute: typeof BlogBuildingACpuRoute
  BlogChacha20InHardwareRoute: typeof BlogChacha20InHardwareRoute
  BlogComputingTrigInHardwareRoute: typeof BlogComputingTrigInHardwareRoute
  BlogHowNetworkSwitchesWorkRoute: typeof BlogHowNetworkSwitchesWorkRoute
  BlogHowTpusWorkRoute: typeof BlogHowTpusWorkRoute
  BlogLogicFromNothingRoute: typeof BlogLogicFromNothingRoute
  BlogMcpBidirectionalBridgeRoute: typeof BlogMcpBidirectionalBridgeRoute
  BlogPongInHardwareRoute: typeof BlogPongInHardwareRoute
  BlogRv32iCpuRoute: typeof BlogRv32iCpuRoute
  BlogSnakeInHardwareRoute: typeof BlogSnakeInHardwareRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogAesInHardwareRoute: BlogAesInHardwareRoute,
  BlogBreakoutInHardwareRoute: BlogBreakoutInHardwareRoute,
  BlogBuildingACpuRoute: BlogBuildingACpuRoute,
  BlogChacha20InHardwareRoute: BlogChacha20InHardwareRoute,
  BlogComputingTrigInHardwareRoute: BlogComputingTrigInHardwareRoute,
  BlogHowNetworkSwitchesWorkRoute: BlogHowNetworkSwitchesWorkRoute,
  BlogHowTpusWorkRoute: BlogHowTpusWorkRoute,
  BlogLogicFromNothingRoute: BlogLogicFromNothingRoute,
  BlogMcpBidirectionalBridgeRoute: BlogMcpBidirectionalBridgeRoute,
  BlogPongInHardwareRoute: BlogPongInHardwareRoute,
  BlogRv32iCpuRoute: BlogRv32iCpuRoute,
  BlogSnakeInHardwareRoute: BlogSnakeInHardwareRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  EditorRoute: EditorRoute,
  ApiSearchRoute: ApiSearchRoute,
  ChallengesBuildACpuRoute: ChallengesBuildACpuRoute,
  ChallengesBuildAnAluRoute: ChallengesBuildAnAluRoute,
  ChallengesNandToLogicRoute: ChallengesNandToLogicRoute,
  ChallengesSnakeRoute: ChallengesSnakeRoute,
  DocsSplatRoute: DocsSplatRoute,
  LearnCpuRoute: LearnCpuRoute,
  LearnDualCpuRoute: LearnDualCpuRoute,
  LearnProgramCounterRoute: LearnProgramCounterRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
