/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Splash4RouteImport } from './routes/splash4'
import { Route as Splash3RouteImport } from './routes/splash3'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LearnProgramCounterRouteImport } from './routes/learn/program-counter'
import { Route as LearnDualCpuRouteImport } from './routes/learn/dual-cpu'
import { Route as LearnCpuRouteImport } from './routes/learn/cpu'
import { Route as ChallengesSnakeRouteImport } from './routes/challenges/snake'
import { Route as ChallengesBuildAnAluRouteImport } from './routes/challenges/build-an-alu'
import { Route as ChallengesBuildACpuRouteImport } from './routes/challenges/build-a-cpu'
import { Route as BlogSnakeInHardwareRouteImport } from './routes/blog/snake-in-hardware'
import { Route as BlogPongInHardwareRouteImport } from './routes/blog/pong-in-hardware'
import { Route as BlogHowTpusWorkRouteImport } from './routes/blog/how-tpus-work'
import { Route as BlogHowNetworkSwitchesWorkRouteImport } from './routes/blog/how-network-switches-work'
import { Route as BlogComputingTrigInHardwareRouteImport } from './routes/blog/computing-trig-in-hardware'
import { Route as BlogBuildingACpuRouteImport } from './routes/blog/building-a-cpu'

const Splash4Route = Splash4RouteImport.update({
  id: '/splash4',
  path: '/splash4',
  getParentRoute: () => rootRouteImport,
} as any)
const Splash3Route = Splash3RouteImport.update({
  id: '/splash3',
  path: '/splash3',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnProgramCounterRoute = LearnProgramCounterRouteImport.update({
  id: '/learn/program-counter',
  path: '/learn/program-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnDualCpuRoute = LearnDualCpuRouteImport.update({
  id: '/learn/dual-cpu',
  path: '/learn/dual-cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCpuRoute = LearnCpuRouteImport.update({
  id: '/learn/cpu',
  path: '/learn/cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesSnakeRoute = ChallengesSnakeRouteImport.update({
  id: '/challenges/snake',
  path: '/challenges/snake',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesBuildAnAluRoute = ChallengesBuildAnAluRouteImport.update({
  id: '/challenges/build-an-alu',
  path: '/challenges/build-an-alu',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesBuildACpuRoute = ChallengesBuildACpuRouteImport.update({
  id: '/challenges/build-a-cpu',
  path: '/challenges/build-a-cpu',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSnakeInHardwareRoute = BlogSnakeInHardwareRouteImport.update({
  id: '/blog/snake-in-hardware',
  path: '/blog/snake-in-hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPongInHardwareRoute = BlogPongInHardwareRouteImport.update({
  id: '/blog/pong-in-hardware',
  path: '/blog/pong-in-hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowTpusWorkRoute = BlogHowTpusWorkRouteImport.update({
  id: '/blog/how-tpus-work',
  path: '/blog/how-tpus-work',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowNetworkSwitchesWorkRoute =
  BlogHowNetworkSwitchesWorkRouteImport.update({
    id: '/blog/how-network-switches-work',
    path: '/blog/how-network-switches-work',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComputingTrigInHardwareRoute =
  BlogComputingTrigInHardwareRouteImport.update({
    id: '/blog/computing-trig-in-hardware',
    path: '/blog/computing-trig-in-hardware',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBuildingACpuRoute = BlogBuildingACpuRouteImport.update({
  id: '/blog/building-a-cpu',
  path: '/blog/building-a-cpu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/splash3': typeof Splash3Route
  '/splash4': typeof Splash4Route
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/splash3': typeof Splash3Route
  '/splash4': typeof Splash4Route
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog': typeof BlogIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/splash3': typeof Splash3Route
  '/splash4': typeof Splash4Route
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/challenges/build-a-cpu': typeof ChallengesBuildACpuRoute
  '/challenges/build-an-alu': typeof ChallengesBuildAnAluRoute
  '/challenges/snake': typeof ChallengesSnakeRoute
  '/learn/cpu': typeof LearnCpuRoute
  '/learn/dual-cpu': typeof LearnDualCpuRoute
  '/learn/program-counter': typeof LearnProgramCounterRoute
  '/blog/': typeof BlogIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/splash3'
    | '/splash4'
    | '/blog/building-a-cpu'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/snake'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog/'
    | '/challenges/'
    | '/docs/'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/splash3'
    | '/splash4'
    | '/blog/building-a-cpu'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/snake'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog'
    | '/challenges'
    | '/docs'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/splash3'
    | '/splash4'
    | '/blog/building-a-cpu'
    | '/blog/computing-trig-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/snake-in-hardware'
    | '/challenges/build-a-cpu'
    | '/challenges/build-an-alu'
    | '/challenges/snake'
    | '/learn/cpu'
    | '/learn/dual-cpu'
    | '/learn/program-counter'
    | '/blog/'
    | '/challenges/'
    | '/docs/'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  Splash3Route: typeof Splash3Route
  Splash4Route: typeof Splash4Route
  BlogBuildingACpuRoute: typeof BlogBuildingACpuRoute
  BlogComputingTrigInHardwareRoute: typeof BlogComputingTrigInHardwareRoute
  BlogHowNetworkSwitchesWorkRoute: typeof BlogHowNetworkSwitchesWorkRoute
  BlogHowTpusWorkRoute: typeof BlogHowTpusWorkRoute
  BlogPongInHardwareRoute: typeof BlogPongInHardwareRoute
  BlogSnakeInHardwareRoute: typeof BlogSnakeInHardwareRoute
  ChallengesBuildACpuRoute: typeof ChallengesBuildACpuRoute
  ChallengesBuildAnAluRoute: typeof ChallengesBuildAnAluRoute
  ChallengesSnakeRoute: typeof ChallengesSnakeRoute
  LearnCpuRoute: typeof LearnCpuRoute
  LearnDualCpuRoute: typeof LearnDualCpuRoute
  LearnProgramCounterRoute: typeof LearnProgramCounterRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash4': {
      id: '/splash4'
      path: '/splash4'
      fullPath: '/splash4'
      preLoaderRoute: typeof Splash4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash3': {
      id: '/splash3'
      path: '/splash3'
      fullPath: '/splash3'
      preLoaderRoute: typeof Splash3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/program-counter': {
      id: '/learn/program-counter'
      path: '/learn/program-counter'
      fullPath: '/learn/program-counter'
      preLoaderRoute: typeof LearnProgramCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/dual-cpu': {
      id: '/learn/dual-cpu'
      path: '/learn/dual-cpu'
      fullPath: '/learn/dual-cpu'
      preLoaderRoute: typeof LearnDualCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/cpu': {
      id: '/learn/cpu'
      path: '/learn/cpu'
      fullPath: '/learn/cpu'
      preLoaderRoute: typeof LearnCpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/snake': {
      id: '/challenges/snake'
      path: '/challenges/snake'
      fullPath: '/challenges/snake'
      preLoaderRoute: typeof ChallengesSnakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/build-an-alu': {
      id: '/challenges/build-an-alu'
      path: '/challenges/build-an-alu'
      fullPath: '/challenges/build-an-alu'
      preLoaderRoute: typeof ChallengesBuildAnAluRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/build-a-cpu': {
      id: '/challenges/build-a-cpu'
      path: '/challenges/build-a-cpu'
      fullPath: '/challenges/build-a-cpu'
      preLoaderRoute: typeof ChallengesBuildACpuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/snake-in-hardware': {
      id: '/blog/snake-in-hardware'
      path: '/blog/snake-in-hardware'
      fullPath: '/blog/snake-in-hardware'
      preLoaderRoute: typeof BlogSnakeInHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/pong-in-hardware': {
      id: '/blog/pong-in-hardware'
      path: '/blog/pong-in-hardware'
      fullPath: '/blog/pong-in-hardware'
      preLoaderRoute: typeof BlogPongInHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-tpus-work': {
      id: '/blog/how-tpus-work'
      path: '/blog/how-tpus-work'
      fullPath: '/blog/how-tpus-work'
      preLoaderRoute: typeof BlogHowTpusWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-network-switches-work': {
      id: '/blog/how-network-switches-work'
      path: '/blog/how-network-switches-work'
      fullPath: '/blog/how-network-switches-work'
      preLoaderRoute: typeof BlogHowNetworkSwitchesWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/computing-trig-in-hardware': {
      id: '/blog/computing-trig-in-hardware'
      path: '/blog/computing-trig-in-hardware'
      fullPath: '/blog/computing-trig-in-hardware'
      preLoaderRoute: typeof BlogComputingTrigInHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/building-a-cpu': {
      id: '/blog/building-a-cpu'
      path: '/blog/building-a-cpu'
      fullPath: '/blog/building-a-cpu'
      preLoaderRoute: typeof BlogBuildingACpuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  Splash3Route: Splash3Route,
  Splash4Route: Splash4Route,
  BlogBuildingACpuRoute: BlogBuildingACpuRoute,
  BlogComputingTrigInHardwareRoute: BlogComputingTrigInHardwareRoute,
  BlogHowNetworkSwitchesWorkRoute: BlogHowNetworkSwitchesWorkRoute,
  BlogHowTpusWorkRoute: BlogHowTpusWorkRoute,
  BlogPongInHardwareRoute: BlogPongInHardwareRoute,
  BlogSnakeInHardwareRoute: BlogSnakeInHardwareRoute,
  ChallengesBuildACpuRoute: ChallengesBuildACpuRoute,
  ChallengesBuildAnAluRoute: ChallengesBuildAnAluRoute,
  ChallengesSnakeRoute: ChallengesSnakeRoute,
  LearnCpuRoute: LearnCpuRoute,
  LearnDualCpuRoute: LearnDualCpuRoute,
  LearnProgramCounterRoute: LearnProgramCounterRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
