;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_print_ok
	.export		_print_colon
	.export		_print_a
	.export		_print_b
	.export		_print_c
	.export		_main

; ---------------------------------------------------------------
; void __near__ print_ok (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_ok: near

.segment	"CODE"

	lda     #$4F
	sta     $F000
	lda     #$4B
	sta     $F000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ print_colon (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_colon: near

.segment	"CODE"

	lda     #$3A
	sta     $F000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ print_a (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_a: near

.segment	"CODE"

	lda     #$41
	sta     $F000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ print_b (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_b: near

.segment	"CODE"

	lda     #$42
	sta     $F000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ print_c (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print_c: near

.segment	"CODE"

	lda     #$43
	sta     $F000
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _print_ok
	jsr     _print_colon
	jsr     _print_a
	jsr     _print_b
	jsr     _print_c
	lda     #$0A
	sta     $F000
L0025:	jmp     L0025

.endproc

