;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_putchar
	.export		_puts
	.export		_main

.segment	"RODATA"

L000C:
	.byte	$48,$65,$6C,$6C,$6F,$2C,$20,$36,$35,$30,$32,$21,$00

; ---------------------------------------------------------------
; void __near__ puts (__near__ const unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_puts: near

.segment	"CODE"

	jsr     pushax
	jmp     L0004
L0002:	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	jsr     stax0sp
	ldy     #$00
	lda     (regsave),y
	jsr     _putchar
L0004:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0002
	lda     #$0A
	jsr     _putchar
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L000C)
	ldx     #>(L000C)
	jsr     _puts
	ldx     #$00
	txa
	rts

.endproc

