/**
 * Circuit definitions for the "Breakout in Hardware" blog post.
 * 32x16 raster-scan architecture with DualPortRAM brick storage.
 *
 * Synthesizable, snake-style I/O with a combinational raster render (like a real
 * raster display): the browser drives `scan_addr`, which splits into
 * `scanX`/`scanY` and feeds the pixel logic straight to `pixel_out`, with no
 * framebuffer, so a render is one combinational sweep and never advances the
 * clock. Game state advances one step per clock tick (throttled by the ball/
 * paddle speed counters), so a game step is a single tick: the browser ticks a
 * handful of times per animation frame, exactly like snake. Paddle input arrives
 * on the top-level `keyboard` bus.
 */

import { bit, bus, circuit } from '@simten/core/circuit';
import {
  Adder,
  And,
  BitSlice,
  Buffer,
  Comparator,
  Constant,
  DualPortRAM,
  LeftShifter,
  Mux,
  Not,
  Or,
  Register,
  RightShifter,
  Splitter8to8,
  Subtractor,
} from '@simten/core/std';

// Full brick wall at power-on: rows 0-3 (128 cells) all alive. Seeded into
// brickRAM's memory so the wall is present on the first frame instead of
// streaming in over the fill counter's 128 ticks.
const FULL_WALL: Record<number, number> = {};
for (let i = 0; i < 128; i++) FULL_WALL[i] = 1;

export const Breakout = circuit('Breakout', {
  // game_en is a clock enable for the game logic: high advances the ball/paddle
  // one step. The fill FSM ignores it and runs at the full clock. On the FPGA
  // the clock runs fast (so the wall redraw is instant) and game_en is pulsed at
  // ~30 Hz; the browser holds game_en high and ticks at the game rate instead.
  inputs: { scan_addr: bus(9), keyboard: bus(8), game_en: bit },
  // `is_filling` is a status/"busy" output: high while the fill FSM is redrawing
  // the wall after a death. The browser bursts the clock while it's high so the
  // ~128-cycle redraw (instant on the FPGA) is instant in the demo too.
  outputs: { pixel_out: bus(8), is_filling: bit },
  nodes: {
    brickRAM: DualPortRAM({ memory: FULL_WALL }),
    // Combinational raster render: scan_addr → scanX/scanY → pixel_out (no
    // framebuffer).
    scanX: BitSlice({ low: 0, high: 4 }),
    scanY: RightShifter({ width: 9 }),
    c0: Constant({ value: 0 }),
    c1: Constant({ value: 1 }),
    c2: Constant({ value: 2 }),
    c3: Constant({ value: 3 }),
    c4: Constant({ value: 4 }),
    c5: Constant({ value: 5 }),
    c14: Constant({ value: 14 }),
    c15: Constant({ value: 15 }),
    c16: Constant({ value: 16 }),
    c28: Constant({ value: 28 }),
    c29: Constant({ value: 29 }),
    c30: Constant({ value: 30 }),
    c31: Constant({ value: 31 }),
    c32: Constant({ value: 32 }),
    c253: Constant({ value: 253 }),
    c254: Constant({ value: 254 }),
    c255: Constant({ value: 255 }),
    ballX: Register({ value: 16 }),
    ballY: Register({ value: 8 }),
    ballDX: Register({ value: 1 }),
    ballDY: Register({ value: 255 }),
    paddleX: Register({ value: 15 }),
    leftCode: Constant({ value: 75 }),
    rightCode: Constant({ value: 77 }),
    isLeftCmp: Comparator(),
    isRightCmp: Comparator(),
    scanYsh: LeftShifter({ width: 8 }),
    scanBrickAddr: Adder({ width: 8 }),
    scanInBrickArea: Comparator(),
    brickAlive: Comparator(),
    brickPixel: And,
    cmpBallX: Comparator(),
    cmpBallY: Comparator(),
    ballPixel: And,
    scanYsplit: Splitter8to8,
    notScanY4: Not,
    notScanY5: Not,
    notScanY6: Not,
    notScanY7: Not,
    isScanY15a: And,
    isScanY15b: And,
    isScanY15c: And,
    isScanY15d: And,
    isScanY15e: And,
    isScanY15f: And,
    isScanY15: And,
    padMinRaw: Adder({ width: 8 }),
    padMaxRaw: Adder({ width: 8 }),
    cmpScanGteMin: Comparator(),
    notLtPadMin: Not,
    cmpScanLteMax: Comparator(),
    notGtPadMax: Not,
    inPadRange: And,
    paddlePixel: And,
    pixOr1: Or,
    pixOr2: Or,
    pixelBus: Mux({ width: 8 }),
    ballSpeedCtr: Register({ value: 0 }),
    ballSpeedInc: Adder({ width: 8 }),
    ballSpeedMax: Constant({ value: 3 }),
    ballSpeedAtMax: Comparator(),
    nextBallSpeed: Mux({ width: 8 }),
    ballUpdate: And,
    padSpeedCtr: Register({ value: 0 }),
    padSpeedInc: Adder({ width: 8 }),
    padSpeedMax: Constant({ value: 1 }),
    padSpeedAtMax: Comparator(),
    nextPadSpeed: Mux({ width: 8 }),
    paddleUpdate: And,
    movingLeftCmp: Comparator(),
    c127: Constant({ value: 127 }),
    movingLeft: Buffer,
    notMovingLeft: Not,
    movingUpCmp: Comparator(),
    movingUp: Buffer,
    movingDown: Not,
    ballAtLeft: Comparator(),
    hitLeft: And,
    ballAtRight: Comparator(),
    notBallLtRight: Not,
    hitRight: And,
    flipDX: Or,
    ballAtTop: Comparator(),
    hitTop: And,
    dxNegated: Subtractor({ width: 8 }),
    newDXbeforePaddle: Mux({ width: 8 }),
    nextBallXraw: Adder({ width: 8 }),
    dyNegated: Subtractor({ width: 8 }),
    topBouncedDY: Mux({ width: 8 }),
    nextBallYraw: Adder({ width: 8 }),
    nextYsh: LeftShifter({ width: 8 }),
    nextBrickAddr: Adder({ width: 8 }),
    nextInBrickArea: Comparator(),
    brickAtNext: Comparator(),
    hitBrickRaw: And,
    hitBrick: And,
    nextYis14: Comparator(),
    cmpNextGteMin: Comparator(),
    notNextLtMin: Not,
    cmpNextLteMax: Comparator(),
    notNextGtMax: Not,
    nextInPadRange: And,
    paddleHitCheck: And,
    hitPaddle: And,
    padOffset: Subtractor({ width: 8 }),
    isFarLeft: Comparator(),
    offsetLt254: Comparator(),
    isMidLeft: Not,
    isMidRight: Comparator(),
    isFarRight: Comparator(),
    paddleDXa: Mux({ width: 8 }),
    paddleDXb: Mux({ width: 8 }),
    paddleDXc: Mux({ width: 8 }),
    newDX: Mux({ width: 8 }),
    flipDYa: Or,
    flipDY: Or,
    newDY: Mux({ width: 8 }),
    topDYneg: Subtractor({ width: 8 }),
    paddleBrickFlipDY: Or,
    finalDY: Mux({ width: 8 }),
    nextYlt15: Comparator(),
    nextYge15: Not,
    ballAtBottom: And,
    notHitPaddle: Not,
    ballMissed: And,
    resetX: Constant({ value: 16 }),
    resetY: Constant({ value: 8 }),
    resetDX: Constant({ value: 1 }),
    resetDY: Constant({ value: 255 }),
    actualBallX: Mux({ width: 8 }),
    actualBallY: Mux({ width: 8 }),
    actualDX: Mux({ width: 8 }),
    actualDY: Mux({ width: 8 }),
    // On a brick hit, reflect the Y position THIS frame so the ball bounces off
    // the brick face instead of stepping into the cell (paddle already bounces
    // one row early, so it keeps its own position path).
    brickDY: Mux({ width: 8 }),
    reflectY: Adder({ width: 8 }),
    paddleDelta: Mux({ width: 8 }),
    paddleDelta2: Mux({ width: 8 }),
    paddleXnewRaw: Adder({ width: 8 }),
    paddleAtMin: Comparator(),
    paddleAtMax: Comparator(),
    paddleClamped1: Mux({ width: 8 }),
    newPaddleX: Mux({ width: 8 }),
    // fillCtr starts at 0 so the fill FSM draws the wall on power-on/reset (this
    // is what runs on the FPGA, where rst_n can't restore RAM). brickRAM's memory
    // init models the FPGA's $readmemh so the wall shows before the FSM even runs.
    fillCtr: Register({ value: 0 }),
    fillCtrInc: Adder({ width: 8 }),
    isFilling: Comparator(),
    c128: Constant({ value: 128 }),
    fillNext: Mux({ width: 8 }),
    onMissVblank: And,
    fillCtrData: Mux({ width: 8 }),
    fillCtrWe: Or,
    brickHitWe: And,
    fillWe: And,
    brickRAMweA: Or,
    brickRAMaddrA: Mux({ width: 8 }),
    brickRAMdataA: Mux({ width: 8 }),
    // Ball is held still while the wall redraws (isFilling) after a death, then
    // launches once the wall is complete. The miss itself still writes (resets
    // the ball to center) via the `ballMissed` term so the hold can't deadlock.
    notFilling: Not,
    ballAndFill: And,
  },
  connect: ({
    inputs,
    outputs,
    nodes: {
      brickRAM,
      scanX,
      scanY,
      c0,
      c1,
      c2,
      c3,
      c4,
      c5,
      c14,
      c15,
      c28,
      c30,
      c253,
      c254,
      c255,
      ballX,
      ballY,
      ballDX,
      ballDY,
      paddleX,
      leftCode,
      rightCode,
      isLeftCmp,
      isRightCmp,
      scanYsh,
      scanBrickAddr,
      scanInBrickArea,
      brickAlive,
      brickPixel,
      cmpBallX,
      cmpBallY,
      ballPixel,
      scanYsplit,
      notScanY4,
      notScanY5,
      notScanY6,
      notScanY7,
      isScanY15a,
      isScanY15b,
      isScanY15c,
      isScanY15d,
      isScanY15e,
      isScanY15f,
      isScanY15,
      padMinRaw,
      padMaxRaw,
      cmpScanGteMin,
      notLtPadMin,
      cmpScanLteMax,
      notGtPadMax,
      inPadRange,
      paddlePixel,
      pixOr1,
      pixOr2,
      pixelBus,
      ballSpeedCtr,
      ballSpeedInc,
      ballSpeedMax,
      ballSpeedAtMax,
      nextBallSpeed,
      ballUpdate,
      padSpeedCtr,
      padSpeedInc,
      padSpeedMax,
      padSpeedAtMax,
      nextPadSpeed,
      paddleUpdate,
      movingLeftCmp,
      c127,
      movingLeft,
      notMovingLeft,
      movingUpCmp,
      movingUp,
      movingDown,
      ballAtLeft,
      hitLeft,
      ballAtRight,
      notBallLtRight,
      hitRight,
      flipDX,
      ballAtTop,
      hitTop,
      dxNegated,
      newDXbeforePaddle,
      nextBallXraw,
      dyNegated,
      topBouncedDY,
      nextBallYraw,
      nextYsh,
      nextBrickAddr,
      nextInBrickArea,
      brickAtNext,
      hitBrickRaw,
      hitBrick,
      nextYis14,
      cmpNextGteMin,
      notNextLtMin,
      cmpNextLteMax,
      notNextGtMax,
      nextInPadRange,
      paddleHitCheck,
      hitPaddle,
      padOffset,
      isFarLeft,
      offsetLt254,
      isMidLeft,
      isMidRight,
      isFarRight,
      paddleDXa,
      paddleDXb,
      paddleDXc,
      newDX,
      flipDYa,
      flipDY,
      newDY,
      topDYneg,
      paddleBrickFlipDY,
      finalDY,
      nextYlt15,
      nextYge15,
      ballAtBottom,
      notHitPaddle,
      ballMissed,
      resetX,
      resetY,
      resetDX,
      resetDY,
      actualBallX,
      actualBallY,
      actualDX,
      actualDY,
      paddleDelta,
      paddleDelta2,
      paddleXnewRaw,
      paddleAtMin,
      paddleAtMax,
      paddleClamped1,
      newPaddleX,
      brickDY,
      reflectY,
      notFilling,
      ballAndFill,
      fillCtr,
      fillCtrInc,
      isFilling,
      c128,
      fillNext,
      onMissVblank,
      fillCtrData,
      fillCtrWe,
      brickHitWe,
      fillWe,
      brickRAMweA,
      brickRAMaddrA,
      brickRAMdataA,
    },
  }) => [
    // --- Combinational raster render: scan_addr → scanX/scanY → pixel_out ---
    // scanX = scan_addr[4:0] (0..31), scanY = scan_addr >> 5 (0..15)
    inputs.scan_addr.to(scanX.in, scanY.value),
    scanX.out.to(scanBrickAddr.b, cmpBallX.a, cmpScanGteMin.a, cmpScanLteMax.b),
    scanY.result.to(scanYsh.value, scanInBrickArea.a, cmpBallY.a, scanYsplit.in),
    // --- Input (top-level ports) ---
    inputs.keyboard.to(isLeftCmp.a, isRightCmp.a),
    leftCode.out.to(isLeftCmp.b),
    rightCode.out.to(isRightCmp.b),
    c5.out.to(scanYsh.shift, nextYsh.shift, scanY.shift),
    scanYsh.result.to(scanBrickAddr.a),
    c0.out.to(
      scanBrickAddr.carry_in,
      brickAlive.b,
      padMinRaw.carry_in,
      padMaxRaw.carry_in,
      pixelBus.in0,
      ballSpeedInc.carry_in,
      nextBallSpeed.in1,
      padSpeedInc.carry_in,
      nextPadSpeed.in1,
      ballAtTop.b,
      dxNegated.a,
      dxNegated.borrow_in,
      nextBallXraw.carry_in,
      dyNegated.a,
      dyNegated.borrow_in,
      nextBallYraw.carry_in,
      nextBrickAddr.carry_in,
      brickAtNext.b,
      padOffset.borrow_in,
      topDYneg.a,
      topDYneg.borrow_in,
      paddleDelta.in0,
      paddleXnewRaw.carry_in,
      fillCtrInc.carry_in,
      fillCtrData.in1,
      brickRAMdataA.in0,
      reflectY.carry_in,
    ),
    scanBrickAddr.sum.to(brickRAM.addrB),
    c4.out.to(scanInBrickArea.b, nextInBrickArea.b),
    brickRAM.outB.to(brickAlive.a),
    scanInBrickArea.lt.to(brickPixel.a),
    brickAlive.gt.to(brickPixel.b),
    ballX.q.to(cmpBallX.b, ballAtLeft.a, ballAtRight.a, nextBallXraw.a),
    ballY.q.to(cmpBallY.b, ballAtTop.a, nextBallYraw.a, reflectY.a),
    cmpBallX.eq.to(ballPixel.a),
    cmpBallY.eq.to(ballPixel.b),
    scanYsplit.bit4.to(notScanY4.in),
    scanYsplit.bit5.to(notScanY5.in),
    scanYsplit.bit6.to(notScanY6.in),
    scanYsplit.bit7.to(notScanY7.in),
    scanYsplit.bit0.to(isScanY15a.a),
    scanYsplit.bit1.to(isScanY15a.b),
    scanYsplit.bit2.to(isScanY15b.a),
    scanYsplit.bit3.to(isScanY15b.b),
    isScanY15a.out.to(isScanY15c.a),
    isScanY15b.out.to(isScanY15c.b),
    notScanY4.out.to(isScanY15d.a),
    notScanY5.out.to(isScanY15d.b),
    notScanY6.out.to(isScanY15e.a),
    notScanY7.out.to(isScanY15e.b),
    isScanY15d.out.to(isScanY15f.a),
    isScanY15e.out.to(isScanY15f.b),
    isScanY15c.out.to(isScanY15.a),
    isScanY15f.out.to(isScanY15.b),
    paddleX.q.to(padMinRaw.a, padMaxRaw.a, padOffset.b, paddleXnewRaw.a),
    c253.out.to(padMinRaw.b, isFarLeft.b),
    c2.out.to(padMaxRaw.b, ballAtLeft.b, isMidRight.b, isFarRight.b, paddleDXa.in1),
    padMinRaw.sum.to(cmpScanGteMin.b, cmpNextGteMin.b),
    cmpScanGteMin.lt.to(notLtPadMin.in),
    padMaxRaw.sum.to(cmpScanLteMax.a, cmpNextLteMax.a),
    cmpScanLteMax.lt.to(notGtPadMax.in),
    notLtPadMin.out.to(inPadRange.a),
    notGtPadMax.out.to(inPadRange.b),
    isScanY15.out.to(paddlePixel.a),
    inPadRange.out.to(paddlePixel.b),
    ballPixel.out.to(pixOr1.a),
    paddlePixel.out.to(pixOr1.b),
    pixOr1.out.to(pixOr2.a),
    brickPixel.out.to(pixOr2.b),
    c1.out.to(
      pixelBus.in1,
      ballSpeedInc.b,
      padSpeedInc.b,
      paddleDXa.in0,
      paddleDelta2.in1,
      fillCtrInc.b,
      brickRAMdataA.in1,
      fillWe.b,
    ),
    pixOr2.out.to(pixelBus.sel),
    pixelBus.out.to(outputs.pixel_out),
    ballSpeedCtr.q.to(ballSpeedInc.a, ballSpeedAtMax.a),
    ballSpeedMax.out.to(ballSpeedAtMax.b),
    ballSpeedInc.sum.to(nextBallSpeed.in0),
    ballSpeedAtMax.eq.to(nextBallSpeed.sel, ballUpdate.b),
    nextBallSpeed.out.to(ballSpeedCtr.data),
    inputs.game_en.to(ballSpeedCtr.we, ballUpdate.a, padSpeedCtr.we, paddleUpdate.a),
    padSpeedCtr.q.to(padSpeedInc.a, padSpeedAtMax.a),
    padSpeedMax.out.to(padSpeedAtMax.b),
    padSpeedInc.sum.to(nextPadSpeed.in0),
    padSpeedAtMax.eq.to(nextPadSpeed.sel, paddleUpdate.b),
    nextPadSpeed.out.to(padSpeedCtr.data),
    c127.out.to(movingLeftCmp.a, movingUpCmp.a),
    ballDX.q.to(movingLeftCmp.b, dxNegated.b, newDXbeforePaddle.in0),
    movingLeftCmp.lt.to(movingLeft.in),
    movingLeft.out.to(notMovingLeft.in, hitLeft.b),
    ballDY.q.to(movingUpCmp.b, dyNegated.b, topBouncedDY.in0),
    movingUpCmp.lt.to(movingUp.in),
    movingUp.out.to(movingDown.in, hitTop.b, hitBrick.b),
    ballAtLeft.lt.to(hitLeft.a),
    c30.out.to(ballAtRight.b),
    ballAtRight.lt.to(notBallLtRight.in),
    notBallLtRight.out.to(hitRight.a),
    notMovingLeft.out.to(hitRight.b),
    hitLeft.out.to(flipDX.a),
    hitRight.out.to(flipDX.b),
    ballAtTop.eq.to(hitTop.a),
    dxNegated.difference.to(newDXbeforePaddle.in1),
    flipDX.out.to(newDXbeforePaddle.sel),
    newDXbeforePaddle.out.to(nextBallXraw.b, newDX.in0),
    dyNegated.difference.to(topBouncedDY.in1, newDY.in1),
    hitTop.out.to(topBouncedDY.sel, flipDYa.a),
    topBouncedDY.out.to(nextBallYraw.b, newDY.in0, topDYneg.b, finalDY.in0, brickDY.in0),
    nextBallYraw.sum.to(nextYsh.value, nextInBrickArea.a, nextYis14.a, nextYlt15.a),
    brickDY.out.to(reflectY.b),
    reflectY.sum.to(actualBallY.in0),
    nextYsh.result.to(nextBrickAddr.a),
    nextBallXraw.sum.to(
      nextBrickAddr.b,
      cmpNextGteMin.a,
      cmpNextLteMax.b,
      padOffset.a,
      actualBallX.in0,
    ),
    brickRAM.outA.to(brickAtNext.a),
    nextInBrickArea.lt.to(hitBrickRaw.a),
    brickAtNext.gt.to(hitBrickRaw.b),
    hitBrickRaw.out.to(hitBrick.a),
    c14.out.to(nextYis14.b),
    cmpNextGteMin.lt.to(notNextLtMin.in),
    cmpNextLteMax.lt.to(notNextGtMax.in),
    notNextLtMin.out.to(nextInPadRange.a),
    notNextGtMax.out.to(nextInPadRange.b),
    nextYis14.eq.to(paddleHitCheck.a),
    nextInPadRange.out.to(paddleHitCheck.b),
    paddleHitCheck.out.to(hitPaddle.a),
    movingDown.out.to(hitPaddle.b, ballAtBottom.b),
    padOffset.difference.to(isFarLeft.a, offsetLt254.a, isMidRight.a, isFarRight.a),
    c254.out.to(offsetLt254.b, paddleDXc.in1),
    offsetLt254.lt.to(isMidLeft.in),
    isFarRight.eq.to(paddleDXa.sel),
    paddleDXa.out.to(paddleDXb.in0),
    c255.out.to(paddleDXb.in1, paddleDelta.in1),
    isMidLeft.out.to(paddleDXb.sel),
    paddleDXb.out.to(paddleDXc.in0),
    isFarLeft.eq.to(paddleDXc.sel),
    paddleDXc.out.to(newDX.in1),
    hitPaddle.out.to(newDX.sel, flipDYa.b, newDY.sel, paddleBrickFlipDY.a, notHitPaddle.in),
    flipDYa.out.to(flipDY.a),
    hitBrick.out.to(flipDY.b, paddleBrickFlipDY.b, brickHitWe.b, brickDY.sel),
    topDYneg.difference.to(finalDY.in1, brickDY.in1),
    paddleBrickFlipDY.out.to(finalDY.sel),
    c15.out.to(nextYlt15.b),
    nextYlt15.lt.to(nextYge15.in),
    nextYge15.out.to(ballAtBottom.a),
    ballAtBottom.out.to(ballMissed.a),
    notHitPaddle.out.to(ballMissed.b),
    resetX.out.to(actualBallX.in1),
    ballMissed.out.to(actualBallX.sel, actualBallY.sel, actualDX.sel, actualDY.sel, onMissVblank.b),
    resetY.out.to(actualBallY.in1),
    newDX.out.to(actualDX.in0),
    resetDX.out.to(actualDX.in1),
    finalDY.out.to(actualDY.in0),
    resetDY.out.to(actualDY.in1),
    actualBallX.out.to(ballX.data),
    actualBallY.out.to(ballY.data),
    actualDX.out.to(ballDX.data),
    actualDY.out.to(ballDY.data),
    // A miss is handled on the ball's move pulse: onMissVblank = ballUpdate AND
    // ballMissed, so the reset and the wall refill fire together on the same
    // step, for both game_en=1 (browser) and a pulsed game_en (FPGA). The ball
    // is reset via ballAndFill on that pulse (before the fill's hold engages).
    ballUpdate.out.to(ballAndFill.a, onMissVblank.a),
    notFilling.out.to(ballAndFill.b),
    ballAndFill.out.to(ballX.we, ballY.we, ballDX.we, ballDY.we, brickHitWe.a),
    isLeftCmp.eq.to(paddleDelta.sel),
    paddleDelta.out.to(paddleDelta2.in0),
    isRightCmp.eq.to(paddleDelta2.sel),
    paddleDelta2.out.to(paddleXnewRaw.b),
    paddleXnewRaw.sum.to(paddleAtMin.a, paddleAtMax.a, paddleClamped1.in0),
    c3.out.to(paddleAtMin.b, paddleClamped1.in1),
    c28.out.to(paddleAtMax.b, newPaddleX.in1),
    paddleAtMin.lt.to(paddleClamped1.sel),
    paddleClamped1.out.to(newPaddleX.in0),
    paddleAtMax.gt.to(newPaddleX.sel),
    newPaddleX.out.to(paddleX.data),
    paddleUpdate.out.to(paddleX.we),
    fillCtr.q.to(fillCtrInc.a, isFilling.a, fillNext.in0, brickRAMaddrA.in1),
    // On a miss, onMissVblank drives fillCtrData.sel → in1 (= 0), which restarts
    // the fill FSM: it rewrites all 128 bricks over the next 128 clocks. On the
    // FPGA that's microseconds (instant); the browser bursts those clocks so the
    // wall redraws instantly in the demo too. The ball is held (see ballWrite)
    // while it redraws so it can't tunnel through half-drawn bricks.
    c128.out.to(isFilling.b),
    fillCtrInc.sum.to(fillNext.in1),
    isFilling.lt.to(
      fillNext.sel,
      fillCtrWe.a,
      fillWe.a,
      brickRAMaddrA.sel,
      brickRAMdataA.sel,
      notFilling.in,
      outputs.is_filling,
    ),
    fillNext.out.to(fillCtrData.in0),
    onMissVblank.out.to(fillCtrData.sel, fillCtrWe.b),
    fillCtrData.out.to(fillCtr.data),
    fillCtrWe.out.to(fillCtr.we),
    brickHitWe.out.to(brickRAMweA.a),
    fillWe.out.to(brickRAMweA.b),
    nextBrickAddr.sum.to(brickRAMaddrA.in0),
    brickRAMaddrA.out.to(brickRAM.addrA),
    brickRAMdataA.out.to(brickRAM.dataA),
    brickRAMweA.out.to(brickRAM.weA),
  ],
});
