/**
 * Drift guard for the globals filter.
 *
 * `buildGlobalsFor` parses a file generated by another package's build script.
 * The format is stable by construction, but "by construction" is a claim, and
 * the failure mode if it changes is silent: components quietly vanish from the
 * editor and a level becomes unsolvable with no error anywhere. These assert
 * the parse still finds what the blob contains.
 */

import { describe, expect, it } from 'vitest';
import { SIMTEN_CORE_GLOBALS } from '../generated/core-types.gen';
import { buildGlobalsFor, knownGlobalNames } from '../globals-subset';

describe('parsing the generated shim', () => {
  it('finds the core API and a representative spread of stdlib', () => {
    const names = knownGlobalNames();
    for (const expected of ['circuit', 'bit', 'bus', 'Nand', 'And', 'Switch', 'Led', 'Register']) {
      expect(names).toContain(expected);
    }
  });

  it('finds every declaration the blob contains', () => {
    // Counted independently of the parser, so a regex that silently matched
    // fewer things would not also shrink the expectation.
    const declared = [...SIMTEN_CORE_GLOBALS.matchAll(/^\s*const ([A-Za-z_$][\w$]*)\s*:/gm)].map(
      (m) => m[1],
    );
    expect(knownGlobalNames().sort()).toEqual([...new Set(declared)].sort());
  });
});

describe('building a subset', () => {
  it('includes what was asked for, with its docs', () => {
    const shim = buildGlobalsFor(['Nand']);
    expect(shim).toContain('const Nand:');
    // The JSDoc is the point — without it the editor loses hover docs, which
    // is most of what makes writing circuits in TypeScript pleasant.
    expect(shim).toMatch(/\/\*\*[\s\S]*?\*\/\n\s*const Nand:/);
  });

  it('excludes what was not', () => {
    const shim = buildGlobalsFor(['Nand']);
    expect(shim).not.toContain('const Xor:');
    expect(shim).not.toContain('const Or:');
  });

  it('always keeps the circuit API, which is not a reward', () => {
    const shim = buildGlobalsFor([]);
    for (const always of ['circuit', 'bit', 'bus', 'reg', 'mem']) {
      expect(shim).toContain(`const ${always}:`);
    }
  });

  it('closes the declare block so the shim is valid on its own', () => {
    const shim = buildGlobalsFor(['Nand']);
    expect(shim).toContain('declare global {');
    expect(shim.trimEnd().endsWith('export {};')).toBe(true);
    // Balanced braces — an unclosed block would take every later lib with it.
    const opens = (shim.match(/\{/g) ?? []).length;
    const closes = (shim.match(/\}/g) ?? []).length;
    expect(closes).toBeGreaterThanOrEqual(opens);
  });

  it('skips an unknown name rather than throwing', () => {
    expect(() => buildGlobalsFor(['NoSuchComponent'])).not.toThrow();
    expect(buildGlobalsFor(['NoSuchComponent'])).not.toContain('NoSuchComponent');
  });
});
