// Auto-generated

const RV32I_CPU = circuit('RV32I_CPU', {
  out: { pc_out: bus(32), alu_result: bus(32) },
  nodes: { imem: RV32I_InstrMem, pc: Register, pc_plus4: Adder, pc_we: Constant, four: Constant, decode: RV32I_Decode, immgen: RV32I_ImmGen, control: RV32I_Control, funct7_splitter: BitSlice, regfile: RV32I_RegisterFile, alu_src_mux: Mux, alu: RV32I_ALU, branch_comp: RV32I_BranchComp, dmem: RV32I_DataMem, pc_plus_imm: Adder, wb_mux: RV32I_WritebackMux, branch_target: Adder, jalr_target: BusAnd, jalr_mask: Constant, next_pc: RV32I_NextPCMux },
  nodeArgs: { pc: { width: 32 }, pc_plus4: { width: 32 }, pc_we: { value: 1, width: 1 }, four: { value: 4, width: 32 }, funct7_splitter: { low: 5, high: 5 }, alu_src_mux: { width: 32 }, pc_plus_imm: { width: 32 }, branch_target: { width: 32 }, jalr_target: { width: 32 }, jalr_mask: { value: 4294967294, width: 32 } },
  connect: ({ in: inp, out, imem, pc, pc_plus4, pc_we, four, decode, immgen, control, funct7_splitter, regfile, alu_src_mux, alu, branch_comp, dmem, pc_plus_imm, wb_mux, branch_target, jalr_target, jalr_mask, next_pc }) => [
    pc.q.to(pc_plus4.a, imem.addr, pc_plus_imm.a, branch_target.a, out.pc_out),
    four.out.to(pc_plus4.b),
    pc_we.out.to(pc.we),
    imem.instruction.to(decode.instruction, immgen.instruction),
    decode.opcode.to(control.opcode),
    decode.funct3.to(control.funct3, branch_comp.funct3, dmem.funct3),
    decode.funct7.to(funct7_splitter.in),
    funct7_splitter.out.to(control.funct7_bit),
    decode.rs1.to(regfile.rs1),
    decode.rs2.to(regfile.rs2),
    decode.rd.to(regfile.rd),
    control.reg_write.to(regfile.we),
    regfile.read2.to(alu_src_mux.in0, branch_comp.b, dmem.write_data),
    immgen.immediate.to(alu_src_mux.in1, pc_plus_imm.b, wb_mux.immediate, branch_target.b),
    control.alu_src.to(alu_src_mux.sel),
    regfile.read1.to(alu.a, branch_comp.a),
    alu_src_mux.out.to(alu.b),
    control.alu_op.to(alu.alu_op),
    alu.result.to(dmem.addr, wb_mux.alu_result, jalr_target.a, out.alu_result),
    control.mem_read.to(dmem.mem_read),
    control.mem_write.to(dmem.mem_write),
    dmem.read_data.to(wb_mux.load_data),
    pc_plus4.sum.to(wb_mux.pc_plus4, next_pc.pc_plus4),
    pc_plus_imm.sum.to(wb_mux.pc_plus_imm),
    control.mem_to_reg.to(wb_mux.mem_to_reg),
    control.lui.to(wb_mux.lui),
    control.auipc.to(wb_mux.auipc),
    control.jump.to(wb_mux.jump, next_pc.jump),
    wb_mux.write_data.to(regfile.write_data),
    jalr_mask.out.to(jalr_target.b),
    branch_target.sum.to(next_pc.branch_target, next_pc.jal_target),
    jalr_target.out.to(next_pc.jalr_target),
    control.branch.to(next_pc.branch),
    branch_comp.take_branch.to(next_pc.take_branch),
    control.is_jalr.to(next_pc.is_jalr),
    next_pc.next_pc.to(pc.data),
  ],
})
