/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CircuitRouteImport } from './routes/circuit'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as CpuIndexRouteImport } from './routes/cpu/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LearnRegistersRouteImport } from './routes/learn/registers'
import { Route as LearnAddersRouteImport } from './routes/learn/adders'
import { Route as LearnAbstractionRouteImport } from './routes/learn/abstraction'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as CpuRv32iRouteImport } from './routes/cpu/rv32i'
import { Route as CircuitEncodedRouteImport } from './routes/circuit_.$encoded'
import { Route as BlogSortingNetworksRouteImport } from './routes/blog/sorting-networks'
import { Route as BlogSnakeInHardwareRouteImport } from './routes/blog/snake-in-hardware'
import { Route as BlogRv32iCpuRouteImport } from './routes/blog/rv32i-cpu'
import { Route as BlogPongInHardwareRouteImport } from './routes/blog/pong-in-hardware'
import { Route as BlogHowTpusWorkRouteImport } from './routes/blog/how-tpus-work'
import { Route as BlogHowNetworkSwitchesWorkRouteImport } from './routes/blog/how-network-switches-work'
import { Route as BlogCrc32InHardwareRouteImport } from './routes/blog/crc32-in-hardware'
import { Route as BlogComputingTrigInHardwareRouteImport } from './routes/blog/computing-trig-in-hardware'
import { Route as BlogChacha20InHardwareRouteImport } from './routes/blog/chacha20-in-hardware'
import { Route as BlogBuildingACpuRouteImport } from './routes/blog/building-a-cpu'
import { Route as BlogBreakoutInHardwareRouteImport } from './routes/blog/breakout-in-hardware'
import { Route as BlogAesInHardwareRouteImport } from './routes/blog/aes-in-hardware'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as CircuitSHashRouteImport } from './routes/circuit_.s.$hash'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitRoute = CircuitRouteImport.update({
  id: '/circuit',
  path: '/circuit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const CpuIndexRoute = CpuIndexRouteImport.update({
  id: '/cpu/',
  path: '/cpu/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const LearnRegistersRoute = LearnRegistersRouteImport.update({
  id: '/learn/registers',
  path: '/learn/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAddersRoute = LearnAddersRouteImport.update({
  id: '/learn/adders',
  path: '/learn/adders',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnAbstractionRoute = LearnAbstractionRouteImport.update({
  id: '/learn/abstraction',
  path: '/learn/abstraction',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CpuRv32iRoute = CpuRv32iRouteImport.update({
  id: '/cpu/rv32i',
  path: '/cpu/rv32i',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitEncodedRoute = CircuitEncodedRouteImport.update({
  id: '/circuit_/$encoded',
  path: '/circuit/$encoded',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSortingNetworksRoute = BlogSortingNetworksRouteImport.update({
  id: '/sorting-networks',
  path: '/sorting-networks',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSnakeInHardwareRoute = BlogSnakeInHardwareRouteImport.update({
  id: '/snake-in-hardware',
  path: '/snake-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogRv32iCpuRoute = BlogRv32iCpuRouteImport.update({
  id: '/rv32i-cpu',
  path: '/rv32i-cpu',
  getParentRoute: () => BlogRoute,
} as any)
const BlogPongInHardwareRoute = BlogPongInHardwareRouteImport.update({
  id: '/pong-in-hardware',
  path: '/pong-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHowTpusWorkRoute = BlogHowTpusWorkRouteImport.update({
  id: '/how-tpus-work',
  path: '/how-tpus-work',
  getParentRoute: () => BlogRoute,
} as any)
const BlogHowNetworkSwitchesWorkRoute =
  BlogHowNetworkSwitchesWorkRouteImport.update({
    id: '/how-network-switches-work',
    path: '/how-network-switches-work',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogCrc32InHardwareRoute = BlogCrc32InHardwareRouteImport.update({
  id: '/crc32-in-hardware',
  path: '/crc32-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogComputingTrigInHardwareRoute =
  BlogComputingTrigInHardwareRouteImport.update({
    id: '/computing-trig-in-hardware',
    path: '/computing-trig-in-hardware',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogChacha20InHardwareRoute = BlogChacha20InHardwareRouteImport.update({
  id: '/chacha20-in-hardware',
  path: '/chacha20-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBuildingACpuRoute = BlogBuildingACpuRouteImport.update({
  id: '/building-a-cpu',
  path: '/building-a-cpu',
  getParentRoute: () => BlogRoute,
} as any)
const BlogBreakoutInHardwareRoute = BlogBreakoutInHardwareRouteImport.update({
  id: '/breakout-in-hardware',
  path: '/breakout-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAesInHardwareRoute = BlogAesInHardwareRouteImport.update({
  id: '/aes-in-hardware',
  path: '/aes-in-hardware',
  getParentRoute: () => BlogRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CircuitSHashRoute = CircuitSHashRouteImport.update({
  id: '/circuit_/s/$hash',
  path: '/circuit/s/$hash',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/circuit': typeof CircuitRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/crc32-in-hardware': typeof BlogCrc32InHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/blog/sorting-networks': typeof BlogSortingNetworksRoute
  '/circuit/$encoded': typeof CircuitEncodedRoute
  '/cpu/rv32i': typeof CpuRv32iRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/abstraction': typeof LearnAbstractionRoute
  '/learn/adders': typeof LearnAddersRoute
  '/learn/registers': typeof LearnRegistersRoute
  '/blog/': typeof BlogIndexRoute
  '/cpu/': typeof CpuIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/circuit/s/$hash': typeof CircuitSHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circuit': typeof CircuitRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/crc32-in-hardware': typeof BlogCrc32InHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/blog/sorting-networks': typeof BlogSortingNetworksRoute
  '/circuit/$encoded': typeof CircuitEncodedRoute
  '/cpu/rv32i': typeof CpuRv32iRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/abstraction': typeof LearnAbstractionRoute
  '/learn/adders': typeof LearnAddersRoute
  '/learn/registers': typeof LearnRegistersRoute
  '/blog': typeof BlogIndexRoute
  '/cpu': typeof CpuIndexRoute
  '/learn': typeof LearnIndexRoute
  '/circuit/s/$hash': typeof CircuitSHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/circuit': typeof CircuitRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/aes-in-hardware': typeof BlogAesInHardwareRoute
  '/blog/breakout-in-hardware': typeof BlogBreakoutInHardwareRoute
  '/blog/building-a-cpu': typeof BlogBuildingACpuRoute
  '/blog/chacha20-in-hardware': typeof BlogChacha20InHardwareRoute
  '/blog/computing-trig-in-hardware': typeof BlogComputingTrigInHardwareRoute
  '/blog/crc32-in-hardware': typeof BlogCrc32InHardwareRoute
  '/blog/how-network-switches-work': typeof BlogHowNetworkSwitchesWorkRoute
  '/blog/how-tpus-work': typeof BlogHowTpusWorkRoute
  '/blog/pong-in-hardware': typeof BlogPongInHardwareRoute
  '/blog/rv32i-cpu': typeof BlogRv32iCpuRoute
  '/blog/snake-in-hardware': typeof BlogSnakeInHardwareRoute
  '/blog/sorting-networks': typeof BlogSortingNetworksRoute
  '/circuit_/$encoded': typeof CircuitEncodedRoute
  '/cpu/rv32i': typeof CpuRv32iRoute
  '/docs/$': typeof DocsSplatRoute
  '/learn/abstraction': typeof LearnAbstractionRoute
  '/learn/adders': typeof LearnAddersRoute
  '/learn/registers': typeof LearnRegistersRoute
  '/blog/': typeof BlogIndexRoute
  '/cpu/': typeof CpuIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/circuit_/s/$hash': typeof CircuitSHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/circuit'
    | '/privacy'
    | '/terms'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/crc32-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/blog/sorting-networks'
    | '/circuit/$encoded'
    | '/cpu/rv32i'
    | '/docs/$'
    | '/learn/abstraction'
    | '/learn/adders'
    | '/learn/registers'
    | '/blog/'
    | '/cpu/'
    | '/learn/'
    | '/circuit/s/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circuit'
    | '/privacy'
    | '/terms'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/crc32-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/blog/sorting-networks'
    | '/circuit/$encoded'
    | '/cpu/rv32i'
    | '/docs/$'
    | '/learn/abstraction'
    | '/learn/adders'
    | '/learn/registers'
    | '/blog'
    | '/cpu'
    | '/learn'
    | '/circuit/s/$hash'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/circuit'
    | '/privacy'
    | '/terms'
    | '/api/search'
    | '/blog/aes-in-hardware'
    | '/blog/breakout-in-hardware'
    | '/blog/building-a-cpu'
    | '/blog/chacha20-in-hardware'
    | '/blog/computing-trig-in-hardware'
    | '/blog/crc32-in-hardware'
    | '/blog/how-network-switches-work'
    | '/blog/how-tpus-work'
    | '/blog/pong-in-hardware'
    | '/blog/rv32i-cpu'
    | '/blog/snake-in-hardware'
    | '/blog/sorting-networks'
    | '/circuit_/$encoded'
    | '/cpu/rv32i'
    | '/docs/$'
    | '/learn/abstraction'
    | '/learn/adders'
    | '/learn/registers'
    | '/blog/'
    | '/cpu/'
    | '/learn/'
    | '/circuit_/s/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CircuitRoute: typeof CircuitRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CircuitEncodedRoute: typeof CircuitEncodedRoute
  CpuRv32iRoute: typeof CpuRv32iRoute
  DocsSplatRoute: typeof DocsSplatRoute
  LearnAbstractionRoute: typeof LearnAbstractionRoute
  LearnAddersRoute: typeof LearnAddersRoute
  LearnRegistersRoute: typeof LearnRegistersRoute
  CpuIndexRoute: typeof CpuIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  CircuitSHashRoute: typeof CircuitSHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit': {
      id: '/circuit'
      path: '/circuit'
      fullPath: '/circuit'
      preLoaderRoute: typeof CircuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpu/': {
      id: '/cpu/'
      path: '/cpu'
      fullPath: '/cpu/'
      preLoaderRoute: typeof CpuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/learn/registers': {
      id: '/learn/registers'
      path: '/learn/registers'
      fullPath: '/learn/registers'
      preLoaderRoute: typeof LearnRegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/adders': {
      id: '/learn/adders'
      path: '/learn/adders'
      fullPath: '/learn/adders'
      preLoaderRoute: typeof LearnAddersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/abstraction': {
      id: '/learn/abstraction'
      path: '/learn/abstraction'
      fullPath: '/learn/abstraction'
      preLoaderRoute: typeof LearnAbstractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cpu/rv32i': {
      id: '/cpu/rv32i'
      path: '/cpu/rv32i'
      fullPath: '/cpu/rv32i'
      preLoaderRoute: typeof CpuRv32iRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit_/$encoded': {
      id: '/circuit_/$encoded'
      path: '/circuit/$encoded'
      fullPath: '/circuit/$encoded'
      preLoaderRoute: typeof CircuitEncodedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sorting-networks': {
      id: '/blog/sorting-networks'
      path: '/sorting-networks'
      fullPath: '/blog/sorting-networks'
      preLoaderRoute: typeof BlogSortingNetworksRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/snake-in-hardware': {
      id: '/blog/snake-in-hardware'
      path: '/snake-in-hardware'
      fullPath: '/blog/snake-in-hardware'
      preLoaderRoute: typeof BlogSnakeInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/rv32i-cpu': {
      id: '/blog/rv32i-cpu'
      path: '/rv32i-cpu'
      fullPath: '/blog/rv32i-cpu'
      preLoaderRoute: typeof BlogRv32iCpuRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/pong-in-hardware': {
      id: '/blog/pong-in-hardware'
      path: '/pong-in-hardware'
      fullPath: '/blog/pong-in-hardware'
      preLoaderRoute: typeof BlogPongInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-tpus-work': {
      id: '/blog/how-tpus-work'
      path: '/how-tpus-work'
      fullPath: '/blog/how-tpus-work'
      preLoaderRoute: typeof BlogHowTpusWorkRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/how-network-switches-work': {
      id: '/blog/how-network-switches-work'
      path: '/how-network-switches-work'
      fullPath: '/blog/how-network-switches-work'
      preLoaderRoute: typeof BlogHowNetworkSwitchesWorkRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/crc32-in-hardware': {
      id: '/blog/crc32-in-hardware'
      path: '/crc32-in-hardware'
      fullPath: '/blog/crc32-in-hardware'
      preLoaderRoute: typeof BlogCrc32InHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/computing-trig-in-hardware': {
      id: '/blog/computing-trig-in-hardware'
      path: '/computing-trig-in-hardware'
      fullPath: '/blog/computing-trig-in-hardware'
      preLoaderRoute: typeof BlogComputingTrigInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/chacha20-in-hardware': {
      id: '/blog/chacha20-in-hardware'
      path: '/chacha20-in-hardware'
      fullPath: '/blog/chacha20-in-hardware'
      preLoaderRoute: typeof BlogChacha20InHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/building-a-cpu': {
      id: '/blog/building-a-cpu'
      path: '/building-a-cpu'
      fullPath: '/blog/building-a-cpu'
      preLoaderRoute: typeof BlogBuildingACpuRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/breakout-in-hardware': {
      id: '/blog/breakout-in-hardware'
      path: '/breakout-in-hardware'
      fullPath: '/blog/breakout-in-hardware'
      preLoaderRoute: typeof BlogBreakoutInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/aes-in-hardware': {
      id: '/blog/aes-in-hardware'
      path: '/aes-in-hardware'
      fullPath: '/blog/aes-in-hardware'
      preLoaderRoute: typeof BlogAesInHardwareRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circuit_/s/$hash': {
      id: '/circuit_/s/$hash'
      path: '/circuit/s/$hash'
      fullPath: '/circuit/s/$hash'
      preLoaderRoute: typeof CircuitSHashRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogAesInHardwareRoute: typeof BlogAesInHardwareRoute
  BlogBreakoutInHardwareRoute: typeof BlogBreakoutInHardwareRoute
  BlogBuildingACpuRoute: typeof BlogBuildingACpuRoute
  BlogChacha20InHardwareRoute: typeof BlogChacha20InHardwareRoute
  BlogComputingTrigInHardwareRoute: typeof BlogComputingTrigInHardwareRoute
  BlogCrc32InHardwareRoute: typeof BlogCrc32InHardwareRoute
  BlogHowNetworkSwitchesWorkRoute: typeof BlogHowNetworkSwitchesWorkRoute
  BlogHowTpusWorkRoute: typeof BlogHowTpusWorkRoute
  BlogPongInHardwareRoute: typeof BlogPongInHardwareRoute
  BlogRv32iCpuRoute: typeof BlogRv32iCpuRoute
  BlogSnakeInHardwareRoute: typeof BlogSnakeInHardwareRoute
  BlogSortingNetworksRoute: typeof BlogSortingNetworksRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogAesInHardwareRoute: BlogAesInHardwareRoute,
  BlogBreakoutInHardwareRoute: BlogBreakoutInHardwareRoute,
  BlogBuildingACpuRoute: BlogBuildingACpuRoute,
  BlogChacha20InHardwareRoute: BlogChacha20InHardwareRoute,
  BlogComputingTrigInHardwareRoute: BlogComputingTrigInHardwareRoute,
  BlogCrc32InHardwareRoute: BlogCrc32InHardwareRoute,
  BlogHowNetworkSwitchesWorkRoute: BlogHowNetworkSwitchesWorkRoute,
  BlogHowTpusWorkRoute: BlogHowTpusWorkRoute,
  BlogPongInHardwareRoute: BlogPongInHardwareRoute,
  BlogRv32iCpuRoute: BlogRv32iCpuRoute,
  BlogSnakeInHardwareRoute: BlogSnakeInHardwareRoute,
  BlogSortingNetworksRoute: BlogSortingNetworksRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CircuitRoute: CircuitRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiSearchRoute: ApiSearchRoute,
  CircuitEncodedRoute: CircuitEncodedRoute,
  CpuRv32iRoute: CpuRv32iRoute,
  DocsSplatRoute: DocsSplatRoute,
  LearnAbstractionRoute: LearnAbstractionRoute,
  LearnAddersRoute: LearnAddersRoute,
  LearnRegistersRoute: LearnRegistersRoute,
  CpuIndexRoute: CpuIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  CircuitSHashRoute: CircuitSHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
