// Auto-generated from DSL

const ALU = component('ALU', {
  in: { a: bus(8), b: bus(8), op: bus(3), carry_in: bit },
  out: { result: bus(8), carry_out: bit, zero: bit, negative: bit },
  nodes: { adder: Adder, subtractor: Subtractor, and_op: BusAnd, or_op: BusOr, xor_op: BusXor, op_0: Constant, op_1: Constant, op_2: Constant, op_3: Constant, op_4: Constant, is_add: Comparator, is_sub: Comparator, is_and: Comparator, is_or: Comparator, is_xor: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux_carry: Mux, zero_cmp: Comparator, threshold: Constant, neg_cmp: Comparator },
  nodeArgs: { op_0: { value: 0 }, op_1: { value: 1 }, op_2: { value: 2 }, op_3: { value: 3 }, op_4: { value: 4 }, threshold: { value: 127 } },
  connect: ({ in: inp, out, adder, subtractor, and_op, or_op, xor_op, op_0, op_1, op_2, op_3, op_4, is_add, is_sub, is_and, is_or, is_xor, mux1, mux2, mux3, mux4, mux_carry, zero_cmp, threshold, neg_cmp }) => [
    inp.a.to(adder.a, subtractor.a, and_op.a, or_op.a, xor_op.a),
    inp.b.to(adder.b, subtractor.b, and_op.b, or_op.b, xor_op.b),
    inp.carry_in.to(adder.carry_in, subtractor.borrow_in),
    inp.op.to(is_add.a, is_sub.a, is_and.a, is_or.a, is_xor.a),
    op_0.out.to(is_add.b, zero_cmp.b),
    op_1.out.to(is_sub.b),
    op_2.out.to(is_and.b),
    op_3.out.to(is_or.b),
    op_4.out.to(is_xor.b),
    is_sub.eq.to(mux1.sel, mux_carry.sel),
    adder.sum.to(mux1.in0),
    subtractor.difference.to(mux1.in1),
    is_and.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    and_op.out.to(mux2.in1),
    is_or.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    or_op.out.to(mux3.in1),
    is_xor.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    xor_op.out.to(mux4.in1),
    mux4.out.to(out.result),
    adder.carry_out.to(mux_carry.in0),
    subtractor.borrow_out.to(mux_carry.in1),
    mux_carry.out.to(out.carry_out),
    out.result.to(zero_cmp.a, neg_cmp.a),
    zero_cmp.eq.to(out.zero),
    threshold.out.to(neg_cmp.b),
    neg_cmp.gt.to(out.negative),
  ],
})

const RegisterFile = component('RegisterFile', {
  in: { write_sel: bus(2), write_data: bus(8), write_enable: bit, read_sel: bus(2) },
  out: { read_data: bus(8) },
  nodes: { regA: Register, regX: Register, regY: Register, sel_0: Constant, sel_1: Constant, sel_2: Constant, is_sel_A: Comparator, is_sel_X: Comparator, is_sel_Y: Comparator, write_A: And, write_X: And, write_Y: And, is_read_X: Comparator, is_read_Y: Comparator, read_mux1: Mux, read_mux2: Mux },
  nodeArgs: { sel_0: { value: 0 }, sel_1: { value: 1 }, sel_2: { value: 2 } },
  connect: ({ in: inp, out, regA, regX, regY, sel_0, sel_1, sel_2, is_sel_A, is_sel_X, is_sel_Y, write_A, write_X, write_Y, is_read_X, is_read_Y, read_mux1, read_mux2 }) => [
    inp.write_data.to(regA.data, regX.data, regY.data),
    inp.write_sel.to(is_sel_A.a, is_sel_X.a, is_sel_Y.a),
    sel_0.out.to(is_sel_A.b),
    sel_1.out.to(is_sel_X.b, is_read_X.b),
    sel_2.out.to(is_sel_Y.b, is_read_Y.b),
    is_sel_A.eq.to(write_A.a),
    inp.write_enable.to(write_A.b, write_X.b, write_Y.b),
    write_A.out.to(regA.we),
    is_sel_X.eq.to(write_X.a),
    write_X.out.to(regX.we),
    is_sel_Y.eq.to(write_Y.a),
    write_Y.out.to(regY.we),
    inp.read_sel.to(is_read_X.a, is_read_Y.a),
    is_read_X.eq.to(read_mux1.sel),
    regA.q.to(read_mux1.in0),
    regX.q.to(read_mux1.in1),
    is_read_Y.eq.to(read_mux2.sel),
    read_mux1.out.to(read_mux2.in0),
    regY.q.to(read_mux2.in1),
    read_mux2.out.to(out.read_data),
  ],
})

const Stage1Integration = component('Stage1Integration', {
  out: { cycle_count: bus(8), reg_a_value: bus(8), reg_x_value: bus(8), alu_result: bus(8) },
  nodes: { counter: Register, always_enable: Constant, inc: Incrementer, cycle_0: Constant, cycle_1: Constant, cycle_2: Constant, cycle_3: Constant, is_cycle_0: Comparator, is_cycle_1: Comparator, is_cycle_2: Comparator, is_cycle_3: Comparator, regfile: RegisterFile, alu: ALU, val_66: Constant, val_8: Constant, val_10: Constant, zero: Constant, sel_A: Constant, sel_X: Constant, op_add: Constant, alu_read_sel: Mux, alu_read_sel2: Mux, alu_b_mux1: Mux, alu_b_mux2: Mux, alu_b_mux3: Mux, write_sel_mux1: Mux, write_sel_mux2: Mux, reader_A: RegisterFile, reader_X: RegisterFile },
  nodeArgs: { always_enable: { value: 1 }, cycle_0: { value: 0 }, cycle_1: { value: 1 }, cycle_2: { value: 2 }, cycle_3: { value: 3 }, val_66: { value: 66 }, val_8: { value: 8 }, val_10: { value: 10 }, zero: { value: 0 }, sel_A: { value: 0 }, sel_X: { value: 1 }, op_add: { value: 0 } },
  connect: ({ in: inp, out, counter, always_enable, inc, cycle_0, cycle_1, cycle_2, cycle_3, is_cycle_0, is_cycle_1, is_cycle_2, is_cycle_3, regfile, alu, val_66, val_8, val_10, zero, sel_A, sel_X, op_add, alu_read_sel, alu_read_sel2, alu_b_mux1, alu_b_mux2, alu_b_mux3, write_sel_mux1, write_sel_mux2, reader_A, reader_X }) => [
    always_enable.out.to(counter.we, regfile.write_enable, reader_A.write_enable, reader_X.write_enable),
    counter.q.to(inc.in, out.cycle_count, is_cycle_0.a, is_cycle_1.a, is_cycle_2.a, is_cycle_3.a),
    inc.out.to(counter.data),
    cycle_0.out.to(is_cycle_0.b),
    cycle_1.out.to(is_cycle_1.b),
    cycle_2.out.to(is_cycle_2.b),
    cycle_3.out.to(is_cycle_3.b),
    is_cycle_2.eq.to(alu_read_sel.sel, alu_b_mux2.sel, write_sel_mux1.sel),
    sel_A.out.to(alu_read_sel.in0, write_sel_mux1.in0, reader_A.read_sel),
    sel_X.out.to(alu_read_sel.in1, alu_read_sel2.in1, write_sel_mux1.in1, write_sel_mux2.in1, reader_X.read_sel),
    is_cycle_3.eq.to(alu_read_sel2.sel, alu_b_mux3.sel, write_sel_mux2.sel),
    alu_read_sel.out.to(alu_read_sel2.in0),
    alu_read_sel2.out.to(regfile.read_sel),
    regfile.read_data.to(alu.a),
    is_cycle_0.eq.to(alu_b_mux1.sel),
    val_8.out.to(alu_b_mux1.in0),
    val_66.out.to(alu_b_mux1.in1),
    alu_b_mux1.out.to(alu_b_mux2.in0),
    zero.out.to(alu_b_mux2.in1, alu.carry_in),
    alu_b_mux2.out.to(alu_b_mux3.in0),
    val_10.out.to(alu_b_mux3.in1),
    alu_b_mux3.out.to(alu.b),
    op_add.out.to(alu.op),
    alu.result.to(out.alu_result, regfile.write_data, reader_A.write_data, reader_X.write_data),
    write_sel_mux1.out.to(write_sel_mux2.in0),
    write_sel_mux2.out.to(regfile.write_sel, reader_A.write_sel, reader_X.write_sel),
    reader_A.read_data.to(out.reg_a_value),
    reader_X.read_data.to(out.reg_x_value),
  ],
})

const Stage1Demo = component('Stage1Demo', {
  nodes: { cpu: Stage1Integration, display_cycle: HexDisplay, display_a: HexDisplay, display_x: HexDisplay, display_alu: HexDisplay },
  connect: ({ in: inp, out, cpu, display_cycle, display_a, display_x, display_alu }) => [
    cpu.cycle_count.to(display_cycle.in),
    cpu.reg_a_value.to(display_a.in),
    cpu.reg_x_value.to(display_x.in),
    cpu.alu_result.to(display_alu.in),
  ],
})
