// Auto-generated from DSL

const InstructionDecoder = component('InstructionDecoder', {
  in: { opcode: bus(8) },
  out: { is_LDA_imm: bit, is_ADC_imm: bit, is_STA_abs: bit, is_JMP_abs: bit, is_BRK: bit, addr_mode: bus(2), cycles: bus(3) },
  nodes: { val_LDA: Constant, val_ADC: Constant, val_STA: Constant, val_JMP: Constant, val_BRK: Constant, cmp_LDA: Comparator, cmp_ADC: Comparator, cmp_STA: Comparator, cmp_JMP: Comparator, cmp_BRK: Comparator, mode_implied: Constant, mode_immediate: Constant, mode_absolute: Constant, is_immediate: Or, is_absolute: Or, mode_mux1: Mux, mode_mux2: Mux, cycles_1: Constant, cycles_2: Constant, cycles_3: Constant, cycles_4: Constant, cycle_mux1: Mux, cycle_mux2: Mux, cycle_mux3: Mux },
  nodeArgs: { val_LDA: { value: 169 }, val_ADC: { value: 105 }, val_STA: { value: 141 }, val_JMP: { value: 76 }, val_BRK: { value: 0 }, mode_implied: { value: 0 }, mode_immediate: { value: 1 }, mode_absolute: { value: 2 }, cycles_1: { value: 1 }, cycles_2: { value: 2 }, cycles_3: { value: 3 }, cycles_4: { value: 4 } },
  connect: ({ in: inp, out, val_LDA, val_ADC, val_STA, val_JMP, val_BRK, cmp_LDA, cmp_ADC, cmp_STA, cmp_JMP, cmp_BRK, mode_implied, mode_immediate, mode_absolute, is_immediate, is_absolute, mode_mux1, mode_mux2, cycles_1, cycles_2, cycles_3, cycles_4, cycle_mux1, cycle_mux2, cycle_mux3 }) => [
    inp.opcode.to(cmp_LDA.a, cmp_ADC.a, cmp_STA.a, cmp_JMP.a, cmp_BRK.a),
    val_LDA.out.to(cmp_LDA.b),
    cmp_LDA.eq.to(out.is_LDA_imm),
    val_ADC.out.to(cmp_ADC.b),
    cmp_ADC.eq.to(out.is_ADC_imm),
    val_STA.out.to(cmp_STA.b),
    cmp_STA.eq.to(out.is_STA_abs),
    val_JMP.out.to(cmp_JMP.b),
    cmp_JMP.eq.to(out.is_JMP_abs),
    val_BRK.out.to(cmp_BRK.b),
    cmp_BRK.eq.to(out.is_BRK),
    out.is_LDA_imm.to(is_immediate.a),
    out.is_ADC_imm.to(is_immediate.b),
    out.is_STA_abs.to(is_absolute.a, cycle_mux3.sel),
    out.is_JMP_abs.to(is_absolute.b, cycle_mux2.sel),
    is_absolute.out.to(mode_mux1.sel),
    mode_implied.out.to(mode_mux1.in0),
    mode_absolute.out.to(mode_mux1.in1),
    is_immediate.out.to(mode_mux2.sel, cycle_mux1.sel),
    mode_mux1.out.to(mode_mux2.in0),
    mode_immediate.out.to(mode_mux2.in1),
    mode_mux2.out.to(out.addr_mode),
    cycles_1.out.to(cycle_mux1.in0),
    cycles_2.out.to(cycle_mux1.in1),
    cycle_mux1.out.to(cycle_mux2.in0),
    cycles_3.out.to(cycle_mux2.in1),
    cycle_mux2.out.to(cycle_mux3.in0),
    cycles_4.out.to(cycle_mux3.in1),
    cycle_mux3.out.to(out.cycles),
  ],
})

const InstructionDecoderTest = component('InstructionDecoderTest', {
  out: { is_LDA: bit, is_ADC: bit, is_STA: bit, is_JMP: bit, is_BRK: bit, mode: bus(2), cycles: bus(3) },
  nodes: { decoder: InstructionDecoder, opcode_input: Input, d_mode: HexDisplay, d_cycles: HexDisplay },
  connect: ({ in: inp, out, decoder, opcode_input, d_mode, d_cycles }) => [
    opcode_input.out.to(decoder.opcode),
    decoder.is_LDA_imm.to(out.is_LDA),
    decoder.is_ADC_imm.to(out.is_ADC),
    decoder.is_STA_abs.to(out.is_STA),
    decoder.is_JMP_abs.to(out.is_JMP),
    decoder.is_BRK.to(out.is_BRK),
    decoder.addr_mode.to(out.mode),
    decoder.cycles.to(out.cycles),
    out.mode.to(d_mode.in),
    out.cycles.to(d_cycles.in),
  ],
})
