// Auto-generated from DSL

const ALU = circuit('ALU', {
  in: { a: bus(8), b: bus(8), op: bus(3), carry_in: bit },
  out: { result: bus(8), carry_out: bit, zero: bit, negative: bit },
  nodes: { adder: Adder, subtractor: Subtractor, and_op: BusAnd, or_op: BusOr, xor_op: BusXor, op_0: Constant, op_1: Constant, op_2: Constant, op_3: Constant, op_4: Constant, is_add: Comparator, is_sub: Comparator, is_and: Comparator, is_or: Comparator, is_xor: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux_carry: Mux, zero_cmp: Comparator, threshold: Constant, neg_cmp: Comparator },
  nodeArgs: { op_0: { value: 0 }, op_1: { value: 1 }, op_2: { value: 2 }, op_3: { value: 3 }, op_4: { value: 4 }, threshold: { value: 127 } },
  connect: ({ in: inp, out, adder, subtractor, and_op, or_op, xor_op, op_0, op_1, op_2, op_3, op_4, is_add, is_sub, is_and, is_or, is_xor, mux1, mux2, mux3, mux4, mux_carry, zero_cmp, threshold, neg_cmp }) => [
    inp.a.to(adder.a, subtractor.a, and_op.a, or_op.a, xor_op.a),
    inp.b.to(adder.b, subtractor.b, and_op.b, or_op.b, xor_op.b),
    inp.carry_in.to(adder.carry_in, subtractor.borrow_in),
    inp.op.to(is_add.a, is_sub.a, is_and.a, is_or.a, is_xor.a),
    op_0.out.to(is_add.b, zero_cmp.b),
    op_1.out.to(is_sub.b),
    op_2.out.to(is_and.b),
    op_3.out.to(is_or.b),
    op_4.out.to(is_xor.b),
    is_sub.eq.to(mux1.sel, mux_carry.sel),
    adder.sum.to(mux1.in0),
    subtractor.difference.to(mux1.in1),
    is_and.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    and_op.out.to(mux2.in1),
    is_or.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    or_op.out.to(mux3.in1),
    is_xor.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    xor_op.out.to(mux4.in1),
    mux4.out.to(out.result),
    adder.carry_out.to(mux_carry.in0),
    subtractor.borrow_out.to(mux_carry.in1),
    mux_carry.out.to(out.carry_out),
    out.result.to(zero_cmp.a, neg_cmp.a),
    zero_cmp.eq.to(out.zero),
    threshold.out.to(neg_cmp.b),
    neg_cmp.gt.to(out.negative),
  ],
})

const ProgramCounter = circuit('ProgramCounter', {
  in: { load: bit, load_addr_low: bus(8), load_addr_high: bus(8), increment: bit },
  out: { pc_low: bus(8), pc_high: bus(8) },
  nodes: { pcl_reg: Register, pch_reg: Register, inc_low: Incrementer, max_byte: Constant, will_overflow: Comparator, inc_high: Incrementer, high_inc_mux: Mux, low_load_or_inc: Mux, low_final: Mux, high_load_or_inc: Mux, high_final: Mux, always_on: Constant },
  nodeArgs: { max_byte: { value: 255 }, always_on: { value: 1 } },
  connect: ({ in: inp, out, pcl_reg, pch_reg, inc_low, max_byte, will_overflow, inc_high, high_inc_mux, low_load_or_inc, low_final, high_load_or_inc, high_final, always_on }) => [
    pcl_reg.q.to(inc_low.in, will_overflow.a, low_load_or_inc.in0, out.pc_low),
    max_byte.out.to(will_overflow.b),
    pch_reg.q.to(inc_high.in, high_inc_mux.in0, high_load_or_inc.in0, out.pc_high),
    will_overflow.eq.to(high_inc_mux.sel),
    inc_high.out.to(high_inc_mux.in1),
    inp.increment.to(low_load_or_inc.sel, high_load_or_inc.sel),
    inc_low.out.to(low_load_or_inc.in1),
    inp.load.to(low_final.sel, high_final.sel),
    low_load_or_inc.out.to(low_final.in0),
    inp.load_addr_low.to(low_final.in1),
    low_final.out.to(pcl_reg.data),
    high_inc_mux.out.to(high_load_or_inc.in1),
    high_load_or_inc.out.to(high_final.in0),
    inp.load_addr_high.to(high_final.in1),
    high_final.out.to(pch_reg.data),
    always_on.out.to(pcl_reg.we, pch_reg.we),
  ],
})

const InstructionDecoder = circuit('InstructionDecoder', {
  in: { opcode: bus(8) },
  out: { is_LDA_imm: bit, is_ADC_imm: bit, is_STA_abs: bit, is_JMP_abs: bit, is_BRK: bit, addr_mode: bus(2), cycles: bus(3) },
  nodes: { val_LDA: Constant, val_ADC: Constant, val_STA: Constant, val_JMP: Constant, val_BRK: Constant, cmp_LDA: Comparator, cmp_ADC: Comparator, cmp_STA: Comparator, cmp_JMP: Comparator, cmp_BRK: Comparator, mode_implied: Constant, mode_immediate: Constant, mode_absolute: Constant, is_immediate: Or, is_absolute: Or, mode_mux1: Mux, mode_mux2: Mux, cycles_1: Constant, cycles_2: Constant, cycles_3: Constant, cycles_4: Constant, cycle_mux1: Mux, cycle_mux2: Mux, cycle_mux3: Mux },
  nodeArgs: { val_LDA: { value: 169 }, val_ADC: { value: 105 }, val_STA: { value: 141 }, val_JMP: { value: 76 }, val_BRK: { value: 0 }, mode_implied: { value: 0 }, mode_immediate: { value: 1 }, mode_absolute: { value: 2 }, cycles_1: { value: 1 }, cycles_2: { value: 2 }, cycles_3: { value: 3 }, cycles_4: { value: 4 } },
  connect: ({ in: inp, out, val_LDA, val_ADC, val_STA, val_JMP, val_BRK, cmp_LDA, cmp_ADC, cmp_STA, cmp_JMP, cmp_BRK, mode_implied, mode_immediate, mode_absolute, is_immediate, is_absolute, mode_mux1, mode_mux2, cycles_1, cycles_2, cycles_3, cycles_4, cycle_mux1, cycle_mux2, cycle_mux3 }) => [
    inp.opcode.to(cmp_LDA.a, cmp_ADC.a, cmp_STA.a, cmp_JMP.a, cmp_BRK.a),
    val_LDA.out.to(cmp_LDA.b),
    cmp_LDA.eq.to(out.is_LDA_imm),
    val_ADC.out.to(cmp_ADC.b),
    cmp_ADC.eq.to(out.is_ADC_imm),
    val_STA.out.to(cmp_STA.b),
    cmp_STA.eq.to(out.is_STA_abs),
    val_JMP.out.to(cmp_JMP.b),
    cmp_JMP.eq.to(out.is_JMP_abs),
    val_BRK.out.to(cmp_BRK.b),
    cmp_BRK.eq.to(out.is_BRK),
    out.is_LDA_imm.to(is_immediate.a),
    out.is_ADC_imm.to(is_immediate.b),
    out.is_STA_abs.to(is_absolute.a, cycle_mux3.sel),
    out.is_JMP_abs.to(is_absolute.b, cycle_mux2.sel),
    is_absolute.out.to(mode_mux1.sel),
    mode_implied.out.to(mode_mux1.in0),
    mode_absolute.out.to(mode_mux1.in1),
    is_immediate.out.to(mode_mux2.sel, cycle_mux1.sel),
    mode_mux1.out.to(mode_mux2.in0),
    mode_immediate.out.to(mode_mux2.in1),
    mode_mux2.out.to(out.addr_mode),
    cycles_1.out.to(cycle_mux1.in0),
    cycles_2.out.to(cycle_mux1.in1),
    cycle_mux1.out.to(cycle_mux2.in0),
    cycles_3.out.to(cycle_mux2.in1),
    cycle_mux2.out.to(cycle_mux3.in0),
    cycles_4.out.to(cycle_mux3.in1),
    cycle_mux3.out.to(out.cycles),
  ],
})

const CPUControl = circuit('CPUControl', {
  in: { reset: bit, instr_cycles: bus(3), is_BRK: bit },
  out: { current_state: bus(3), cycle_num: bus(3), pc_increment: bit, mem_read: bit, mem_write: bit, alu_enable: bit, reg_write: bit, halted: bit },
  nodes: { state_reg: Register, cycle_reg: Register, halt_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, inc_cycle: Incrementer, cycle_done: Comparator, cycle_reset_or_inc: Mux, always_on: Constant, zero: Constant, exec_done: And, next_if_fetch: Mux, next_if_decode: Mux, next_if_execute: Mux, handle_reset: Mux, set_halt: Or, halt_value: Mux, mem_read_sig: Or },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, always_on: { value: 1 }, zero: { value: 0 } },
  connect: ({ in: inp, out, state_reg, cycle_reg, halt_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, inc_cycle, cycle_done, cycle_reset_or_inc, always_on, zero, exec_done, next_if_fetch, next_if_decode, next_if_execute, handle_reset, set_halt, halt_value, mem_read_sig }) => [
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_if_fetch.in0, out.current_state),
    STATE_FETCH.out.to(is_fetch.b, cycle_reset_or_inc.in1, next_if_execute.in1, handle_reset.in1),
    STATE_DECODE.out.to(is_decode.b, next_if_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_if_decode.in1),
    cycle_reg.q.to(inc_cycle.in, cycle_done.a, out.cycle_num),
    inp.instr_cycles.to(cycle_done.b),
    is_fetch.eq.to(cycle_reset_or_inc.sel, next_if_fetch.sel, out.pc_increment, mem_read_sig.a),
    inc_cycle.out.to(cycle_reset_or_inc.in0),
    cycle_reset_or_inc.out.to(cycle_reg.data),
    always_on.out.to(cycle_reg.we, state_reg.we, halt_reg.we),
    is_execute.eq.to(exec_done.a, out.mem_write, out.alu_enable, out.reg_write),
    cycle_done.eq.to(exec_done.b),
    is_decode.eq.to(next_if_decode.sel, mem_read_sig.b),
    next_if_fetch.out.to(next_if_decode.in0),
    exec_done.out.to(next_if_execute.sel),
    next_if_decode.out.to(next_if_execute.in0),
    inp.reset.to(handle_reset.sel, halt_value.sel),
    next_if_execute.out.to(handle_reset.in0),
    handle_reset.out.to(state_reg.data),
    halt_reg.q.to(set_halt.a, out.halted),
    inp.is_BRK.to(set_halt.b),
    set_halt.out.to(halt_value.in0),
    zero.out.to(halt_value.in1),
    halt_value.out.to(halt_reg.data),
    mem_read_sig.out.to(out.mem_read),
  ],
})

const SimpleROM = circuit('SimpleROM', {
  in: { addr: bus(8) },
  out: { data: bus(8) },
  nodes: { zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux },
  nodeArgs: { zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, byte_0: { value: 169 }, byte_1: { value: 66 }, byte_2: { value: 105 }, byte_3: { value: 8 }, byte_4: { value: 141 }, byte_5: { value: 254 }, byte_6: { value: 0 }, byte_7: { value: 0 } },
  connect: ({ in: inp, out, zero, one, two, three, four, five, six, seven, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, mux1, mux2, mux3, mux4, mux5, mux6, mux7 }) => [
    inp.addr.to(at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a),
    zero.out.to(at_0.b),
    one.out.to(at_1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    mux7.out.to(out.data),
  ],
})

const CompleteCPU = circuit('CompleteCPU', {
  in: { reset: bit },
  out: { pc_low: bus(8), pc_high: bus(8), instruction: bus(8), current_state: bus(3), reg_a: bus(8), halted: bit },
  nodes: { pc_reg: ProgramCounter, decoder: InstructionDecoder, control: CPUControl, alu: ALU, rom: SimpleROM, regA: Register, zero: Constant },
  nodeArgs: { zero: { value: 0 } },
  connect: ({ in: inp, out, pc_reg, decoder, control, alu, rom, regA, zero }) => [
    pc_reg.pc_low.to(rom.addr, out.pc_low),
    rom.data.to(decoder.opcode, out.instruction, alu.b),
    decoder.cycles.to(control.instr_cycles),
    decoder.is_BRK.to(control.is_BRK),
    inp.reset.to(control.reset),
    control.pc_increment.to(pc_reg.increment),
    zero.out.to(pc_reg.load, pc_reg.load_addr_low, pc_reg.load_addr_high, alu.op, alu.carry_in),
    regA.q.to(alu.a, out.reg_a),
    alu.result.to(regA.data),
    control.reg_write.to(regA.we),
    pc_reg.pc_high.to(out.pc_high),
    control.current_state.to(out.current_state),
    control.halted.to(out.halted),
  ],
})

const FullCPUTest = circuit('FullCPUTest', {
  nodes: { cpu: CompleteCPU, reset_input: Input, d_pc: HexDisplay, d_instruction: HexDisplay, d_state: HexDisplay, d_reg_a: HexDisplay, d_halted: Led },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_instruction, d_state, d_reg_a, d_halted }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc_low.to(d_pc.in),
    cpu.instruction.to(d_instruction.in),
    cpu.current_state.to(d_state.in),
    cpu.reg_a.to(d_reg_a.in),
    cpu.halted.to(d_halted.in),
  ],
})
