// Auto-generated from DSL

const InstructionRegister = circuit('InstructionRegister', {
  in: { opcode: bus(8), load: bit },
  out: { current_opcode: bus(8) },
  nodes: { ir: Register },
  connect: ({ in: inp, out, ir }) => [
    inp.opcode.to(ir.data),
    inp.load.to(ir.we),
    ir.q.to(out.current_opcode),
  ],
})

const EnhancedControl = circuit('EnhancedControl', {
  in: { reset: bit, current_opcode: bus(8) },
  out: { current_state: bus(3), exec_subcycle: bus(3), pc_increment: bit, ir_load: bit, operand_load: bit, reg_write: bit, is_lda: bit, is_adc: bit },
  nodes: { state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDA_IMM: Constant, ADC_IMM: Constant, cmp_lda: Comparator, cmp_adc: Comparator, zero: Constant, one: Constant, two: Constant, inc_subcycle: Incrementer, subcycle_increment: Mux, always_on: Constant, is_subcycle_0: Comparator, is_subcycle_1: Comparator, next_from_fetch: Mux, next_from_decode: Mux, exec_done: And, next_from_execute: Mux, next_state: Mux, exec_subcycle_0: And, pc_inc_signal: Or, exec_subcycle_1: And },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDA_IMM: { value: 169 }, ADC_IMM: { value: 105 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, always_on: { value: 1 } },
  connect: ({ in: inp, out, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDA_IMM, ADC_IMM, cmp_lda, cmp_adc, zero, one, two, inc_subcycle, subcycle_increment, always_on, is_subcycle_0, is_subcycle_1, next_from_fetch, next_from_decode, exec_done, next_from_execute, next_state, exec_subcycle_0, pc_inc_signal, exec_subcycle_1 }) => [
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0, out.current_state),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    inp.current_opcode.to(cmp_lda.a, cmp_adc.a),
    LDA_IMM.out.to(cmp_lda.b),
    cmp_lda.eq.to(out.is_lda),
    ADC_IMM.out.to(cmp_adc.b),
    cmp_adc.eq.to(out.is_adc),
    subcycle_reg.q.to(inc_subcycle.in, out.exec_subcycle, is_subcycle_0.a, is_subcycle_1.a),
    is_execute.eq.to(subcycle_increment.sel, exec_done.a, exec_subcycle_0.a, exec_subcycle_1.a),
    zero.out.to(subcycle_increment.in0, is_subcycle_0.b),
    inc_subcycle.out.to(subcycle_increment.in1),
    subcycle_increment.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we),
    one.out.to(is_subcycle_1.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_signal.a, out.ir_load),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    is_subcycle_1.eq.to(exec_done.b, exec_subcycle_1.b),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    is_subcycle_0.eq.to(exec_subcycle_0.b),
    exec_subcycle_0.out.to(pc_inc_signal.b, out.operand_load),
    pc_inc_signal.out.to(out.pc_increment),
    exec_subcycle_1.out.to(out.reg_write),
  ],
})

const EnhancedCPU = circuit('EnhancedCPU', {
  in: { reset: bit },
  out: { pc: bus(8), instruction: bus(8), operand: bus(8), current_state: bus(3), subcycle: bus(3), reg_a: bus(8) },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, ir: Register, operand_reg: Register, control: EnhancedControl, pc_next: Mux, reg_a_internal: Register, adder: Adder, result: Mux },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, byte_0: { value: 169 }, byte_1: { value: 66 }, byte_2: { value: 105 }, byte_3: { value: 8 }, byte_4: { value: 0 }, byte_5: { value: 0 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, at_0, at_1, at_2, at_3, at_4, at_5, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, mux1, mux2, mux3, mux4, mux5, ir, operand_reg, control, pc_next, reg_a_internal, adder, result }) => [
    always_on.out.to(pc_reg.we),
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, adder.carry_in),
    one.out.to(at_1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    mux5.out.to(ir.data, operand_reg.data),
    inp.reset.to(control.reset),
    ir.q.to(control.current_opcode, out.instruction),
    control.pc_increment.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    control.ir_load.to(ir.we),
    control.operand_load.to(operand_reg.we),
    control.reg_write.to(reg_a_internal.we),
    reg_a_internal.q.to(adder.a, out.reg_a),
    operand_reg.q.to(adder.b, result.in1, out.operand),
    control.is_lda.to(result.sel),
    adder.sum.to(result.in0),
    result.out.to(reg_a_internal.data),
    control.current_state.to(out.current_state),
    control.exec_subcycle.to(out.subcycle),
  ],
})

const Stage3Test = circuit('Stage3Test', {
  nodes: { cpu: EnhancedCPU, reset_input: Input, d_pc: HexDisplay, d_instruction: HexDisplay, d_operand: HexDisplay, d_state: HexDisplay, d_subcycle: HexDisplay, d_a: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_instruction, d_operand, d_state, d_subcycle, d_a }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.instruction.to(d_instruction.in),
    cpu.operand.to(d_operand.in),
    cpu.current_state.to(d_state.in),
    cpu.subcycle.to(d_subcycle.in),
    cpu.reg_a.to(d_a.in),
  ],
})
