// Auto-generated from DSL

const RegisterFile = component('RegisterFile', {
  in: { write_a: bit, write_x: bit, write_y: bit, data_a: bus(8), data_x: bus(8), data_y: bus(8) },
  out: { reg_a: bus(8), reg_x: bus(8), reg_y: bus(8) },
  nodes: { regA: Register, regX: Register, regY: Register },
  connect: ({ in: inp, out, regA, regX, regY }) => [
    inp.data_a.to(regA.data),
    inp.data_x.to(regX.data),
    inp.data_y.to(regY.data),
    inp.write_a.to(regA.we),
    inp.write_x.to(regX.we),
    inp.write_y.to(regY.we),
    regA.q.to(out.reg_a),
    regX.q.to(out.reg_x),
    regY.q.to(out.reg_y),
  ],
})

const Stage3Control = component('Stage3Control', {
  in: { reset: bit, current_opcode: bus(8) },
  out: { current_state: bus(8), exec_subcycle: bus(8), pc_increment: bit, ir_load: bit, operand_load: bit, write_a: bit, write_x: bit, write_y: bit, is_lda: bit, is_adc: bit, is_tax: bit, is_tay: bit, is_txa: bit, is_tya: bit, is_inx: bit, is_dex: bit, is_iny: bit, is_dey: bit },
  nodes: { state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDA_IMM: Constant, ADC_IMM: Constant, TAX: Constant, TAY: Constant, TXA: Constant, TYA: Constant, INX: Constant, DEX: Constant, INY: Constant, DEY: Constant, cmp_lda: Comparator, cmp_adc: Comparator, cmp_tax: Comparator, cmp_tay: Comparator, cmp_txa: Comparator, cmp_tya: Comparator, cmp_inx: Comparator, cmp_dex: Comparator, cmp_iny: Comparator, cmp_dey: Comparator, needs_operand: Or, zero: Constant, one: Constant, inc_subcycle: Incrementer, subcycle_increment: Mux, always_on: Constant, is_subcycle_0: Comparator, is_subcycle_1: Comparator, next_from_fetch: Mux, next_from_decode: Mux, exec_done_2cycle: And, exec_done_1cycle: And, is_1cycle: Or, is_1cycle_2: Or, is_1cycle_3: Or, is_1cycle_4: Or, is_1cycle_5: Or, is_1cycle_6: Or, is_1cycle_final: Or, exec_done_1cycle_check: And, exec_done: Or, next_from_execute: Mux, next_state: Mux, exec_subcycle_0: And, exec_subcycle_0_needs_operand: And, pc_inc_signal: Or, operand_load_signal: And, exec_subcycle_1: And, write_a_2cycle: And, write_a_txa: And, write_a_tya: And, write_a_transfer: Or, write_a_signal: Or, write_x_tax: And, write_x_inx: And, write_x_dex: And, write_x_temp: Or, write_x_signal: Or, write_y_tay: And, write_y_iny: And, write_y_dey: And, write_y_temp: Or, write_y_signal: Or },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDA_IMM: { value: 169 }, ADC_IMM: { value: 105 }, TAX: { value: 170 }, TAY: { value: 168 }, TXA: { value: 138 }, TYA: { value: 152 }, INX: { value: 232 }, DEX: { value: 202 }, INY: { value: 200 }, DEY: { value: 136 }, zero: { value: 0 }, one: { value: 1 }, always_on: { value: 1 } },
  connect: ({ in: inp, out, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDA_IMM, ADC_IMM, TAX, TAY, TXA, TYA, INX, DEX, INY, DEY, cmp_lda, cmp_adc, cmp_tax, cmp_tay, cmp_txa, cmp_tya, cmp_inx, cmp_dex, cmp_iny, cmp_dey, needs_operand, zero, one, inc_subcycle, subcycle_increment, always_on, is_subcycle_0, is_subcycle_1, next_from_fetch, next_from_decode, exec_done_2cycle, exec_done_1cycle, is_1cycle, is_1cycle_2, is_1cycle_3, is_1cycle_4, is_1cycle_5, is_1cycle_6, is_1cycle_final, exec_done_1cycle_check, exec_done, next_from_execute, next_state, exec_subcycle_0, exec_subcycle_0_needs_operand, pc_inc_signal, operand_load_signal, exec_subcycle_1, write_a_2cycle, write_a_txa, write_a_tya, write_a_transfer, write_a_signal, write_x_tax, write_x_inx, write_x_dex, write_x_temp, write_x_signal, write_y_tay, write_y_iny, write_y_dey, write_y_temp, write_y_signal }) => [
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0, out.current_state),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    inp.current_opcode.to(cmp_lda.a, cmp_adc.a, cmp_tax.a, cmp_tay.a, cmp_txa.a, cmp_tya.a, cmp_inx.a, cmp_dex.a, cmp_iny.a, cmp_dey.a),
    LDA_IMM.out.to(cmp_lda.b),
    cmp_lda.eq.to(out.is_lda, needs_operand.a),
    ADC_IMM.out.to(cmp_adc.b),
    cmp_adc.eq.to(out.is_adc, needs_operand.b),
    TAX.out.to(cmp_tax.b),
    cmp_tax.eq.to(out.is_tax, is_1cycle.a, write_x_tax.b),
    TAY.out.to(cmp_tay.b),
    cmp_tay.eq.to(out.is_tay, is_1cycle.b, write_y_tay.b),
    TXA.out.to(cmp_txa.b),
    cmp_txa.eq.to(out.is_txa, is_1cycle_2.b, write_a_txa.b),
    TYA.out.to(cmp_tya.b),
    cmp_tya.eq.to(out.is_tya, is_1cycle_3.b, write_a_tya.b),
    INX.out.to(cmp_inx.b),
    cmp_inx.eq.to(out.is_inx, is_1cycle_4.b, write_x_inx.b),
    DEX.out.to(cmp_dex.b),
    cmp_dex.eq.to(out.is_dex, is_1cycle_5.b, write_x_dex.b),
    INY.out.to(cmp_iny.b),
    cmp_iny.eq.to(out.is_iny, is_1cycle_6.b, write_y_iny.b),
    DEY.out.to(cmp_dey.b),
    cmp_dey.eq.to(out.is_dey, is_1cycle_final.b, write_y_dey.b),
    subcycle_reg.q.to(inc_subcycle.in, out.exec_subcycle, is_subcycle_0.a, is_subcycle_1.a),
    is_execute.eq.to(subcycle_increment.sel, exec_done_2cycle.a, exec_done_1cycle.a, exec_subcycle_0.a, exec_subcycle_1.a),
    zero.out.to(subcycle_increment.in0, is_subcycle_0.b),
    inc_subcycle.out.to(subcycle_increment.in1),
    subcycle_increment.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we),
    one.out.to(is_subcycle_1.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_signal.a, out.ir_load),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    is_subcycle_1.eq.to(exec_done_2cycle.b, exec_subcycle_1.b),
    is_subcycle_0.eq.to(exec_done_1cycle.b, exec_subcycle_0.b),
    is_1cycle.out.to(is_1cycle_2.a),
    is_1cycle_2.out.to(is_1cycle_3.a),
    is_1cycle_3.out.to(is_1cycle_4.a),
    is_1cycle_4.out.to(is_1cycle_5.a),
    is_1cycle_5.out.to(is_1cycle_6.a),
    is_1cycle_6.out.to(is_1cycle_final.a),
    exec_done_1cycle.out.to(exec_done_1cycle_check.a),
    is_1cycle_final.out.to(exec_done_1cycle_check.b),
    exec_done_2cycle.out.to(exec_done.a),
    exec_done_1cycle_check.out.to(exec_done.b),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    exec_subcycle_0.out.to(exec_subcycle_0_needs_operand.a, operand_load_signal.a, write_a_txa.a, write_a_tya.a, write_x_tax.a, write_x_inx.a, write_x_dex.a, write_y_tay.a, write_y_iny.a, write_y_dey.a),
    needs_operand.out.to(exec_subcycle_0_needs_operand.b, operand_load_signal.b, write_a_2cycle.b),
    exec_subcycle_0_needs_operand.out.to(pc_inc_signal.b),
    pc_inc_signal.out.to(out.pc_increment),
    operand_load_signal.out.to(out.operand_load),
    exec_subcycle_1.out.to(write_a_2cycle.a),
    write_a_txa.out.to(write_a_transfer.a),
    write_a_tya.out.to(write_a_transfer.b),
    write_a_2cycle.out.to(write_a_signal.a),
    write_a_transfer.out.to(write_a_signal.b),
    write_a_signal.out.to(out.write_a),
    write_x_tax.out.to(write_x_temp.a),
    write_x_inx.out.to(write_x_temp.b),
    write_x_temp.out.to(write_x_signal.a),
    write_x_dex.out.to(write_x_signal.b),
    write_x_signal.out.to(out.write_x),
    write_y_tay.out.to(write_y_temp.a),
    write_y_iny.out.to(write_y_temp.b),
    write_y_temp.out.to(write_y_signal.a),
    write_y_dey.out.to(write_y_signal.b),
    write_y_signal.out.to(out.write_y),
  ],
})

const Stage3CPU = component('Stage3CPU', {
  in: { reset: bit },
  out: { pc: bus(8), instruction: bus(8), operand: bus(8), current_state: bus(8), subcycle: bus(8), reg_a: bus(8), reg_x: bus(8), reg_y: bus(8) },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, ir: Register, operand_reg: Register, control: Stage3Control, pc_next: Mux, registers: RegisterFile, adder: Adder, inc_x: Incrementer, dec_x: Subtractor, inc_y: Incrementer, dec_y: Subtractor, result_a_lda_adc: Mux, result_a_txa: Mux, result_a: Mux, result_x_inx_dex: Mux, result_x: Mux, result_y_iny_dey: Mux, result_y: Mux },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, byte_0: { value: 169 }, byte_1: { value: 66 }, byte_2: { value: 170 }, byte_3: { value: 232 }, byte_4: { value: 152 }, byte_5: { value: 0 }, byte_6: { value: 0 }, byte_7: { value: 0 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, six, seven, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, mux1, mux2, mux3, mux4, mux5, mux6, mux7, ir, operand_reg, control, pc_next, registers, adder, inc_x, dec_x, inc_y, dec_y, result_a_lda_adc, result_a_txa, result_a, result_x_inx_dex, result_x, result_y_iny_dey, result_y }) => [
    always_on.out.to(pc_reg.we),
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, adder.carry_in, dec_x.borrow_in, dec_y.borrow_in),
    one.out.to(at_1.b, dec_x.b, dec_y.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    mux7.out.to(ir.data, operand_reg.data),
    inp.reset.to(control.reset),
    ir.q.to(control.current_opcode, out.instruction),
    control.pc_increment.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    control.ir_load.to(ir.we),
    control.operand_load.to(operand_reg.we),
    control.write_a.to(registers.write_a),
    control.write_x.to(registers.write_x),
    control.write_y.to(registers.write_y),
    registers.reg_a.to(adder.a, result_x.in1, result_y.in1, out.reg_a),
    operand_reg.q.to(adder.b, result_a_lda_adc.in1, out.operand),
    registers.reg_x.to(inc_x.in, dec_x.a, result_a_txa.in1, out.reg_x),
    registers.reg_y.to(inc_y.in, dec_y.a, result_a.in1, out.reg_y),
    control.is_lda.to(result_a_lda_adc.sel),
    adder.sum.to(result_a_lda_adc.in0),
    control.is_txa.to(result_a_txa.sel),
    result_a_lda_adc.out.to(result_a_txa.in0),
    control.is_tya.to(result_a.sel),
    result_a_txa.out.to(result_a.in0),
    result_a.out.to(registers.data_a),
    control.is_dex.to(result_x_inx_dex.sel),
    inc_x.out.to(result_x_inx_dex.in0),
    dec_x.difference.to(result_x_inx_dex.in1),
    control.is_tax.to(result_x.sel),
    result_x_inx_dex.out.to(result_x.in0),
    result_x.out.to(registers.data_x),
    control.is_dey.to(result_y_iny_dey.sel),
    inc_y.out.to(result_y_iny_dey.in0),
    dec_y.difference.to(result_y_iny_dey.in1),
    control.is_tay.to(result_y.sel),
    result_y_iny_dey.out.to(result_y.in0),
    result_y.out.to(registers.data_y),
    control.current_state.to(out.current_state),
    control.exec_subcycle.to(out.subcycle),
  ],
})

const Stage3XYTest = component('Stage3XYTest', {
  nodes: { cpu: Stage3CPU, reset_input: Input, d_pc: HexDisplay, d_instruction: HexDisplay, d_operand: HexDisplay, d_state: HexDisplay, d_subcycle: HexDisplay, d_a: HexDisplay, d_x: HexDisplay, d_y: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_instruction, d_operand, d_state, d_subcycle, d_a, d_x, d_y }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.instruction.to(d_instruction.in),
    cpu.operand.to(d_operand.in),
    cpu.current_state.to(d_state.in),
    cpu.subcycle.to(d_subcycle.in),
    cpu.reg_a.to(d_a.in),
    cpu.reg_x.to(d_x.in),
    cpu.reg_y.to(d_y.in),
  ],
})
