// Auto-generated from DSL

const SimpleMemory = component('SimpleMemory', {
  in: { addr: bus(8), data_in: bus(8), write_enable: bit },
  out: { data_out: bus(8) },
  nodes: { zero: Constant, addr_10: Constant, addr_11: Constant, addr_12: Constant, addr_13: Constant, addr_14: Constant, addr_15: Constant, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, mem_10: Register, mem_11: Register, mem_12: Register, mem_13: Register, mem_14: Register, mem_15: Register, we_10: And, we_11: And, we_12: And, we_13: And, we_14: And, we_15: And, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux },
  nodeArgs: { zero: { value: 0 }, addr_10: { value: 16 }, addr_11: { value: 17 }, addr_12: { value: 18 }, addr_13: { value: 19 }, addr_14: { value: 20 }, addr_15: { value: 21 } },
  connect: ({ in: inp, out, zero, addr_10, addr_11, addr_12, addr_13, addr_14, addr_15, at_10, at_11, at_12, at_13, at_14, at_15, mem_10, mem_11, mem_12, mem_13, mem_14, mem_15, we_10, we_11, we_12, we_13, we_14, we_15, mux1, mux2, mux3, mux4, mux5, mux6 }) => [
    inp.addr.to(at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a),
    addr_10.out.to(at_10.b),
    addr_11.out.to(at_11.b),
    addr_12.out.to(at_12.b),
    addr_13.out.to(at_13.b),
    addr_14.out.to(at_14.b),
    addr_15.out.to(at_15.b),
    inp.data_in.to(mem_10.data, mem_11.data, mem_12.data, mem_13.data, mem_14.data, mem_15.data),
    inp.write_enable.to(we_10.a, we_11.a, we_12.a, we_13.a, we_14.a, we_15.a),
    at_10.eq.to(we_10.b, mux1.sel),
    we_10.out.to(mem_10.we),
    at_11.eq.to(we_11.b, mux2.sel),
    we_11.out.to(mem_11.we),
    at_12.eq.to(we_12.b, mux3.sel),
    we_12.out.to(mem_12.we),
    at_13.eq.to(we_13.b, mux4.sel),
    we_13.out.to(mem_13.we),
    at_14.eq.to(we_14.b, mux5.sel),
    we_14.out.to(mem_14.we),
    at_15.eq.to(we_15.b, mux6.sel),
    we_15.out.to(mem_15.we),
    zero.out.to(mux1.in0),
    mem_10.q.to(mux1.in1),
    mux1.out.to(mux2.in0),
    mem_11.q.to(mux2.in1),
    mux2.out.to(mux3.in0),
    mem_12.q.to(mux3.in1),
    mux3.out.to(mux4.in0),
    mem_13.q.to(mux4.in1),
    mux4.out.to(mux5.in0),
    mem_14.q.to(mux5.in1),
    mux5.out.to(mux6.in0),
    mem_15.q.to(mux6.in1),
    mux6.out.to(out.data_out),
  ],
})

const RegisterFile = component('RegisterFile', {
  in: { write_a: bit, write_x: bit, write_y: bit, data_a: bus(8), data_x: bus(8), data_y: bus(8) },
  out: { reg_a: bus(8), reg_x: bus(8), reg_y: bus(8) },
  nodes: { regA: Register, regX: Register, regY: Register },
  connect: ({ in: inp, out, regA, regX, regY }) => [
    inp.data_a.to(regA.data),
    inp.data_x.to(regX.data),
    inp.data_y.to(regY.data),
    inp.write_a.to(regA.we),
    inp.write_x.to(regX.we),
    inp.write_y.to(regY.we),
    regA.q.to(out.reg_a),
    regX.q.to(out.reg_x),
    regY.q.to(out.reg_y),
  ],
})

const CompleteControl = component('CompleteControl', {
  in: { reset: bit, current_opcode: bus(8) },
  out: { current_state: bus(8), exec_subcycle: bus(8), pc_increment: bit, ir_load: bit, operand_load: bit, addr_lo_load: bit, addr_hi_load: bit, mem_read: bit, mem_write: bit, write_a: bit, write_x: bit, write_y: bit, is_lda_imm: bit, is_lda_zp: bit, is_lda_abs: bit, is_lda_abs_x: bit, is_sta_zp: bit, is_sta_abs: bit, is_sta_abs_x: bit, is_tax: bit, is_inx: bit },
  nodes: { state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDA_IMM: Constant, LDA_ZP: Constant, LDA_ABS: Constant, LDA_ABS_X: Constant, STA_ZP: Constant, STA_ABS: Constant, STA_ABS_X: Constant, TAX: Constant, INX: Constant, cmp_lda_imm: Comparator, cmp_lda_zp: Comparator, cmp_lda_abs: Comparator, cmp_lda_abs_x: Comparator, cmp_sta_zp: Comparator, cmp_sta_abs: Comparator, cmp_sta_abs_x: Comparator, cmp_tax: Comparator, cmp_inx: Comparator, is_imm: Or, is_zp: Or, is_abs_temp: Or, is_abs: Or, is_abs_final: Or, is_1cycle: Or, zero: Constant, one: Constant, two: Constant, three: Constant, inc_subcycle: Incrementer, subcycle_increment: Mux, always_on: Constant, is_sub0: Comparator, is_sub1: Comparator, is_sub2: Comparator, is_sub3: Comparator, four: Constant, is_sub4: Comparator, next_from_fetch: Mux, next_from_decode: Mux, exec_sub0: And, exec_sub1: And, exec_sub2: And, exec_sub3: And, exec_sub4: And, done_imm: And, done_zp: And, done_abs: And, done_1cyc: And, exec_done_temp1: Or, exec_done_temp2: Or, exec_done: Or, next_from_execute: Mux, next_state: Mux, needs_operand_any: Or, needs_operand: Or, pc_inc_exec_sub0: And, pc_inc_exec_sub1: And, pc_inc_temp: Or, pc_inc_signal: Or, operand_load_signal: And, addr_lo_load_signal: And, addr_hi_load_signal: And, is_load: Or, is_load_final: Or, mem_read_zp: And, mem_read_abs_temp: And, mem_read_abs_x: And, mem_read_abs: Or, mem_read_signal: Or, mem_write_zp: And, mem_write_abs_temp: And, mem_write_abs_x: And, mem_write_abs: Or, mem_write_signal: Or, write_a_imm: And, write_a_zp: And, write_a_abs_temp: And, write_a_abs_x: And, write_a_abs: Or, write_a_temp: Or, write_a_signal: Or, write_x_tax: And, write_x_inx: And, write_x_signal: Or },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDA_IMM: { value: 169 }, LDA_ZP: { value: 165 }, LDA_ABS: { value: 173 }, LDA_ABS_X: { value: 189 }, STA_ZP: { value: 133 }, STA_ABS: { value: 141 }, STA_ABS_X: { value: 157 }, TAX: { value: 170 }, INX: { value: 232 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, always_on: { value: 1 }, four: { value: 4 } },
  connect: ({ in: inp, out, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDA_IMM, LDA_ZP, LDA_ABS, LDA_ABS_X, STA_ZP, STA_ABS, STA_ABS_X, TAX, INX, cmp_lda_imm, cmp_lda_zp, cmp_lda_abs, cmp_lda_abs_x, cmp_sta_zp, cmp_sta_abs, cmp_sta_abs_x, cmp_tax, cmp_inx, is_imm, is_zp, is_abs_temp, is_abs, is_abs_final, is_1cycle, zero, one, two, three, inc_subcycle, subcycle_increment, always_on, is_sub0, is_sub1, is_sub2, is_sub3, four, is_sub4, next_from_fetch, next_from_decode, exec_sub0, exec_sub1, exec_sub2, exec_sub3, exec_sub4, done_imm, done_zp, done_abs, done_1cyc, exec_done_temp1, exec_done_temp2, exec_done, next_from_execute, next_state, needs_operand_any, needs_operand, pc_inc_exec_sub0, pc_inc_exec_sub1, pc_inc_temp, pc_inc_signal, operand_load_signal, addr_lo_load_signal, addr_hi_load_signal, is_load, is_load_final, mem_read_zp, mem_read_abs_temp, mem_read_abs_x, mem_read_abs, mem_read_signal, mem_write_zp, mem_write_abs_temp, mem_write_abs_x, mem_write_abs, mem_write_signal, write_a_imm, write_a_zp, write_a_abs_temp, write_a_abs_x, write_a_abs, write_a_temp, write_a_signal, write_x_tax, write_x_inx, write_x_signal }) => [
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0, out.current_state),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    inp.current_opcode.to(cmp_lda_imm.a, cmp_lda_zp.a, cmp_lda_abs.a, cmp_lda_abs_x.a, cmp_sta_zp.a, cmp_sta_abs.a, cmp_sta_abs_x.a, cmp_tax.a, cmp_inx.a),
    LDA_IMM.out.to(cmp_lda_imm.b),
    cmp_lda_imm.eq.to(out.is_lda_imm, is_imm.a, is_imm.b, write_a_imm.b),
    LDA_ZP.out.to(cmp_lda_zp.b),
    cmp_lda_zp.eq.to(out.is_lda_zp, is_zp.a, is_load.a, mem_read_zp.b, write_a_zp.b),
    LDA_ABS.out.to(cmp_lda_abs.b),
    cmp_lda_abs.eq.to(out.is_lda_abs, is_abs_temp.a, is_load.b, mem_read_abs_temp.b, write_a_abs_temp.b),
    LDA_ABS_X.out.to(cmp_lda_abs_x.b),
    cmp_lda_abs_x.eq.to(out.is_lda_abs_x, is_abs.b, is_load_final.b, mem_read_abs_x.b, write_a_abs_x.b),
    STA_ZP.out.to(cmp_sta_zp.b),
    cmp_sta_zp.eq.to(out.is_sta_zp, is_zp.b, mem_write_zp.b),
    STA_ABS.out.to(cmp_sta_abs.b),
    cmp_sta_abs.eq.to(out.is_sta_abs, is_abs_temp.b, mem_write_abs_temp.b),
    STA_ABS_X.out.to(cmp_sta_abs_x.b),
    cmp_sta_abs_x.eq.to(out.is_sta_abs_x, is_abs_final.b, mem_write_abs_x.b),
    TAX.out.to(cmp_tax.b),
    cmp_tax.eq.to(out.is_tax, is_1cycle.a, write_x_tax.b),
    INX.out.to(cmp_inx.b),
    cmp_inx.eq.to(out.is_inx, is_1cycle.b, write_x_inx.b),
    is_abs_temp.out.to(is_abs.a),
    is_abs.out.to(is_abs_final.a),
    subcycle_reg.q.to(inc_subcycle.in, out.exec_subcycle, is_sub0.a, is_sub1.a, is_sub2.a, is_sub3.a, is_sub4.a),
    is_execute.eq.to(subcycle_increment.sel, exec_sub0.a, exec_sub1.a, exec_sub2.a, exec_sub3.a, exec_sub4.a),
    zero.out.to(subcycle_increment.in0, is_sub0.b, out.write_y),
    inc_subcycle.out.to(subcycle_increment.in1),
    subcycle_increment.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we),
    one.out.to(is_sub1.b),
    two.out.to(is_sub2.b),
    three.out.to(is_sub3.b),
    four.out.to(is_sub4.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_temp.a, out.ir_load),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    is_sub0.eq.to(exec_sub0.b),
    is_sub1.eq.to(exec_sub1.b),
    is_sub2.eq.to(exec_sub2.b),
    is_sub3.eq.to(exec_sub3.b),
    is_sub4.eq.to(exec_sub4.b),
    exec_sub1.out.to(done_imm.a, pc_inc_exec_sub1.a, addr_hi_load_signal.a, write_a_imm.a),
    is_imm.out.to(done_imm.b, needs_operand_any.a),
    exec_sub3.out.to(done_zp.a, mem_read_abs_temp.a, mem_read_abs_x.a, mem_write_abs_temp.a, mem_write_abs_x.a, write_a_zp.a),
    is_zp.out.to(done_zp.b, needs_operand_any.b),
    exec_sub4.out.to(done_abs.a, write_a_abs_temp.a, write_a_abs_x.a),
    is_abs_final.out.to(done_abs.b, needs_operand.b, pc_inc_exec_sub1.b, addr_hi_load_signal.b),
    exec_sub0.out.to(done_1cyc.a, pc_inc_exec_sub0.a, operand_load_signal.a, addr_lo_load_signal.a, write_x_tax.a, write_x_inx.a),
    is_1cycle.out.to(done_1cyc.b),
    done_imm.out.to(exec_done_temp1.a),
    done_zp.out.to(exec_done_temp1.b),
    exec_done_temp1.out.to(exec_done_temp2.a),
    done_abs.out.to(exec_done_temp2.b),
    exec_done_temp2.out.to(exec_done.a),
    done_1cyc.out.to(exec_done.b),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    needs_operand_any.out.to(needs_operand.a),
    needs_operand.out.to(pc_inc_exec_sub0.b, operand_load_signal.b, addr_lo_load_signal.b),
    pc_inc_exec_sub0.out.to(pc_inc_temp.b),
    pc_inc_temp.out.to(pc_inc_signal.a),
    pc_inc_exec_sub1.out.to(pc_inc_signal.b),
    pc_inc_signal.out.to(out.pc_increment),
    operand_load_signal.out.to(out.operand_load),
    addr_lo_load_signal.out.to(out.addr_lo_load),
    addr_hi_load_signal.out.to(out.addr_hi_load),
    is_load.out.to(is_load_final.a),
    exec_sub2.out.to(mem_read_zp.a, mem_write_zp.a),
    mem_read_abs_temp.out.to(mem_read_abs.a),
    mem_read_abs_x.out.to(mem_read_abs.b),
    mem_read_zp.out.to(mem_read_signal.a),
    mem_read_abs.out.to(mem_read_signal.b),
    mem_read_signal.out.to(out.mem_read),
    mem_write_abs_temp.out.to(mem_write_abs.a),
    mem_write_abs_x.out.to(mem_write_abs.b),
    mem_write_zp.out.to(mem_write_signal.a),
    mem_write_abs.out.to(mem_write_signal.b),
    mem_write_signal.out.to(out.mem_write),
    write_a_abs_temp.out.to(write_a_abs.a),
    write_a_abs_x.out.to(write_a_abs.b),
    write_a_imm.out.to(write_a_temp.a),
    write_a_zp.out.to(write_a_temp.b),
    write_a_temp.out.to(write_a_signal.a),
    write_a_abs.out.to(write_a_signal.b),
    write_a_signal.out.to(out.write_a),
    write_x_tax.out.to(write_x_signal.a),
    write_x_inx.out.to(write_x_signal.b),
    write_x_signal.out.to(out.write_x),
  ],
})

const CompleteCPU = component('CompleteCPU', {
  in: { reset: bit },
  out: { pc: bus(8), instruction: bus(8), operand: bus(8), address: bus(8), mem_data: bus(8), current_state: bus(8), subcycle: bus(8), reg_a: bus(8), reg_x: bus(8) },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, byte_8: Constant, byte_9: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, at_8: Comparator, at_9: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, ir: Register, operand_reg: Register, addr_lo_reg: Register, addr_hi_reg: Register, addr_with_x: Adder, control: CompleteControl, pc_next: Mux, registers: RegisterFile, effective_addr: Mux, effective_addr_final: Mux, memory: SimpleMemory, inc_x: Incrementer, result_a_imm_zp: Mux, result_a_abs: Mux, result_a: Mux, result_x: Mux },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, byte_0: { value: 169 }, byte_1: { value: 66 }, byte_2: { value: 141 }, byte_3: { value: 16 }, byte_4: { value: 0 }, byte_5: { value: 173 }, byte_6: { value: 16 }, byte_7: { value: 0 }, byte_8: { value: 170 }, byte_9: { value: 232 }, byte_10: { value: 0 }, byte_11: { value: 0 }, byte_12: { value: 0 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, at_8, at_9, at_10, at_11, at_12, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, ir, operand_reg, addr_lo_reg, addr_hi_reg, addr_with_x, control, pc_next, registers, effective_addr, effective_addr_final, memory, inc_x, result_a_imm_zp, result_a_abs, result_a, result_x }) => [
    always_on.out.to(pc_reg.we),
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, at_8.a, at_9.a, at_10.a, at_11.a, at_12.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, addr_with_x.carry_in, registers.data_y),
    one.out.to(at_1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    eight.out.to(at_8.b),
    nine.out.to(at_9.b),
    ten.out.to(at_10.b),
    eleven.out.to(at_11.b),
    twelve.out.to(at_12.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    at_8.eq.to(mux8.sel),
    mux7.out.to(mux8.in0),
    byte_8.out.to(mux8.in1),
    at_9.eq.to(mux9.sel),
    mux8.out.to(mux9.in0),
    byte_9.out.to(mux9.in1),
    at_10.eq.to(mux10.sel),
    mux9.out.to(mux10.in0),
    byte_10.out.to(mux10.in1),
    at_11.eq.to(mux11.sel),
    mux10.out.to(mux11.in0),
    byte_11.out.to(mux11.in1),
    at_12.eq.to(mux12.sel),
    mux11.out.to(mux12.in0),
    byte_12.out.to(mux12.in1),
    mux12.out.to(ir.data, operand_reg.data, addr_lo_reg.data, addr_hi_reg.data),
    addr_lo_reg.q.to(addr_with_x.a, effective_addr.in0),
    inp.reset.to(control.reset),
    ir.q.to(control.current_opcode, out.instruction),
    control.pc_increment.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    control.ir_load.to(ir.we),
    control.operand_load.to(operand_reg.we),
    control.addr_lo_load.to(addr_lo_reg.we),
    control.addr_hi_load.to(addr_hi_reg.we),
    control.write_a.to(registers.write_a),
    control.write_x.to(registers.write_x),
    control.write_y.to(registers.write_y),
    control.is_lda_abs_x.to(effective_addr.sel, result_a.sel),
    addr_with_x.sum.to(effective_addr.in1, effective_addr_final.in1),
    control.is_sta_abs_x.to(effective_addr_final.sel),
    effective_addr.out.to(effective_addr_final.in0),
    registers.reg_x.to(addr_with_x.b, inc_x.in, out.reg_x),
    effective_addr_final.out.to(memory.addr, out.address),
    control.mem_write.to(memory.write_enable),
    registers.reg_a.to(memory.data_in, result_x.in1, out.reg_a),
    control.is_lda_zp.to(result_a_imm_zp.sel),
    operand_reg.q.to(result_a_imm_zp.in0, out.operand),
    memory.data_out.to(result_a_imm_zp.in1, result_a_abs.in1, result_a.in1, out.mem_data),
    control.is_lda_abs.to(result_a_abs.sel),
    result_a_imm_zp.out.to(result_a_abs.in0),
    result_a_abs.out.to(result_a.in0),
    result_a.out.to(registers.data_a),
    control.is_tax.to(result_x.sel),
    inc_x.out.to(result_x.in0),
    result_x.out.to(registers.data_x),
    control.current_state.to(out.current_state),
    control.exec_subcycle.to(out.subcycle),
  ],
})

const CompleteTest = component('CompleteTest', {
  nodes: { cpu: CompleteCPU, reset_input: Input, d_pc: HexDisplay, d_instruction: HexDisplay, d_operand: HexDisplay, d_address: HexDisplay, d_mem_data: HexDisplay, d_state: HexDisplay, d_subcycle: HexDisplay, d_a: HexDisplay, d_x: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_instruction, d_operand, d_address, d_mem_data, d_state, d_subcycle, d_a, d_x }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.instruction.to(d_instruction.in),
    cpu.operand.to(d_operand.in),
    cpu.address.to(d_address.in),
    cpu.mem_data.to(d_mem_data.in),
    cpu.current_state.to(d_state.in),
    cpu.subcycle.to(d_subcycle.in),
    cpu.reg_a.to(d_a.in),
    cpu.reg_x.to(d_x.in),
  ],
})
