// Auto-generated from DSL

const FlagRegister = circuit('FlagRegister', {
  in: { update_n: bit, update_z: bit, update_c: bit, update_v: bit, new_n: bit, new_z: bit, new_c: bit, new_v: bit },
  out: { flag_n: bit, flag_z: bit, flag_c: bit, flag_v: bit },
  nodes: { reg_n: Register, reg_z: Register, reg_c: Register, reg_v: Register },
  nodeArgs: { reg_n: { initial: 0 }, reg_z: { initial: 0 }, reg_c: { initial: 0 }, reg_v: { initial: 0 } },
  connect: ({ in: inp, out, reg_n, reg_z, reg_c, reg_v }) => [
    inp.update_n.to(reg_n.we),
    inp.new_n.to(reg_n.data),
    reg_n.q.to(out.flag_n),
    inp.update_z.to(reg_z.we),
    inp.new_z.to(reg_z.data),
    reg_z.q.to(out.flag_z),
    inp.update_c.to(reg_c.we),
    inp.new_c.to(reg_c.data),
    reg_c.q.to(out.flag_c),
    inp.update_v.to(reg_v.we),
    inp.new_v.to(reg_v.data),
    reg_v.q.to(out.flag_v),
  ],
})

const FlagCalculator = circuit('FlagCalculator', {
  in: { result: bus(8), carry_out: bit, operand_a_bit7: bit, operand_b_bit7: bit, result_bit7: bit },
  out: { calc_n: bit, calc_z: bit, calc_c: bit, calc_v: bit },
  nodes: { const_128: Constant, cmp_neg: Comparator, n_flag: Or, const_0: Constant, cmp_zero: Comparator, xor_ab: Xor, xor_ar: Xor, not_xor_ab: Not, v_flag: And },
  nodeArgs: { const_128: { value: 128 }, const_0: { value: 0 } },
  connect: ({ in: inp, out, const_128, cmp_neg, n_flag, const_0, cmp_zero, xor_ab, xor_ar, not_xor_ab, v_flag }) => [
    inp.result.to(cmp_neg.a, cmp_zero.a),
    const_128.out.to(cmp_neg.b),
    cmp_neg.gt.to(n_flag.a),
    cmp_neg.eq.to(n_flag.b),
    n_flag.out.to(out.calc_n),
    const_0.out.to(cmp_zero.b),
    cmp_zero.eq.to(out.calc_z),
    inp.carry_out.to(out.calc_c),
    inp.operand_a_bit7.to(xor_ab.a, xor_ar.a),
    inp.operand_b_bit7.to(xor_ab.b),
    inp.result_bit7.to(xor_ar.b),
    xor_ab.out.to(not_xor_ab.in),
    not_xor_ab.out.to(v_flag.a),
    xor_ar.out.to(v_flag.b),
    v_flag.out.to(out.calc_v),
  ],
})

const Bit7Extractor = circuit('Bit7Extractor', {
  in: { value: bus(8) },
  out: { bit7: bit },
  nodes: { const_128: Constant, cmp: Comparator, is_gte: Or },
  nodeArgs: { const_128: { value: 128 } },
  connect: ({ in: inp, out, const_128, cmp, is_gte }) => [
    inp.value.to(cmp.a),
    const_128.out.to(cmp.b),
    cmp.gt.to(is_gte.a),
    cmp.eq.to(is_gte.b),
    is_gte.out.to(out.bit7),
  ],
})

const BranchCondition = circuit('BranchCondition', {
  in: { flag_n: bit, flag_z: bit, flag_c: bit, flag_v: bit, is_beq: bit, is_bne: bit, is_bcc: bit, is_bcs: bit, is_bmi: bit, is_bpl: bit, is_bvc: bit, is_bvs: bit },
  out: { branch_taken: bit },
  nodes: { beq_cond: And, not_z: Not, bne_cond: And, not_c: Not, bcc_cond: And, bcs_cond: And, bmi_cond: And, not_n: Not, bpl_cond: And, not_v: Not, bvc_cond: And, bvs_cond: And, or1: Or, or2: Or, or3: Or, or4: Or, or5: Or, or6: Or, or7: Or },
  connect: ({ in: inp, out, beq_cond, not_z, bne_cond, not_c, bcc_cond, bcs_cond, bmi_cond, not_n, bpl_cond, not_v, bvc_cond, bvs_cond, or1, or2, or3, or4, or5, or6, or7 }) => [
    inp.is_beq.to(beq_cond.a),
    inp.flag_z.to(beq_cond.b, not_z.in),
    inp.is_bne.to(bne_cond.a),
    not_z.out.to(bne_cond.b),
    inp.flag_c.to(not_c.in, bcs_cond.b),
    inp.is_bcc.to(bcc_cond.a),
    not_c.out.to(bcc_cond.b),
    inp.is_bcs.to(bcs_cond.a),
    inp.is_bmi.to(bmi_cond.a),
    inp.flag_n.to(bmi_cond.b, not_n.in),
    inp.is_bpl.to(bpl_cond.a),
    not_n.out.to(bpl_cond.b),
    inp.flag_v.to(not_v.in, bvs_cond.b),
    inp.is_bvc.to(bvc_cond.a),
    not_v.out.to(bvc_cond.b),
    inp.is_bvs.to(bvs_cond.a),
    beq_cond.out.to(or1.a),
    bne_cond.out.to(or1.b),
    or1.out.to(or2.a),
    bcc_cond.out.to(or2.b),
    or2.out.to(or3.a),
    bcs_cond.out.to(or3.b),
    or3.out.to(or4.a),
    bmi_cond.out.to(or4.b),
    or4.out.to(or5.a),
    bpl_cond.out.to(or5.b),
    or5.out.to(or6.a),
    bvc_cond.out.to(or6.b),
    or6.out.to(or7.a),
    bvs_cond.out.to(or7.b),
    or7.out.to(out.branch_taken),
  ],
})

const SignedBranchAdder = circuit('SignedBranchAdder', {
  in: { pc: bus(8), offset: bus(8) },
  out: { result: bus(8) },
  nodes: { adder: Adder, zero: Constant },
  nodeArgs: { zero: { value: 0 } },
  connect: ({ in: inp, out, adder, zero }) => [
    inp.pc.to(adder.a),
    inp.offset.to(adder.b),
    zero.out.to(adder.carry_in),
    adder.sum.to(out.result),
  ],
})

const FlagTest = circuit('FlagTest', {
  nodes: { flags: FlagRegister, calc: FlagCalculator, bit7_a: Bit7Extractor, bit7_b: Bit7Extractor, bit7_r: Bit7Extractor, branch: BranchCondition, result_input: Input, operand_a_input: Input, operand_b_input: Input, carry_input: Input, update_input: Input, beq_input: Input, bne_input: Input, bcc_input: Input, bcs_input: Input, bmi_input: Input, bpl_input: Input, bvc_input: Input, bvs_input: Input, d_n: HexDisplay, d_z: HexDisplay, d_c: HexDisplay, d_v: HexDisplay, d_branch: HexDisplay },
  connect: ({ in: inp, out, flags, calc, bit7_a, bit7_b, bit7_r, branch, result_input, operand_a_input, operand_b_input, carry_input, update_input, beq_input, bne_input, bcc_input, bcs_input, bmi_input, bpl_input, bvc_input, bvs_input, d_n, d_z, d_c, d_v, d_branch }) => [
    flags.flag_n.to(branch.flag_n, d_n.in),
    flags.flag_z.to(branch.flag_z, d_z.in),
    flags.flag_c.to(branch.flag_c, d_c.in),
    flags.flag_v.to(branch.flag_v, d_v.in),
    result_input.out.to(calc.result, bit7_r.value),
    bit7_r.bit7.to(calc.result_bit7),
    operand_a_input.out.to(bit7_a.value),
    bit7_a.bit7.to(calc.operand_a_bit7),
    operand_b_input.out.to(bit7_b.value),
    bit7_b.bit7.to(calc.operand_b_bit7),
    carry_input.out.to(calc.carry_out),
    update_input.out.to(flags.update_n, flags.update_z, flags.update_c, flags.update_v),
    calc.calc_n.to(flags.new_n),
    calc.calc_z.to(flags.new_z),
    calc.calc_c.to(flags.new_c),
    calc.calc_v.to(flags.new_v),
    beq_input.out.to(branch.is_beq),
    bne_input.out.to(branch.is_bne),
    bcc_input.out.to(branch.is_bcc),
    bcs_input.out.to(branch.is_bcs),
    bmi_input.out.to(branch.is_bmi),
    bpl_input.out.to(branch.is_bpl),
    bvc_input.out.to(branch.is_bvc),
    bvs_input.out.to(branch.is_bvs),
    branch.branch_taken.to(d_branch.in),
  ],
})
