// Auto-generated from DSL

const SimpleMemory = circuit('SimpleMemory', {
  in: { addr: bus(8), data_in: bus(8), write_enable: bit },
  out: { data_out: bus(8) },
  nodes: { zero: Constant, addr_10: Constant, addr_11: Constant, addr_12: Constant, addr_13: Constant, addr_14: Constant, addr_15: Constant, addr_20: Constant, addr_21: Constant, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, at_20: Comparator, at_21: Comparator, mem_10: Register, mem_11: Register, mem_12: Register, mem_13: Register, mem_14: Register, mem_15: Register, mem_20: Register, mem_21: Register, we_10: And, we_11: And, we_12: And, we_13: And, we_14: And, we_15: And, we_20: And, we_21: And, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux },
  nodeArgs: { zero: { value: 0 }, addr_10: { value: 16 }, addr_11: { value: 17 }, addr_12: { value: 18 }, addr_13: { value: 19 }, addr_14: { value: 20 }, addr_15: { value: 21 }, addr_20: { value: 32 }, addr_21: { value: 33 } },
  connect: ({ in: inp, out, zero, addr_10, addr_11, addr_12, addr_13, addr_14, addr_15, addr_20, addr_21, at_10, at_11, at_12, at_13, at_14, at_15, at_20, at_21, mem_10, mem_11, mem_12, mem_13, mem_14, mem_15, mem_20, mem_21, we_10, we_11, we_12, we_13, we_14, we_15, we_20, we_21, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8 }) => [
    inp.addr.to(at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, at_20.a, at_21.a),
    addr_10.out.to(at_10.b),
    addr_11.out.to(at_11.b),
    addr_12.out.to(at_12.b),
    addr_13.out.to(at_13.b),
    addr_14.out.to(at_14.b),
    addr_15.out.to(at_15.b),
    addr_20.out.to(at_20.b),
    addr_21.out.to(at_21.b),
    inp.data_in.to(mem_10.data, mem_11.data, mem_12.data, mem_13.data, mem_14.data, mem_15.data, mem_20.data, mem_21.data),
    inp.write_enable.to(we_10.a, we_11.a, we_12.a, we_13.a, we_14.a, we_15.a, we_20.a, we_21.a),
    at_10.eq.to(we_10.b, mux1.sel),
    we_10.out.to(mem_10.we),
    at_11.eq.to(we_11.b, mux2.sel),
    we_11.out.to(mem_11.we),
    at_12.eq.to(we_12.b, mux3.sel),
    we_12.out.to(mem_12.we),
    at_13.eq.to(we_13.b, mux4.sel),
    we_13.out.to(mem_13.we),
    at_14.eq.to(we_14.b, mux5.sel),
    we_14.out.to(mem_14.we),
    at_15.eq.to(we_15.b, mux6.sel),
    we_15.out.to(mem_15.we),
    at_20.eq.to(we_20.b, mux7.sel),
    we_20.out.to(mem_20.we),
    at_21.eq.to(we_21.b, mux8.sel),
    we_21.out.to(mem_21.we),
    zero.out.to(mux1.in0),
    mem_10.q.to(mux1.in1),
    mux1.out.to(mux2.in0),
    mem_11.q.to(mux2.in1),
    mux2.out.to(mux3.in0),
    mem_12.q.to(mux3.in1),
    mux3.out.to(mux4.in0),
    mem_13.q.to(mux4.in1),
    mux4.out.to(mux5.in0),
    mem_14.q.to(mux5.in1),
    mux5.out.to(mux6.in0),
    mem_15.q.to(mux6.in1),
    mux6.out.to(mux7.in0),
    mem_20.q.to(mux7.in1),
    mux7.out.to(mux8.in0),
    mem_21.q.to(mux8.in1),
    mux8.out.to(out.data_out),
  ],
})

const RegisterFile = circuit('RegisterFile', {
  in: { write_a: bit, write_x: bit, write_y: bit, data_a: bus(8), data_x: bus(8), data_y: bus(8) },
  out: { reg_a: bus(8), reg_x: bus(8), reg_y: bus(8) },
  nodes: { regA: Register, regX: Register, regY: Register },
  connect: ({ in: inp, out, regA, regX, regY }) => [
    inp.data_a.to(regA.data),
    inp.data_x.to(regX.data),
    inp.data_y.to(regY.data),
    inp.write_a.to(regA.we),
    inp.write_x.to(regX.we),
    inp.write_y.to(regY.we),
    regA.q.to(out.reg_a),
    regX.q.to(out.reg_x),
    regY.q.to(out.reg_y),
  ],
})

const StackPointer = circuit('StackPointer', {
  in: { decrement: bit, increment: bit, load: bit, load_value: bus(8) },
  out: { sp: bus(8) },
  nodes: { sp_reg: Register, always_on: Constant, one: Constant, dec: Subtractor, zero_bit: Constant, inc: Adder, mux_inc: Mux, mux_dec: Mux, mux_load: Mux },
  nodeArgs: { sp_reg: { initial: 255 }, always_on: { value: 1 }, one: { value: 1 }, zero_bit: { value: 0 } },
  connect: ({ in: inp, out, sp_reg, always_on, one, dec, zero_bit, inc, mux_inc, mux_dec, mux_load }) => [
    always_on.out.to(sp_reg.we),
    sp_reg.q.to(dec.a, inc.a, mux_inc.in0, out.sp),
    one.out.to(dec.b, inc.b),
    zero_bit.out.to(dec.borrow_in, inc.carry_in),
    inp.increment.to(mux_inc.sel),
    inc.sum.to(mux_inc.in1),
    inp.decrement.to(mux_dec.sel),
    mux_inc.out.to(mux_dec.in0),
    dec.difference.to(mux_dec.in1),
    inp.load.to(mux_load.sel),
    mux_dec.out.to(mux_load.in0),
    inp.load_value.to(mux_load.in1),
    mux_load.out.to(sp_reg.data),
  ],
})

const StackMemory = circuit('StackMemory', {
  in: { addr: bus(8), data_in: bus(8), write_enable: bit },
  out: { data_out: bus(8) },
  nodes: { zero: Constant, addr_f0: Constant, addr_f1: Constant, addr_f2: Constant, addr_f3: Constant, addr_f4: Constant, addr_f5: Constant, addr_f6: Constant, addr_f7: Constant, addr_f8: Constant, addr_f9: Constant, addr_fa: Constant, addr_fb: Constant, addr_fc: Constant, addr_fd: Constant, addr_fe: Constant, addr_ff: Constant, at_f0: Comparator, at_f1: Comparator, at_f2: Comparator, at_f3: Comparator, at_f4: Comparator, at_f5: Comparator, at_f6: Comparator, at_f7: Comparator, at_f8: Comparator, at_f9: Comparator, at_fa: Comparator, at_fb: Comparator, at_fc: Comparator, at_fd: Comparator, at_fe: Comparator, at_ff: Comparator, mem_f0: Register, mem_f1: Register, mem_f2: Register, mem_f3: Register, mem_f4: Register, mem_f5: Register, mem_f6: Register, mem_f7: Register, mem_f8: Register, mem_f9: Register, mem_fa: Register, mem_fb: Register, mem_fc: Register, mem_fd: Register, mem_fe: Register, mem_ff: Register, we_f0: And, we_f1: And, we_f2: And, we_f3: And, we_f4: And, we_f5: And, we_f6: And, we_f7: And, we_f8: And, we_f9: And, we_fa: And, we_fb: And, we_fc: And, we_fd: And, we_fe: And, we_ff: And, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, mux13: Mux, mux14: Mux, mux15: Mux, mux16: Mux },
  nodeArgs: { zero: { value: 0 }, addr_f0: { value: 240 }, addr_f1: { value: 241 }, addr_f2: { value: 242 }, addr_f3: { value: 243 }, addr_f4: { value: 244 }, addr_f5: { value: 245 }, addr_f6: { value: 246 }, addr_f7: { value: 247 }, addr_f8: { value: 248 }, addr_f9: { value: 249 }, addr_fa: { value: 250 }, addr_fb: { value: 251 }, addr_fc: { value: 252 }, addr_fd: { value: 253 }, addr_fe: { value: 254 }, addr_ff: { value: 255 } },
  connect: ({ in: inp, out, zero, addr_f0, addr_f1, addr_f2, addr_f3, addr_f4, addr_f5, addr_f6, addr_f7, addr_f8, addr_f9, addr_fa, addr_fb, addr_fc, addr_fd, addr_fe, addr_ff, at_f0, at_f1, at_f2, at_f3, at_f4, at_f5, at_f6, at_f7, at_f8, at_f9, at_fa, at_fb, at_fc, at_fd, at_fe, at_ff, mem_f0, mem_f1, mem_f2, mem_f3, mem_f4, mem_f5, mem_f6, mem_f7, mem_f8, mem_f9, mem_fa, mem_fb, mem_fc, mem_fd, mem_fe, mem_ff, we_f0, we_f1, we_f2, we_f3, we_f4, we_f5, we_f6, we_f7, we_f8, we_f9, we_fa, we_fb, we_fc, we_fd, we_fe, we_ff, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, mux13, mux14, mux15, mux16 }) => [
    inp.addr.to(at_f0.a, at_f1.a, at_f2.a, at_f3.a, at_f4.a, at_f5.a, at_f6.a, at_f7.a, at_f8.a, at_f9.a, at_fa.a, at_fb.a, at_fc.a, at_fd.a, at_fe.a, at_ff.a),
    addr_f0.out.to(at_f0.b),
    addr_f1.out.to(at_f1.b),
    addr_f2.out.to(at_f2.b),
    addr_f3.out.to(at_f3.b),
    addr_f4.out.to(at_f4.b),
    addr_f5.out.to(at_f5.b),
    addr_f6.out.to(at_f6.b),
    addr_f7.out.to(at_f7.b),
    addr_f8.out.to(at_f8.b),
    addr_f9.out.to(at_f9.b),
    addr_fa.out.to(at_fa.b),
    addr_fb.out.to(at_fb.b),
    addr_fc.out.to(at_fc.b),
    addr_fd.out.to(at_fd.b),
    addr_fe.out.to(at_fe.b),
    addr_ff.out.to(at_ff.b),
    inp.data_in.to(mem_f0.data, mem_f1.data, mem_f2.data, mem_f3.data, mem_f4.data, mem_f5.data, mem_f6.data, mem_f7.data, mem_f8.data, mem_f9.data, mem_fa.data, mem_fb.data, mem_fc.data, mem_fd.data, mem_fe.data, mem_ff.data),
    inp.write_enable.to(we_f0.a, we_f1.a, we_f2.a, we_f3.a, we_f4.a, we_f5.a, we_f6.a, we_f7.a, we_f8.a, we_f9.a, we_fa.a, we_fb.a, we_fc.a, we_fd.a, we_fe.a, we_ff.a),
    at_f0.eq.to(we_f0.b, mux1.sel),
    we_f0.out.to(mem_f0.we),
    at_f1.eq.to(we_f1.b, mux2.sel),
    we_f1.out.to(mem_f1.we),
    at_f2.eq.to(we_f2.b, mux3.sel),
    we_f2.out.to(mem_f2.we),
    at_f3.eq.to(we_f3.b, mux4.sel),
    we_f3.out.to(mem_f3.we),
    at_f4.eq.to(we_f4.b, mux5.sel),
    we_f4.out.to(mem_f4.we),
    at_f5.eq.to(we_f5.b, mux6.sel),
    we_f5.out.to(mem_f5.we),
    at_f6.eq.to(we_f6.b, mux7.sel),
    we_f6.out.to(mem_f6.we),
    at_f7.eq.to(we_f7.b, mux8.sel),
    we_f7.out.to(mem_f7.we),
    at_f8.eq.to(we_f8.b, mux9.sel),
    we_f8.out.to(mem_f8.we),
    at_f9.eq.to(we_f9.b, mux10.sel),
    we_f9.out.to(mem_f9.we),
    at_fa.eq.to(we_fa.b, mux11.sel),
    we_fa.out.to(mem_fa.we),
    at_fb.eq.to(we_fb.b, mux12.sel),
    we_fb.out.to(mem_fb.we),
    at_fc.eq.to(we_fc.b, mux13.sel),
    we_fc.out.to(mem_fc.we),
    at_fd.eq.to(we_fd.b, mux14.sel),
    we_fd.out.to(mem_fd.we),
    at_fe.eq.to(we_fe.b, mux15.sel),
    we_fe.out.to(mem_fe.we),
    at_ff.eq.to(we_ff.b, mux16.sel),
    we_ff.out.to(mem_ff.we),
    zero.out.to(mux1.in0),
    mem_f0.q.to(mux1.in1),
    mux1.out.to(mux2.in0),
    mem_f1.q.to(mux2.in1),
    mux2.out.to(mux3.in0),
    mem_f2.q.to(mux3.in1),
    mux3.out.to(mux4.in0),
    mem_f3.q.to(mux4.in1),
    mux4.out.to(mux5.in0),
    mem_f4.q.to(mux5.in1),
    mux5.out.to(mux6.in0),
    mem_f5.q.to(mux6.in1),
    mux6.out.to(mux7.in0),
    mem_f6.q.to(mux7.in1),
    mux7.out.to(mux8.in0),
    mem_f7.q.to(mux8.in1),
    mux8.out.to(mux9.in0),
    mem_f8.q.to(mux9.in1),
    mux9.out.to(mux10.in0),
    mem_f9.q.to(mux10.in1),
    mux10.out.to(mux11.in0),
    mem_fa.q.to(mux11.in1),
    mux11.out.to(mux12.in0),
    mem_fb.q.to(mux12.in1),
    mux12.out.to(mux13.in0),
    mem_fc.q.to(mux13.in1),
    mux13.out.to(mux14.in0),
    mem_fd.q.to(mux14.in1),
    mux14.out.to(mux15.in0),
    mem_fe.q.to(mux15.in1),
    mux15.out.to(mux16.in0),
    mem_ff.q.to(mux16.in1),
    mux16.out.to(out.data_out),
  ],
})

const FlagRegister = circuit('FlagRegister', {
  in: { update_n: bit, update_z: bit, update_c: bit, update_v: bit, new_n: bit, new_z: bit, new_c: bit, new_v: bit },
  out: { flag_n: bit, flag_z: bit, flag_c: bit, flag_v: bit, debug_update_z_received: bit, debug_new_z_received: bit },
  nodes: { reg_n: Register, reg_z: Register, reg_c: Register, reg_v: Register },
  nodeArgs: { reg_n: { initial: 0 }, reg_z: { initial: 0 }, reg_c: { initial: 0 }, reg_v: { initial: 0 } },
  connect: ({ in: inp, out, reg_n, reg_z, reg_c, reg_v }) => [
    inp.update_n.to(reg_n.we),
    inp.new_n.to(reg_n.data),
    reg_n.q.to(out.flag_n),
    inp.update_z.to(reg_z.we, out.debug_update_z_received),
    inp.new_z.to(reg_z.data, out.debug_new_z_received),
    reg_z.q.to(out.flag_z),
    inp.update_c.to(reg_c.we),
    inp.new_c.to(reg_c.data),
    reg_c.q.to(out.flag_c),
    inp.update_v.to(reg_v.we),
    inp.new_v.to(reg_v.data),
    reg_v.q.to(out.flag_v),
  ],
})

const Stage5Control = circuit('Stage5Control', {
  in: { reset: bit, current_opcode: bus(8), flag_n: bit, flag_z: bit, flag_c: bit, flag_v: bit },
  out: { current_state: bus(8), exec_subcycle: bus(8), pc_increment: bit, ir_load: bit, operand_load: bit, addr_lo_load: bit, addr_hi_load: bit, mem_read: bit, mem_write: bit, write_a: bit, write_x: bit, write_y: bit, sp_decrement: bit, sp_increment: bit, stack_write: bit, use_stack_data: bit, jsr_load_pc: bit, rts_load_pc: bit, push_pc_hi: bit, push_pc_lo: bit, pull_pc_lo: bit, pull_pc_hi: bit, branch_load_pc: bit, update_flags: bit, is_lda_imm: bit, is_lda_zp: bit, is_lda_abs: bit, is_lda_abs_x: bit, is_sta_zp: bit, is_sta_abs: bit, is_sta_abs_x: bit, is_tax: bit, is_inx: bit, is_pha: bit, is_pla: bit, is_jsr: bit, is_rts: bit, is_cmp_imm: bit, is_beq: bit, is_bne: bit, is_bcc: bit, is_bcs: bit, is_bmi: bit, is_bpl: bit },
  nodes: { state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDA_IMM: Constant, LDA_ZP: Constant, LDA_ABS: Constant, LDA_ABS_X: Constant, STA_ZP: Constant, STA_ABS: Constant, STA_ABS_X: Constant, TAX: Constant, INX: Constant, PHA: Constant, PLA: Constant, JSR: Constant, RTS: Constant, CMP_IMM: Constant, BEQ: Constant, BNE: Constant, BCC: Constant, BCS: Constant, BMI: Constant, BPL: Constant, cmp_lda_imm: Comparator, cmp_lda_zp: Comparator, cmp_lda_abs: Comparator, cmp_lda_abs_x: Comparator, cmp_sta_zp: Comparator, cmp_sta_abs: Comparator, cmp_sta_abs_x: Comparator, cmp_tax: Comparator, cmp_inx: Comparator, cmp_pha: Comparator, cmp_pla: Comparator, cmp_jsr: Comparator, cmp_rts: Comparator, cmp_cmp_imm: Comparator, cmp_beq: Comparator, cmp_bne: Comparator, cmp_bcc: Comparator, cmp_bcs: Comparator, cmp_bmi: Comparator, cmp_bpl: Comparator, is_imm_lda_cmp: Or, is_imm: Or, is_zp: Or, is_abs_temp: Or, is_abs: Or, is_abs_final: Or, is_1cycle: Or, is_branch_1: Or, is_branch_2: Or, is_branch_3: Or, is_branch_4: Or, is_branch: Or, beq_cond: And, not_z: Not, bne_cond: And, not_c: Not, bcc_cond: And, bcs_cond: And, bmi_cond: And, not_n: Not, bpl_cond: And, branch_cond_1: Or, branch_cond_2: Or, branch_cond_3: Or, branch_cond_4: Or, branch_taken: Or, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, inc_subcycle: Incrementer, subcycle_increment: Mux, always_on: Constant, is_sub0: Comparator, is_sub1: Comparator, is_sub2: Comparator, is_sub3: Comparator, is_sub4: Comparator, is_sub5: Comparator, next_from_fetch: Mux, next_from_decode: Mux, exec_sub0: And, exec_sub1: And, exec_sub2: And, exec_sub3: And, exec_sub4: And, exec_sub5: And, done_imm: And, done_zp: And, done_abs: And, done_1cyc: And, done_pha: And, done_pla: And, done_jsr: And, done_rts: And, done_branch: And, exec_done_temp1: Or, exec_done_temp2: Or, exec_done_temp3: Or, exec_done_temp4: Or, exec_done_temp5: Or, exec_done_temp6: Or, exec_done_temp7: Or, exec_done: Or, next_from_execute: Mux, next_state: Mux, needs_operand_any: Or, needs_operand_temp: Or, needs_operand_temp2: Or, needs_operand: Or, pc_inc_exec_sub0: And, needs_2nd_byte: Or, pc_inc_exec_sub1: And, pc_inc_temp: Or, pc_inc_signal: Or, operand_load_signal: And, addr_lo_load_signal: And, addr_hi_load_signal: And, is_load: Or, is_load_final: Or, mem_read_zp: And, mem_read_abs_temp: And, mem_read_abs_x: And, mem_read_abs: Or, mem_read_signal: Or, mem_write_zp: And, mem_write_abs_temp: And, mem_write_abs_x: And, mem_write_abs: Or, mem_write_signal: Or, sp_dec_pha: And, sp_dec_jsr_sub2: And, sp_dec_jsr_sub3: And, sp_dec_temp: Or, sp_dec_signal: Or, sp_inc_pla: And, sp_inc_rts_sub0: And, sp_inc_rts_sub2: And, sp_inc_temp: Or, sp_inc_signal: Or, stack_write_pha: And, stack_write_jsr_hi: And, stack_write_jsr_lo: And, stack_write_temp: Or, stack_write_signal: Or, use_stack_signal: And, jsr_load_pc_signal: And, rts_load_pc_signal: And, push_pc_hi_signal: And, push_pc_lo_signal: And, pull_pc_lo_signal: And, pull_pc_hi_signal: And, branch_at_sub1: And, update_flags_lda: And, update_flags_cmp: And, update_flags_inx: And, update_flags_temp: Or, update_flags_signal: Or, write_a_imm: And, write_a_zp: And, write_a_abs_temp: And, write_a_abs_x: And, write_a_abs: Or, write_a_temp: Or, write_a_temp2: Or, write_a_pla: And, write_a_signal: Or, write_x_tax: And, write_x_inx: And, write_x_signal: Or },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDA_IMM: { value: 169 }, LDA_ZP: { value: 165 }, LDA_ABS: { value: 173 }, LDA_ABS_X: { value: 189 }, STA_ZP: { value: 133 }, STA_ABS: { value: 141 }, STA_ABS_X: { value: 157 }, TAX: { value: 170 }, INX: { value: 232 }, PHA: { value: 72 }, PLA: { value: 104 }, JSR: { value: 32 }, RTS: { value: 96 }, CMP_IMM: { value: 201 }, BEQ: { value: 240 }, BNE: { value: 208 }, BCC: { value: 144 }, BCS: { value: 176 }, BMI: { value: 48 }, BPL: { value: 16 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, always_on: { value: 1 } },
  connect: ({ in: inp, out, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDA_IMM, LDA_ZP, LDA_ABS, LDA_ABS_X, STA_ZP, STA_ABS, STA_ABS_X, TAX, INX, PHA, PLA, JSR, RTS, CMP_IMM, BEQ, BNE, BCC, BCS, BMI, BPL, cmp_lda_imm, cmp_lda_zp, cmp_lda_abs, cmp_lda_abs_x, cmp_sta_zp, cmp_sta_abs, cmp_sta_abs_x, cmp_tax, cmp_inx, cmp_pha, cmp_pla, cmp_jsr, cmp_rts, cmp_cmp_imm, cmp_beq, cmp_bne, cmp_bcc, cmp_bcs, cmp_bmi, cmp_bpl, is_imm_lda_cmp, is_imm, is_zp, is_abs_temp, is_abs, is_abs_final, is_1cycle, is_branch_1, is_branch_2, is_branch_3, is_branch_4, is_branch, beq_cond, not_z, bne_cond, not_c, bcc_cond, bcs_cond, bmi_cond, not_n, bpl_cond, branch_cond_1, branch_cond_2, branch_cond_3, branch_cond_4, branch_taken, zero, one, two, three, four, five, inc_subcycle, subcycle_increment, always_on, is_sub0, is_sub1, is_sub2, is_sub3, is_sub4, is_sub5, next_from_fetch, next_from_decode, exec_sub0, exec_sub1, exec_sub2, exec_sub3, exec_sub4, exec_sub5, done_imm, done_zp, done_abs, done_1cyc, done_pha, done_pla, done_jsr, done_rts, done_branch, exec_done_temp1, exec_done_temp2, exec_done_temp3, exec_done_temp4, exec_done_temp5, exec_done_temp6, exec_done_temp7, exec_done, next_from_execute, next_state, needs_operand_any, needs_operand_temp, needs_operand_temp2, needs_operand, pc_inc_exec_sub0, needs_2nd_byte, pc_inc_exec_sub1, pc_inc_temp, pc_inc_signal, operand_load_signal, addr_lo_load_signal, addr_hi_load_signal, is_load, is_load_final, mem_read_zp, mem_read_abs_temp, mem_read_abs_x, mem_read_abs, mem_read_signal, mem_write_zp, mem_write_abs_temp, mem_write_abs_x, mem_write_abs, mem_write_signal, sp_dec_pha, sp_dec_jsr_sub2, sp_dec_jsr_sub3, sp_dec_temp, sp_dec_signal, sp_inc_pla, sp_inc_rts_sub0, sp_inc_rts_sub2, sp_inc_temp, sp_inc_signal, stack_write_pha, stack_write_jsr_hi, stack_write_jsr_lo, stack_write_temp, stack_write_signal, use_stack_signal, jsr_load_pc_signal, rts_load_pc_signal, push_pc_hi_signal, push_pc_lo_signal, pull_pc_lo_signal, pull_pc_hi_signal, branch_at_sub1, update_flags_lda, update_flags_cmp, update_flags_inx, update_flags_temp, update_flags_signal, write_a_imm, write_a_zp, write_a_abs_temp, write_a_abs_x, write_a_abs, write_a_temp, write_a_temp2, write_a_pla, write_a_signal, write_x_tax, write_x_inx, write_x_signal }) => [
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0, out.current_state),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    inp.current_opcode.to(cmp_lda_imm.a, cmp_lda_zp.a, cmp_lda_abs.a, cmp_lda_abs_x.a, cmp_sta_zp.a, cmp_sta_abs.a, cmp_sta_abs_x.a, cmp_tax.a, cmp_inx.a, cmp_pha.a, cmp_pla.a, cmp_jsr.a, cmp_rts.a, cmp_cmp_imm.a, cmp_beq.a, cmp_bne.a, cmp_bcc.a, cmp_bcs.a, cmp_bmi.a, cmp_bpl.a),
    LDA_IMM.out.to(cmp_lda_imm.b),
    cmp_lda_imm.eq.to(out.is_lda_imm, is_imm_lda_cmp.a, is_imm.b, update_flags_lda.b, write_a_imm.b),
    LDA_ZP.out.to(cmp_lda_zp.b),
    cmp_lda_zp.eq.to(out.is_lda_zp, is_zp.a, is_load.a, mem_read_zp.b, write_a_zp.b),
    LDA_ABS.out.to(cmp_lda_abs.b),
    cmp_lda_abs.eq.to(out.is_lda_abs, is_abs_temp.a, is_load.b, mem_read_abs_temp.b, write_a_abs_temp.b),
    LDA_ABS_X.out.to(cmp_lda_abs_x.b),
    cmp_lda_abs_x.eq.to(out.is_lda_abs_x, is_abs.b, is_load_final.b, mem_read_abs_x.b, write_a_abs_x.b),
    STA_ZP.out.to(cmp_sta_zp.b),
    cmp_sta_zp.eq.to(out.is_sta_zp, is_zp.b, mem_write_zp.b),
    STA_ABS.out.to(cmp_sta_abs.b),
    cmp_sta_abs.eq.to(out.is_sta_abs, is_abs_temp.b, mem_write_abs_temp.b),
    STA_ABS_X.out.to(cmp_sta_abs_x.b),
    cmp_sta_abs_x.eq.to(out.is_sta_abs_x, is_abs_final.b, mem_write_abs_x.b),
    TAX.out.to(cmp_tax.b),
    cmp_tax.eq.to(out.is_tax, is_1cycle.a, write_x_tax.b),
    INX.out.to(cmp_inx.b),
    cmp_inx.eq.to(out.is_inx, is_1cycle.b, update_flags_inx.b, write_x_inx.b),
    PHA.out.to(cmp_pha.b),
    cmp_pha.eq.to(out.is_pha, done_pha.b, sp_dec_pha.b, stack_write_pha.b),
    PLA.out.to(cmp_pla.b),
    cmp_pla.eq.to(out.is_pla, done_pla.b, sp_inc_pla.b, use_stack_signal.b, write_a_pla.b),
    JSR.out.to(cmp_jsr.b),
    cmp_jsr.eq.to(out.is_jsr, done_jsr.b, needs_operand_temp2.b, needs_2nd_byte.b, sp_dec_jsr_sub2.b, sp_dec_jsr_sub3.b, stack_write_jsr_hi.b, stack_write_jsr_lo.b, jsr_load_pc_signal.b, push_pc_hi_signal.b, push_pc_lo_signal.b),
    RTS.out.to(cmp_rts.b),
    cmp_rts.eq.to(out.is_rts, done_rts.b, sp_inc_rts_sub0.b, sp_inc_rts_sub2.b, rts_load_pc_signal.b, pull_pc_lo_signal.b, pull_pc_hi_signal.b),
    CMP_IMM.out.to(cmp_cmp_imm.b),
    cmp_cmp_imm.eq.to(out.is_cmp_imm, is_imm_lda_cmp.b, update_flags_cmp.b),
    BEQ.out.to(cmp_beq.b),
    cmp_beq.eq.to(out.is_beq, is_branch_1.a, beq_cond.a),
    BNE.out.to(cmp_bne.b),
    cmp_bne.eq.to(out.is_bne, is_branch_1.b, bne_cond.a),
    BCC.out.to(cmp_bcc.b),
    cmp_bcc.eq.to(out.is_bcc, is_branch_2.b, bcc_cond.a),
    BCS.out.to(cmp_bcs.b),
    cmp_bcs.eq.to(out.is_bcs, is_branch_3.b, bcs_cond.a),
    BMI.out.to(cmp_bmi.b),
    cmp_bmi.eq.to(out.is_bmi, is_branch_4.b, bmi_cond.a),
    BPL.out.to(cmp_bpl.b),
    cmp_bpl.eq.to(out.is_bpl, is_branch.b, bpl_cond.a),
    is_imm_lda_cmp.out.to(is_imm.a, done_imm.b, needs_operand_any.a),
    is_abs_temp.out.to(is_abs.a),
    is_abs.out.to(is_abs_final.a),
    is_branch_1.out.to(is_branch_2.a),
    is_branch_2.out.to(is_branch_3.a),
    is_branch_3.out.to(is_branch_4.a),
    is_branch_4.out.to(is_branch.a),
    inp.flag_z.to(beq_cond.b, not_z.in),
    not_z.out.to(bne_cond.b),
    inp.flag_c.to(not_c.in, bcs_cond.b),
    not_c.out.to(bcc_cond.b),
    inp.flag_n.to(bmi_cond.b, not_n.in),
    not_n.out.to(bpl_cond.b),
    beq_cond.out.to(branch_cond_1.a),
    bne_cond.out.to(branch_cond_1.b),
    branch_cond_1.out.to(branch_cond_2.a),
    bcc_cond.out.to(branch_cond_2.b),
    branch_cond_2.out.to(branch_cond_3.a),
    bcs_cond.out.to(branch_cond_3.b),
    branch_cond_3.out.to(branch_cond_4.a),
    bmi_cond.out.to(branch_cond_4.b),
    branch_cond_4.out.to(branch_taken.a),
    bpl_cond.out.to(branch_taken.b),
    subcycle_reg.q.to(inc_subcycle.in, out.exec_subcycle, is_sub0.a, is_sub1.a, is_sub2.a, is_sub3.a, is_sub4.a, is_sub5.a),
    is_execute.eq.to(subcycle_increment.sel, exec_sub0.a, exec_sub1.a, exec_sub2.a, exec_sub3.a, exec_sub4.a, exec_sub5.a),
    zero.out.to(subcycle_increment.in0, is_sub0.b, out.write_y),
    inc_subcycle.out.to(subcycle_increment.in1),
    subcycle_increment.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we),
    one.out.to(is_sub1.b),
    two.out.to(is_sub2.b),
    three.out.to(is_sub3.b),
    four.out.to(is_sub4.b),
    five.out.to(is_sub5.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_temp.a, out.ir_load),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    is_sub0.eq.to(exec_sub0.b),
    is_sub1.eq.to(exec_sub1.b),
    is_sub2.eq.to(exec_sub2.b),
    is_sub3.eq.to(exec_sub3.b),
    is_sub4.eq.to(exec_sub4.b),
    is_sub5.eq.to(exec_sub5.b),
    exec_sub1.out.to(done_imm.a, done_pha.a, done_branch.a, pc_inc_exec_sub1.a, addr_hi_load_signal.a, pull_pc_lo_signal.a, branch_at_sub1.a, update_flags_lda.a, update_flags_cmp.a, write_a_imm.a),
    exec_sub3.out.to(done_zp.a, mem_read_abs_temp.a, mem_read_abs_x.a, mem_write_abs_temp.a, mem_write_abs_x.a, sp_dec_jsr_sub3.a, stack_write_jsr_lo.a, push_pc_lo_signal.a, pull_pc_hi_signal.a, write_a_zp.a),
    is_zp.out.to(done_zp.b, needs_operand_any.b),
    exec_sub4.out.to(done_abs.a, jsr_load_pc_signal.a, rts_load_pc_signal.a, write_a_abs_temp.a, write_a_abs_x.a),
    is_abs_final.out.to(done_abs.b, needs_operand_temp.b, needs_2nd_byte.a),
    exec_sub0.out.to(done_1cyc.a, pc_inc_exec_sub0.a, operand_load_signal.a, addr_lo_load_signal.a, sp_dec_pha.a, sp_inc_pla.a, sp_inc_rts_sub0.a, stack_write_pha.a, update_flags_inx.a, write_x_tax.a, write_x_inx.a),
    is_1cycle.out.to(done_1cyc.b),
    exec_sub2.out.to(done_pla.a, mem_read_zp.a, mem_write_zp.a, sp_dec_jsr_sub2.a, sp_inc_rts_sub2.a, stack_write_jsr_hi.a, use_stack_signal.a, push_pc_hi_signal.a, write_a_pla.a),
    exec_sub5.out.to(done_jsr.a, done_rts.a),
    is_branch.out.to(done_branch.b, needs_operand.b),
    done_imm.out.to(exec_done_temp1.a),
    done_zp.out.to(exec_done_temp1.b),
    exec_done_temp1.out.to(exec_done_temp2.a),
    done_abs.out.to(exec_done_temp2.b),
    exec_done_temp2.out.to(exec_done_temp3.a),
    done_1cyc.out.to(exec_done_temp3.b),
    exec_done_temp3.out.to(exec_done_temp4.a),
    done_pha.out.to(exec_done_temp4.b),
    exec_done_temp4.out.to(exec_done_temp5.a),
    done_pla.out.to(exec_done_temp5.b),
    exec_done_temp5.out.to(exec_done_temp6.a),
    done_jsr.out.to(exec_done_temp6.b),
    exec_done_temp6.out.to(exec_done_temp7.a),
    done_rts.out.to(exec_done_temp7.b),
    exec_done_temp7.out.to(exec_done.a),
    done_branch.out.to(exec_done.b),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    needs_operand_any.out.to(needs_operand_temp.a),
    needs_operand_temp.out.to(needs_operand_temp2.a),
    needs_operand_temp2.out.to(needs_operand.a),
    needs_operand.out.to(pc_inc_exec_sub0.b, operand_load_signal.b, addr_lo_load_signal.b),
    needs_2nd_byte.out.to(pc_inc_exec_sub1.b, addr_hi_load_signal.b),
    pc_inc_exec_sub0.out.to(pc_inc_temp.b),
    pc_inc_temp.out.to(pc_inc_signal.a),
    pc_inc_exec_sub1.out.to(pc_inc_signal.b),
    pc_inc_signal.out.to(out.pc_increment),
    operand_load_signal.out.to(out.operand_load),
    addr_lo_load_signal.out.to(out.addr_lo_load),
    addr_hi_load_signal.out.to(out.addr_hi_load),
    is_load.out.to(is_load_final.a),
    mem_read_abs_temp.out.to(mem_read_abs.a),
    mem_read_abs_x.out.to(mem_read_abs.b),
    mem_read_zp.out.to(mem_read_signal.a),
    mem_read_abs.out.to(mem_read_signal.b),
    mem_read_signal.out.to(out.mem_read),
    mem_write_abs_temp.out.to(mem_write_abs.a),
    mem_write_abs_x.out.to(mem_write_abs.b),
    mem_write_zp.out.to(mem_write_signal.a),
    mem_write_abs.out.to(mem_write_signal.b),
    mem_write_signal.out.to(out.mem_write),
    sp_dec_pha.out.to(sp_dec_temp.a),
    sp_dec_jsr_sub2.out.to(sp_dec_temp.b),
    sp_dec_temp.out.to(sp_dec_signal.a),
    sp_dec_jsr_sub3.out.to(sp_dec_signal.b),
    sp_dec_signal.out.to(out.sp_decrement),
    sp_inc_pla.out.to(sp_inc_temp.a),
    sp_inc_rts_sub0.out.to(sp_inc_temp.b),
    sp_inc_temp.out.to(sp_inc_signal.a),
    sp_inc_rts_sub2.out.to(sp_inc_signal.b),
    sp_inc_signal.out.to(out.sp_increment),
    stack_write_pha.out.to(stack_write_temp.a),
    stack_write_jsr_hi.out.to(stack_write_temp.b),
    stack_write_temp.out.to(stack_write_signal.a),
    stack_write_jsr_lo.out.to(stack_write_signal.b),
    stack_write_signal.out.to(out.stack_write),
    use_stack_signal.out.to(out.use_stack_data),
    jsr_load_pc_signal.out.to(out.jsr_load_pc),
    rts_load_pc_signal.out.to(out.rts_load_pc),
    push_pc_hi_signal.out.to(out.push_pc_hi),
    push_pc_lo_signal.out.to(out.push_pc_lo),
    pull_pc_lo_signal.out.to(out.pull_pc_lo),
    pull_pc_hi_signal.out.to(out.pull_pc_hi),
    branch_taken.out.to(branch_at_sub1.b),
    branch_at_sub1.out.to(out.branch_load_pc),
    update_flags_lda.out.to(update_flags_temp.a),
    update_flags_cmp.out.to(update_flags_temp.b),
    update_flags_temp.out.to(update_flags_signal.a),
    update_flags_inx.out.to(update_flags_signal.b),
    update_flags_signal.out.to(out.update_flags),
    write_a_abs_temp.out.to(write_a_abs.a),
    write_a_abs_x.out.to(write_a_abs.b),
    write_a_imm.out.to(write_a_temp.a),
    write_a_zp.out.to(write_a_temp.b),
    write_a_temp.out.to(write_a_temp2.a),
    write_a_abs.out.to(write_a_temp2.b),
    write_a_temp2.out.to(write_a_signal.a),
    write_a_pla.out.to(write_a_signal.b),
    write_a_signal.out.to(out.write_a),
    write_x_tax.out.to(write_x_signal.a),
    write_x_inx.out.to(write_x_signal.b),
    write_x_signal.out.to(out.write_x),
  ],
})

const Stage5CPU = circuit('Stage5CPU', {
  in: { reset: bit },
  out: { pc: bus(8), instruction: bus(8), operand: bus(8), address: bus(8), mem_data: bus(8), stack_data: bus(8), current_state: bus(8), subcycle: bus(8), reg_a: bus(8), reg_x: bus(8), reg_sp: bus(8), flag_n: bit, flag_z: bit, flag_c: bit, debug_update_flags: bit, debug_cmp_z_eq: bit, debug_z_source: bit, debug_is_cmp: bit },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, thirteen: Constant, fourteen: Constant, fifteen: Constant, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, byte_8: Constant, byte_9: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, byte_13: Constant, byte_14: Constant, byte_15: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, at_8: Comparator, at_9: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, mux13: Mux, mux14: Mux, mux15: Mux, ir: Register, operand_reg: Register, addr_lo_reg: Register, addr_hi_reg: Register, pc_lo_temp: Register, pc_hi_temp: Register, flags: FlagRegister, addr_with_x: Adder, control: Stage5Control, registers: RegisterFile, sp: StackPointer, sp_init: Constant, stack: StackMemory, pc_minus_1: Subtractor, one_const: Constant, stack_data_pha_or_lo: Mux, stack_data_final: Mux, effective_addr: Mux, effective_addr_final: Mux, memory: SimpleMemory, inc_x: Incrementer, rts_pc_plus1: Incrementer, branch_adder: Adder, result_a_imm_zp: Mux, result_a_abs: Mux, result_a_abs_x: Mux, result_a: Mux, result_x: Mux, cmp_sub: Subtractor, const_128: Constant, cmp_n: Comparator, n_gte: Or, cmp_z: Comparator, not_borrow: Not, lda_n: Comparator, lda_n_gte: Or, lda_z: Comparator, inx_n: Comparator, inx_n_gte: Or, inx_z: Comparator, n_cmp_or_lda: Mux, n_source: Mux, z_cmp_or_lda: Mux, z_source: Mux, pc_after_inc: Mux, pc_after_branch: Mux, pc_after_rts: Mux, pc_after_jsr: Mux },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, thirteen: { value: 13 }, fourteen: { value: 14 }, fifteen: { value: 15 }, byte_0: { value: 169 }, byte_1: { value: 5 }, byte_2: { value: 201 }, byte_3: { value: 5 }, byte_4: { value: 240 }, byte_5: { value: 2 }, byte_6: { value: 169 }, byte_7: { value: 255 }, byte_8: { value: 133 }, byte_9: { value: 32 }, byte_10: { value: 169 }, byte_11: { value: 66 }, byte_12: { value: 0 }, byte_13: { value: 0 }, byte_14: { value: 0 }, byte_15: { value: 0 }, sp_init: { value: 255 }, one_const: { value: 1 }, const_128: { value: 128 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, byte_13, byte_14, byte_15, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, at_8, at_9, at_10, at_11, at_12, at_13, at_14, at_15, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, mux13, mux14, mux15, ir, operand_reg, addr_lo_reg, addr_hi_reg, pc_lo_temp, pc_hi_temp, flags, addr_with_x, control, registers, sp, sp_init, stack, pc_minus_1, one_const, stack_data_pha_or_lo, stack_data_final, effective_addr, effective_addr_final, memory, inc_x, rts_pc_plus1, branch_adder, result_a_imm_zp, result_a_abs, result_a_abs_x, result_a, result_x, cmp_sub, const_128, cmp_n, n_gte, cmp_z, not_borrow, lda_n, lda_n_gte, lda_z, inx_n, inx_n_gte, inx_z, n_cmp_or_lda, n_source, z_cmp_or_lda, z_source, pc_after_inc, pc_after_branch, pc_after_rts, pc_after_jsr }) => [
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, at_8.a, at_9.a, at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, pc_minus_1.a, branch_adder.a, pc_after_inc.in0, out.pc),
    zero.out.to(at_0.b, addr_with_x.carry_in, pc_minus_1.borrow_in, stack_data_final.in1, branch_adder.carry_in, registers.data_y, cmp_sub.borrow_in, cmp_z.b, lda_z.b, inx_z.b, flags.update_v, flags.new_v),
    one.out.to(at_1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    eight.out.to(at_8.b),
    nine.out.to(at_9.b),
    ten.out.to(at_10.b),
    eleven.out.to(at_11.b),
    twelve.out.to(at_12.b),
    thirteen.out.to(at_13.b),
    fourteen.out.to(at_14.b),
    fifteen.out.to(at_15.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    at_8.eq.to(mux8.sel),
    mux7.out.to(mux8.in0),
    byte_8.out.to(mux8.in1),
    at_9.eq.to(mux9.sel),
    mux8.out.to(mux9.in0),
    byte_9.out.to(mux9.in1),
    at_10.eq.to(mux10.sel),
    mux9.out.to(mux10.in0),
    byte_10.out.to(mux10.in1),
    at_11.eq.to(mux11.sel),
    mux10.out.to(mux11.in0),
    byte_11.out.to(mux11.in1),
    at_12.eq.to(mux12.sel),
    mux11.out.to(mux12.in0),
    byte_12.out.to(mux12.in1),
    at_13.eq.to(mux13.sel),
    mux12.out.to(mux13.in0),
    byte_13.out.to(mux13.in1),
    at_14.eq.to(mux14.sel),
    mux13.out.to(mux14.in0),
    byte_14.out.to(mux14.in1),
    at_15.eq.to(mux15.sel),
    mux14.out.to(mux15.in0),
    byte_15.out.to(mux15.in1),
    mux15.out.to(ir.data, operand_reg.data, addr_lo_reg.data, addr_hi_reg.data),
    addr_lo_reg.q.to(addr_with_x.a, effective_addr.in0, pc_after_jsr.in1),
    inp.reset.to(control.reset, sp.load),
    ir.q.to(control.current_opcode, out.instruction),
    flags.flag_n.to(control.flag_n, out.flag_n),
    flags.flag_z.to(control.flag_z, out.flag_z),
    flags.flag_c.to(control.flag_c, out.flag_c),
    flags.flag_v.to(control.flag_v),
    control.write_a.to(registers.write_a),
    control.write_x.to(registers.write_x),
    control.write_y.to(registers.write_y),
    control.sp_decrement.to(sp.decrement),
    control.sp_increment.to(sp.increment),
    sp_init.out.to(sp.load_value),
    sp.sp.to(stack.addr, out.reg_sp),
    one_const.out.to(pc_minus_1.b),
    control.push_pc_lo.to(stack_data_pha_or_lo.sel),
    registers.reg_a.to(stack_data_pha_or_lo.in0, memory.data_in, result_x.in1, cmp_sub.a, out.reg_a),
    pc_minus_1.difference.to(stack_data_pha_or_lo.in1),
    control.push_pc_hi.to(stack_data_final.sel),
    stack_data_pha_or_lo.out.to(stack_data_final.in0),
    stack_data_final.out.to(stack.data_in),
    control.stack_write.to(stack.write_enable),
    stack.data_out.to(pc_lo_temp.data, pc_hi_temp.data, result_a.in1, out.stack_data),
    control.pull_pc_lo.to(pc_lo_temp.we),
    control.pull_pc_hi.to(pc_hi_temp.we),
    control.is_lda_abs_x.to(effective_addr.sel, result_a_abs_x.sel),
    addr_with_x.sum.to(effective_addr.in1, effective_addr_final.in1),
    control.is_sta_abs_x.to(effective_addr_final.sel),
    effective_addr.out.to(effective_addr_final.in0),
    registers.reg_x.to(addr_with_x.b, inc_x.in, out.reg_x),
    effective_addr_final.out.to(memory.addr, out.address),
    control.mem_write.to(memory.write_enable),
    pc_lo_temp.q.to(rts_pc_plus1.in),
    operand_reg.q.to(branch_adder.b, result_a_imm_zp.in0, cmp_sub.b, lda_n.a, lda_z.a, out.operand),
    control.is_lda_zp.to(result_a_imm_zp.sel),
    memory.data_out.to(result_a_imm_zp.in1, result_a_abs.in1, result_a_abs_x.in1, out.mem_data),
    control.is_lda_abs.to(result_a_abs.sel),
    result_a_imm_zp.out.to(result_a_abs.in0),
    result_a_abs.out.to(result_a_abs_x.in0),
    control.use_stack_data.to(result_a.sel),
    result_a_abs_x.out.to(result_a.in0),
    result_a.out.to(registers.data_a),
    control.is_tax.to(result_x.sel),
    inc_x.out.to(result_x.in0, inx_n.a, inx_z.a),
    result_x.out.to(registers.data_x),
    cmp_sub.difference.to(cmp_n.a, cmp_z.a),
    const_128.out.to(cmp_n.b, lda_n.b, inx_n.b),
    cmp_n.gt.to(n_gte.a),
    cmp_n.eq.to(n_gte.b),
    cmp_sub.borrow_out.to(not_borrow.in),
    lda_n.gt.to(lda_n_gte.a),
    lda_n.eq.to(lda_n_gte.b),
    inx_n.gt.to(inx_n_gte.a),
    inx_n.eq.to(inx_n_gte.b),
    control.is_cmp_imm.to(n_cmp_or_lda.sel, z_cmp_or_lda.sel, out.debug_is_cmp),
    lda_n_gte.out.to(n_cmp_or_lda.in0),
    n_gte.out.to(n_cmp_or_lda.in1),
    control.is_inx.to(n_source.sel, z_source.sel),
    n_cmp_or_lda.out.to(n_source.in0),
    inx_n_gte.out.to(n_source.in1),
    lda_z.eq.to(z_cmp_or_lda.in0),
    cmp_z.eq.to(z_cmp_or_lda.in1, out.debug_cmp_z_eq),
    z_cmp_or_lda.out.to(z_source.in0),
    inx_z.eq.to(z_source.in1),
    control.update_flags.to(flags.update_n, flags.update_z, flags.update_c, out.debug_update_flags),
    n_source.out.to(flags.new_n),
    z_source.out.to(flags.new_z, out.debug_z_source),
    not_borrow.out.to(flags.new_c),
    control.pc_increment.to(pc_after_inc.sel),
    pc_inc.out.to(pc_after_inc.in1),
    control.branch_load_pc.to(pc_after_branch.sel),
    pc_after_inc.out.to(pc_after_branch.in0),
    branch_adder.sum.to(pc_after_branch.in1),
    control.rts_load_pc.to(pc_after_rts.sel),
    pc_after_branch.out.to(pc_after_rts.in0),
    rts_pc_plus1.out.to(pc_after_rts.in1),
    control.jsr_load_pc.to(pc_after_jsr.sel),
    pc_after_rts.out.to(pc_after_jsr.in0),
    pc_after_jsr.out.to(pc_reg.data),
    always_on.out.to(pc_reg.we),
    control.ir_load.to(ir.we),
    control.operand_load.to(operand_reg.we),
    control.addr_lo_load.to(addr_lo_reg.we),
    control.addr_hi_load.to(addr_hi_reg.we),
    control.current_state.to(out.current_state),
    control.exec_subcycle.to(out.subcycle),
  ],
})

const Stage5Test = circuit('Stage5Test', {
  nodes: { cpu: Stage5CPU, reset_input: Input, d_pc: HexDisplay, d_instruction: HexDisplay, d_operand: HexDisplay, d_address: HexDisplay, d_mem_data: HexDisplay, d_stack_data: HexDisplay, d_state: HexDisplay, d_subcycle: HexDisplay, d_a: HexDisplay, d_x: HexDisplay, d_sp: HexDisplay, d_n: HexDisplay, d_z: HexDisplay, d_c: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_instruction, d_operand, d_address, d_mem_data, d_stack_data, d_state, d_subcycle, d_a, d_x, d_sp, d_n, d_z, d_c }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.instruction.to(d_instruction.in),
    cpu.operand.to(d_operand.in),
    cpu.address.to(d_address.in),
    cpu.mem_data.to(d_mem_data.in),
    cpu.stack_data.to(d_stack_data.in),
    cpu.current_state.to(d_state.in),
    cpu.subcycle.to(d_subcycle.in),
    cpu.reg_a.to(d_a.in),
    cpu.reg_x.to(d_x.in),
    cpu.reg_sp.to(d_sp.in),
    cpu.flag_n.to(d_n.in),
    cpu.flag_z.to(d_z.in),
    cpu.flag_c.to(d_c.in),
  ],
})
