// Auto-generated from DSL

const Part2TestCPU = component('Part2TestCPU', {
  in: { reset: bit },
  out: { pc: bus(8), reg_a: bus(8), reg_x: bus(8), reg_y: bus(8), flag_n: bit, flag_z: bit, flag_c: bit },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, thirteen: Constant, fourteen: Constant, fifteen: Constant, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, byte_8: Constant, byte_9: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, byte_13: Constant, byte_14: Constant, byte_15: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, at_8: Comparator, at_9: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, mux13: Mux, mux14: Mux, mux15: Mux, ir: Register, operand_reg: Register, regA: Register, regX: Register, regY: Register, flag_n_reg: Register, flag_z_reg: Register, flag_c_reg: Register, state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDY_IMM: Constant, TYA: Constant, TAX: Constant, LDA_IMM: Constant, TXA: Constant, CPX_IMM: Constant, CPY_IMM: Constant, NOP: Constant, cmp_ldy_imm: Comparator, cmp_tya: Comparator, cmp_tax: Comparator, cmp_lda_imm: Comparator, cmp_txa: Comparator, cmp_cpx_imm: Comparator, cmp_cpy_imm: Comparator, cmp_nop: Comparator, is_sub0: Comparator, is_sub1: Comparator, inc_subcycle: Incrementer, subcycle_next: Mux, exec_sub0: And, exec_sub1: And, is_imm: Or, is_imm_2: Or, is_imm_any: Or, is_1cyc: Or, is_1cyc_2: Or, is_1cycle: Or, done_imm: And, done_1cyc: And, exec_done: Or, next_from_fetch: Mux, next_from_decode: Mux, next_from_execute: Mux, next_state: Mux, needs_operand: And, pc_inc_fetch: Or, pc_next: Mux, a_from_lda: Mux, a_from_txa: Mux, a_data: Mux, write_a_lda: And, write_a_txa: And, write_a_tya: And, write_a_1: Or, write_a: Or, write_x_tax: And, write_y_ldy: And, cpx_sub: Subtractor, cpy_sub: Subtractor, const_128: Constant, flag_val_cpx: Mux, flag_val: Mux, n_check: Comparator, n_val: Or, z_check: Comparator, not_borrow_cpx: Not, not_borrow_cpy: Not, c_val: Mux, update_ldy: And, update_txa: And, update_tya: And, update_cpx: And, update_cpy: And, update_nz_1: Or, update_nz_2: Or, update_nz_3: Or, update_nz: Or, update_c: Or },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, thirteen: { value: 13 }, fourteen: { value: 14 }, fifteen: { value: 15 }, byte_0: { value: 160 }, byte_1: { value: 66 }, byte_2: { value: 152 }, byte_3: { value: 170 }, byte_4: { value: 169 }, byte_5: { value: 0 }, byte_6: { value: 138 }, byte_7: { value: 224 }, byte_8: { value: 66 }, byte_9: { value: 192 }, byte_10: { value: 66 }, byte_11: { value: 224 }, byte_12: { value: 80 }, byte_13: { value: 234 }, byte_14: { value: 234 }, byte_15: { value: 234 }, flag_n_reg: { initial: 0 }, flag_z_reg: { initial: 0 }, flag_c_reg: { initial: 0 }, STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDY_IMM: { value: 160 }, TYA: { value: 152 }, TAX: { value: 170 }, LDA_IMM: { value: 169 }, TXA: { value: 138 }, CPX_IMM: { value: 224 }, CPY_IMM: { value: 192 }, NOP: { value: 234 }, const_128: { value: 128 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, byte_13, byte_14, byte_15, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, at_8, at_9, at_10, at_11, at_12, at_13, at_14, at_15, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, mux13, mux14, mux15, ir, operand_reg, regA, regX, regY, flag_n_reg, flag_z_reg, flag_c_reg, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDY_IMM, TYA, TAX, LDA_IMM, TXA, CPX_IMM, CPY_IMM, NOP, cmp_ldy_imm, cmp_tya, cmp_tax, cmp_lda_imm, cmp_txa, cmp_cpx_imm, cmp_cpy_imm, cmp_nop, is_sub0, is_sub1, inc_subcycle, subcycle_next, exec_sub0, exec_sub1, is_imm, is_imm_2, is_imm_any, is_1cyc, is_1cyc_2, is_1cycle, done_imm, done_1cyc, exec_done, next_from_fetch, next_from_decode, next_from_execute, next_state, needs_operand, pc_inc_fetch, pc_next, a_from_lda, a_from_txa, a_data, write_a_lda, write_a_txa, write_a_tya, write_a_1, write_a, write_x_tax, write_y_ldy, cpx_sub, cpy_sub, const_128, flag_val_cpx, flag_val, n_check, n_val, z_check, not_borrow_cpx, not_borrow_cpy, c_val, update_ldy, update_txa, update_tya, update_cpx, update_cpy, update_nz_1, update_nz_2, update_nz_3, update_nz, update_c }) => [
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, at_8.a, at_9.a, at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, is_sub0.b, subcycle_next.in0, cpx_sub.borrow_in, cpy_sub.borrow_in, z_check.b),
    one.out.to(at_1.b, is_sub1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    eight.out.to(at_8.b),
    nine.out.to(at_9.b),
    ten.out.to(at_10.b),
    eleven.out.to(at_11.b),
    twelve.out.to(at_12.b),
    thirteen.out.to(at_13.b),
    fourteen.out.to(at_14.b),
    fifteen.out.to(at_15.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    at_8.eq.to(mux8.sel),
    mux7.out.to(mux8.in0),
    byte_8.out.to(mux8.in1),
    at_9.eq.to(mux9.sel),
    mux8.out.to(mux9.in0),
    byte_9.out.to(mux9.in1),
    at_10.eq.to(mux10.sel),
    mux9.out.to(mux10.in0),
    byte_10.out.to(mux10.in1),
    at_11.eq.to(mux11.sel),
    mux10.out.to(mux11.in0),
    byte_11.out.to(mux11.in1),
    at_12.eq.to(mux12.sel),
    mux11.out.to(mux12.in0),
    byte_12.out.to(mux12.in1),
    at_13.eq.to(mux13.sel),
    mux12.out.to(mux13.in0),
    byte_13.out.to(mux13.in1),
    at_14.eq.to(mux14.sel),
    mux13.out.to(mux14.in0),
    byte_14.out.to(mux14.in1),
    at_15.eq.to(mux15.sel),
    mux14.out.to(mux15.in0),
    byte_15.out.to(mux15.in1),
    mux15.out.to(ir.data, operand_reg.data),
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    ir.q.to(cmp_ldy_imm.a, cmp_tya.a, cmp_tax.a, cmp_lda_imm.a, cmp_txa.a, cmp_cpx_imm.a, cmp_cpy_imm.a, cmp_nop.a),
    LDY_IMM.out.to(cmp_ldy_imm.b),
    TYA.out.to(cmp_tya.b),
    TAX.out.to(cmp_tax.b),
    LDA_IMM.out.to(cmp_lda_imm.b),
    TXA.out.to(cmp_txa.b),
    CPX_IMM.out.to(cmp_cpx_imm.b),
    CPY_IMM.out.to(cmp_cpy_imm.b),
    NOP.out.to(cmp_nop.b),
    subcycle_reg.q.to(is_sub0.a, is_sub1.a, inc_subcycle.in),
    is_execute.eq.to(subcycle_next.sel, exec_sub0.a, exec_sub1.a),
    inc_subcycle.out.to(subcycle_next.in1),
    subcycle_next.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we, pc_reg.we),
    is_sub0.eq.to(exec_sub0.b),
    is_sub1.eq.to(exec_sub1.b),
    cmp_ldy_imm.eq.to(is_imm.a, write_y_ldy.b, update_ldy.b),
    cmp_lda_imm.eq.to(is_imm.b, a_from_lda.sel, write_a_lda.b),
    is_imm.out.to(is_imm_2.a),
    cmp_cpx_imm.eq.to(is_imm_2.b, flag_val_cpx.sel, update_cpx.b),
    is_imm_2.out.to(is_imm_any.a),
    cmp_cpy_imm.eq.to(is_imm_any.b, flag_val.sel, c_val.sel, update_cpy.b),
    cmp_tya.eq.to(is_1cyc.a, a_data.sel, write_a_tya.b, update_tya.b),
    cmp_tax.eq.to(is_1cyc.b, write_x_tax.b),
    is_1cyc.out.to(is_1cyc_2.a),
    cmp_txa.eq.to(is_1cyc_2.b, a_from_txa.sel, write_a_txa.b, update_txa.b),
    is_1cyc_2.out.to(is_1cycle.a),
    cmp_nop.eq.to(is_1cycle.b),
    exec_sub1.out.to(done_imm.a, write_a_lda.a, write_y_ldy.a, update_ldy.a, update_cpx.a, update_cpy.a),
    is_imm_any.out.to(done_imm.b, needs_operand.b),
    exec_sub0.out.to(done_1cyc.a, needs_operand.a, write_a_txa.a, write_a_tya.a, write_x_tax.a, update_txa.a, update_tya.a),
    is_1cycle.out.to(done_1cyc.b),
    done_imm.out.to(exec_done.a),
    done_1cyc.out.to(exec_done.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_fetch.a, ir.we),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    needs_operand.out.to(pc_inc_fetch.b, operand_reg.we),
    pc_inc_fetch.out.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    regA.q.to(a_from_lda.in0, regX.data, out.reg_a),
    operand_reg.q.to(a_from_lda.in1, regY.data, cpx_sub.b, cpy_sub.b),
    a_from_lda.out.to(a_from_txa.in0),
    regX.q.to(a_from_txa.in1, cpx_sub.a, out.reg_x),
    a_from_txa.out.to(a_data.in0),
    regY.q.to(a_data.in1, cpy_sub.a, out.reg_y),
    a_data.out.to(regA.data, flag_val_cpx.in0),
    write_a_lda.out.to(write_a_1.a),
    write_a_txa.out.to(write_a_1.b),
    write_a_1.out.to(write_a.a),
    write_a_tya.out.to(write_a.b),
    write_a.out.to(regA.we),
    write_x_tax.out.to(regX.we),
    write_y_ldy.out.to(regY.we),
    cpx_sub.difference.to(flag_val_cpx.in1),
    flag_val_cpx.out.to(flag_val.in0),
    cpy_sub.difference.to(flag_val.in1),
    flag_val.out.to(n_check.a, z_check.a),
    const_128.out.to(n_check.b),
    n_check.gt.to(n_val.a),
    n_check.eq.to(n_val.b),
    cpx_sub.borrow_out.to(not_borrow_cpx.in),
    cpy_sub.borrow_out.to(not_borrow_cpy.in),
    not_borrow_cpx.out.to(c_val.in0),
    not_borrow_cpy.out.to(c_val.in1),
    update_ldy.out.to(update_nz_1.a),
    update_txa.out.to(update_nz_1.b),
    update_nz_1.out.to(update_nz_2.a),
    update_tya.out.to(update_nz_2.b),
    update_nz_2.out.to(update_nz_3.a),
    update_cpx.out.to(update_nz_3.b, update_c.a),
    update_nz_3.out.to(update_nz.a),
    update_cpy.out.to(update_nz.b, update_c.b),
    update_nz.out.to(flag_n_reg.we, flag_z_reg.we),
    update_c.out.to(flag_c_reg.we),
    n_val.out.to(flag_n_reg.data),
    z_check.eq.to(flag_z_reg.data),
    c_val.out.to(flag_c_reg.data),
    flag_n_reg.q.to(out.flag_n),
    flag_z_reg.q.to(out.flag_z),
    flag_c_reg.q.to(out.flag_c),
  ],
})

const Part2Test = component('Part2Test', {
  nodes: { cpu: Part2TestCPU, reset_input: Input, d_pc: HexDisplay, d_a: HexDisplay, d_x: HexDisplay, d_y: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_a, d_x, d_y }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.reg_a.to(d_a.in),
    cpu.reg_x.to(d_x.in),
    cpu.reg_y.to(d_y.in),
  ],
})
