// Auto-generated from DSL

const Part4TestCPU = circuit('Part4TestCPU', {
  in: { reset: bit },
  out: { pc: bus(8), reg_a: bus(8), reg_x: bus(8), reg_y: bus(8), flag_n: bit, flag_z: bit, flag_c: bit },
  nodes: { pc_reg: Register, always_on: Constant, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, thirteen: Constant, fourteen: Constant, fifteen: Constant, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, byte_8: Constant, byte_9: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, byte_13: Constant, byte_14: Constant, byte_15: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, at_8: Comparator, at_9: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, mux13: Mux, mux14: Mux, mux15: Mux, ir: Register, operand_reg: Register, regA: Register, regX: Register, regY: Register, flag_n_reg: Register, flag_z_reg: Register, flag_c_reg: Register, state_reg: Register, subcycle_reg: Register, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, LDX_IMM: Constant, LDA_IMM: Constant, SEC: Constant, SBC_IMM: Constant, NOP: Constant, cmp_ldx_imm: Comparator, cmp_lda_imm: Comparator, cmp_sec: Comparator, cmp_sbc_imm: Comparator, cmp_nop: Comparator, is_sub0: Comparator, is_sub1: Comparator, inc_subcycle: Incrementer, subcycle_next: Mux, exec_sub0: And, exec_sub1: And, is_imm_1: Or, is_imm: Or, is_1cycle: Or, done_imm: And, done_1cyc: And, exec_done: Or, next_from_fetch: Mux, next_from_decode: Mux, next_from_execute: Mux, next_state: Mux, pc_inc_fetch: Or, needs_operand: And, pc_inc_imm: Or, pc_next: Mux, not_carry: Not, sbc_sub: Subtractor, a_from_lda: Mux, a_data: Mux, is_lda_or_sbc: Or, write_a: And, write_x: And, const_128: Constant, flag_val: Mux, n_check: Comparator, n_val: Or, z_check: Comparator, not_borrow: Not, c_from_sbc: Mux, c_from_sec: Mux, update_imm: And, update_sec: And, update_flags: Or },
  nodeArgs: { always_on: { value: 1 }, zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, thirteen: { value: 13 }, fourteen: { value: 14 }, fifteen: { value: 15 }, byte_0: { value: 162 }, byte_1: { value: 66 }, byte_2: { value: 169 }, byte_3: { value: 80 }, byte_4: { value: 56 }, byte_5: { value: 233 }, byte_6: { value: 16 }, byte_7: { value: 233 }, byte_8: { value: 48 }, byte_9: { value: 233 }, byte_10: { value: 16 }, byte_11: { value: 169 }, byte_12: { value: 5 }, byte_13: { value: 233 }, byte_14: { value: 16 }, byte_15: { value: 234 }, flag_n_reg: { initial: 0 }, flag_z_reg: { initial: 0 }, flag_c_reg: { initial: 0 }, STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, LDX_IMM: { value: 162 }, LDA_IMM: { value: 169 }, SEC: { value: 56 }, SBC_IMM: { value: 233 }, NOP: { value: 234 }, const_128: { value: 128 } },
  connect: ({ in: inp, out, pc_reg, always_on, pc_inc, zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, byte_13, byte_14, byte_15, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, at_8, at_9, at_10, at_11, at_12, at_13, at_14, at_15, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, mux13, mux14, mux15, ir, operand_reg, regA, regX, regY, flag_n_reg, flag_z_reg, flag_c_reg, state_reg, subcycle_reg, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, LDX_IMM, LDA_IMM, SEC, SBC_IMM, NOP, cmp_ldx_imm, cmp_lda_imm, cmp_sec, cmp_sbc_imm, cmp_nop, is_sub0, is_sub1, inc_subcycle, subcycle_next, exec_sub0, exec_sub1, is_imm_1, is_imm, is_1cycle, done_imm, done_1cyc, exec_done, next_from_fetch, next_from_decode, next_from_execute, next_state, pc_inc_fetch, needs_operand, pc_inc_imm, pc_next, not_carry, sbc_sub, a_from_lda, a_data, is_lda_or_sbc, write_a, write_x, const_128, flag_val, n_check, n_val, z_check, not_borrow, c_from_sbc, c_from_sec, update_imm, update_sec, update_flags }) => [
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, at_8.a, at_9.a, at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, is_sub0.b, subcycle_next.in0, z_check.b),
    one.out.to(at_1.b, is_sub1.b, c_from_sec.in1),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    eight.out.to(at_8.b),
    nine.out.to(at_9.b),
    ten.out.to(at_10.b),
    eleven.out.to(at_11.b),
    twelve.out.to(at_12.b),
    thirteen.out.to(at_13.b),
    fourteen.out.to(at_14.b),
    fifteen.out.to(at_15.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    at_8.eq.to(mux8.sel),
    mux7.out.to(mux8.in0),
    byte_8.out.to(mux8.in1),
    at_9.eq.to(mux9.sel),
    mux8.out.to(mux9.in0),
    byte_9.out.to(mux9.in1),
    at_10.eq.to(mux10.sel),
    mux9.out.to(mux10.in0),
    byte_10.out.to(mux10.in1),
    at_11.eq.to(mux11.sel),
    mux10.out.to(mux11.in0),
    byte_11.out.to(mux11.in1),
    at_12.eq.to(mux12.sel),
    mux11.out.to(mux12.in0),
    byte_12.out.to(mux12.in1),
    at_13.eq.to(mux13.sel),
    mux12.out.to(mux13.in0),
    byte_13.out.to(mux13.in1),
    at_14.eq.to(mux14.sel),
    mux13.out.to(mux14.in0),
    byte_14.out.to(mux14.in1),
    at_15.eq.to(mux15.sel),
    mux14.out.to(mux15.in0),
    byte_15.out.to(mux15.in1),
    mux15.out.to(ir.data, operand_reg.data),
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    ir.q.to(cmp_ldx_imm.a, cmp_lda_imm.a, cmp_sec.a, cmp_sbc_imm.a, cmp_nop.a),
    LDX_IMM.out.to(cmp_ldx_imm.b),
    LDA_IMM.out.to(cmp_lda_imm.b),
    SEC.out.to(cmp_sec.b),
    SBC_IMM.out.to(cmp_sbc_imm.b),
    NOP.out.to(cmp_nop.b),
    subcycle_reg.q.to(is_sub0.a, is_sub1.a, inc_subcycle.in),
    is_execute.eq.to(subcycle_next.sel, exec_sub0.a, exec_sub1.a),
    inc_subcycle.out.to(subcycle_next.in1),
    subcycle_next.out.to(subcycle_reg.data),
    always_on.out.to(subcycle_reg.we, state_reg.we, pc_reg.we),
    is_sub0.eq.to(exec_sub0.b),
    is_sub1.eq.to(exec_sub1.b),
    cmp_ldx_imm.eq.to(is_imm_1.a, write_x.b, flag_val.sel),
    cmp_lda_imm.eq.to(is_imm_1.b, a_from_lda.sel, is_lda_or_sbc.a),
    is_imm_1.out.to(is_imm.a),
    cmp_sbc_imm.eq.to(is_imm.b, a_data.sel, is_lda_or_sbc.b, c_from_sbc.sel),
    cmp_sec.eq.to(is_1cycle.a, c_from_sec.sel, update_sec.b),
    cmp_nop.eq.to(is_1cycle.b),
    exec_sub1.out.to(done_imm.a, write_a.a, write_x.a, update_imm.a),
    is_imm.out.to(done_imm.b, needs_operand.b, update_imm.b),
    exec_sub0.out.to(done_1cyc.a, pc_inc_fetch.b, needs_operand.a, update_sec.a),
    is_1cycle.out.to(done_1cyc.b),
    done_imm.out.to(exec_done.a),
    done_1cyc.out.to(exec_done.b),
    is_fetch.eq.to(next_from_fetch.sel, pc_inc_fetch.a, pc_inc_imm.a, ir.we),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    needs_operand.out.to(pc_inc_imm.b, operand_reg.we),
    pc_inc_imm.out.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    flag_c_reg.q.to(not_carry.in, c_from_sbc.in0, out.flag_c),
    regA.q.to(sbc_sub.a, a_from_lda.in0, out.reg_a),
    operand_reg.q.to(sbc_sub.b, a_from_lda.in1, regX.data, flag_val.in1),
    not_carry.out.to(sbc_sub.borrow_in),
    a_from_lda.out.to(a_data.in0),
    sbc_sub.difference.to(a_data.in1),
    a_data.out.to(regA.data, flag_val.in0),
    is_lda_or_sbc.out.to(write_a.b),
    write_a.out.to(regA.we),
    write_x.out.to(regX.we),
    flag_val.out.to(n_check.a, z_check.a),
    const_128.out.to(n_check.b),
    n_check.gt.to(n_val.a),
    n_check.eq.to(n_val.b),
    sbc_sub.borrow_out.to(not_borrow.in),
    not_borrow.out.to(c_from_sbc.in1),
    c_from_sbc.out.to(c_from_sec.in0),
    update_imm.out.to(update_flags.a),
    update_sec.out.to(update_flags.b),
    update_flags.out.to(flag_n_reg.we, flag_z_reg.we, flag_c_reg.we),
    n_val.out.to(flag_n_reg.data),
    z_check.eq.to(flag_z_reg.data),
    c_from_sec.out.to(flag_c_reg.data),
    regX.q.to(out.reg_x),
    regY.q.to(out.reg_y),
    flag_n_reg.q.to(out.flag_n),
    flag_z_reg.q.to(out.flag_z),
  ],
})

const Part4Test = circuit('Part4Test', {
  nodes: { cpu: Part4TestCPU, reset_input: Input, d_pc: HexDisplay, d_a: HexDisplay, d_x: HexDisplay },
  connect: ({ in: inp, out, cpu, reset_input, d_pc, d_a, d_x }) => [
    reset_input.out.to(cpu.reset),
    cpu.pc.to(d_pc.in),
    cpu.reg_a.to(d_a.in),
    cpu.reg_x.to(d_x.in),
  ],
})
