// Auto-generated from DSL

const SimpleMemory = component('SimpleMemory', {
  in: { addr: bus(8), data_in: bus(8), write_enable: bit },
  out: { data_out: bus(8) },
  nodes: { zero: Constant, addr_10: Constant, addr_11: Constant, addr_12: Constant, addr_13: Constant, addr_14: Constant, addr_15: Constant, addr_20: Constant, addr_21: Constant, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, at_20: Comparator, at_21: Comparator, mem_10: Register, mem_11: Register, mem_12: Register, mem_13: Register, mem_14: Register, mem_15: Register, mem_20: Register, mem_21: Register, we_10: And, we_11: And, we_12: And, we_13: And, we_14: And, we_15: And, we_20: And, we_21: And, out_mux1: Mux, out_mux2: Mux, out_mux3: Mux, out_mux4: Mux, out_mux5: Mux, out_mux6: Mux, out_mux7: Mux },
  nodeArgs: { zero: { value: 0 }, addr_10: { value: 16 }, addr_11: { value: 17 }, addr_12: { value: 18 }, addr_13: { value: 19 }, addr_14: { value: 20 }, addr_15: { value: 21 }, addr_20: { value: 32 }, addr_21: { value: 33 } },
  connect: ({ in: inp, out, zero, addr_10, addr_11, addr_12, addr_13, addr_14, addr_15, addr_20, addr_21, at_10, at_11, at_12, at_13, at_14, at_15, at_20, at_21, mem_10, mem_11, mem_12, mem_13, mem_14, mem_15, mem_20, mem_21, we_10, we_11, we_12, we_13, we_14, we_15, we_20, we_21, out_mux1, out_mux2, out_mux3, out_mux4, out_mux5, out_mux6, out_mux7 }) => [
    inp.addr.to(at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, at_20.a, at_21.a),
    addr_10.out.to(at_10.b),
    addr_11.out.to(at_11.b),
    addr_12.out.to(at_12.b),
    addr_13.out.to(at_13.b),
    addr_14.out.to(at_14.b),
    addr_15.out.to(at_15.b),
    addr_20.out.to(at_20.b),
    addr_21.out.to(at_21.b),
    inp.data_in.to(mem_10.data, mem_11.data, mem_12.data, mem_13.data, mem_14.data, mem_15.data, mem_20.data, mem_21.data),
    inp.write_enable.to(we_10.a, we_11.a, we_12.a, we_13.a, we_14.a, we_15.a, we_20.a, we_21.a),
    at_10.eq.to(we_10.b),
    we_10.out.to(mem_10.we),
    at_11.eq.to(we_11.b, out_mux1.sel),
    we_11.out.to(mem_11.we),
    at_12.eq.to(we_12.b, out_mux2.sel),
    we_12.out.to(mem_12.we),
    at_13.eq.to(we_13.b, out_mux3.sel),
    we_13.out.to(mem_13.we),
    at_14.eq.to(we_14.b, out_mux4.sel),
    we_14.out.to(mem_14.we),
    at_15.eq.to(we_15.b, out_mux5.sel),
    we_15.out.to(mem_15.we),
    at_20.eq.to(we_20.b, out_mux6.sel),
    we_20.out.to(mem_20.we),
    at_21.eq.to(we_21.b, out_mux7.sel),
    we_21.out.to(mem_21.we),
    mem_10.q.to(out_mux1.in0),
    mem_11.q.to(out_mux1.in1),
    out_mux1.out.to(out_mux2.in0),
    mem_12.q.to(out_mux2.in1),
    out_mux2.out.to(out_mux3.in0),
    mem_13.q.to(out_mux3.in1),
    out_mux3.out.to(out_mux4.in0),
    mem_14.q.to(out_mux4.in1),
    out_mux4.out.to(out_mux5.in0),
    mem_15.q.to(out_mux5.in1),
    out_mux5.out.to(out_mux6.in0),
    mem_20.q.to(out_mux6.in1),
    out_mux6.out.to(out_mux7.in0),
    mem_21.q.to(out_mux7.in1),
    out_mux7.out.to(out.data_out),
  ],
})

const FlagRegister = component('FlagRegister', {
  in: { new_n: bit, new_z: bit, new_c: bit, new_v: bit, update_n: bit, update_z: bit, update_c: bit, update_v: bit },
  out: { flag_n: bit, flag_z: bit, flag_c: bit, flag_v: bit },
  nodes: { reg_n: Register, reg_z: Register, reg_c: Register, reg_v: Register },
  connect: ({ in: inp, out, reg_n, reg_z, reg_c, reg_v }) => [
    inp.new_n.to(reg_n.data),
    inp.new_z.to(reg_z.data),
    inp.new_c.to(reg_c.data),
    inp.new_v.to(reg_v.data),
    inp.update_n.to(reg_n.we),
    inp.update_z.to(reg_z.we),
    inp.update_c.to(reg_c.we),
    inp.update_v.to(reg_v.we),
    reg_n.q.to(out.flag_n),
    reg_z.q.to(out.flag_z),
    reg_c.q.to(out.flag_c),
    reg_v.q.to(out.flag_v),
  ],
})

const RegisterFile = component('RegisterFile', {
  in: { data_a: bus(8), data_x: bus(8), data_y: bus(8), write_a: bit, write_x: bit, write_y: bit },
  out: { reg_a: bus(8), reg_x: bus(8), reg_y: bus(8) },
  nodes: { regA: Register, regX: Register, regY: Register },
  connect: ({ in: inp, out, regA, regX, regY }) => [
    inp.data_a.to(regA.data),
    inp.data_x.to(regX.data),
    inp.data_y.to(regY.data),
    inp.write_a.to(regA.we),
    inp.write_x.to(regX.we),
    inp.write_y.to(regY.we),
    regA.q.to(out.reg_a),
    regX.q.to(out.reg_x),
    regY.q.to(out.reg_y),
  ],
})

const Part5Control = component('Part5Control', {
  in: { current_state: bus(8), current_opcode: bus(8), subcycle: bus(8), flag_c: bit },
  out: { next_state: bus(8), next_subcycle: bus(8), pc_increment: bit, ir_load: bit, operand_load: bit, addr_lo_load: bit, write_a: bit, write_x: bit, write_y: bit, mem_write: bit, update_flags: bit, update_c_only: bit, set_c: bit, clear_c: bit, is_adc_imm: bit, is_stx_zp: bit, is_sty_zp: bit, use_x_for_mem: bit, use_y_for_mem: bit },
  nodes: { STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, SUB0: Constant, SUB1: Constant, SUB2: Constant, LDA_IMM: Constant, LDX_IMM: Constant, LDY_IMM: Constant, ADC_IMM: Constant, STX_ZP: Constant, STY_ZP: Constant, SEC: Constant, CLC: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, at_sub0: Comparator, at_sub1: Comparator, at_sub2: Comparator, exec_sub0: And, exec_sub1: And, exec_sub2: And, cmp_lda_imm: Comparator, cmp_ldx_imm: Comparator, cmp_ldy_imm: Comparator, cmp_adc_imm: Comparator, cmp_stx_zp: Comparator, cmp_sty_zp: Comparator, cmp_sec: Comparator, cmp_clc: Comparator, is_imm_1: Or, is_imm_2: Or, is_imm: Or, is_zp: Or, is_1cycle: Or, needs_operand: Or, one: Constant, zero: Constant, go_to_decode: Mux, go_to_execute: Mux, done_1cycle: And, done_imm: And, done_zp: And, done_temp: Or, done: Or, go_to_fetch: Mux, inc_subcycle: Incrementer, reset_subcycle: Mux, keep_subcycle: Mux, pc_inc_fetch: And, pc_inc_exec: And, pc_inc_signal: Or, operand_load_signal: And, is_write_a: Or, write_a_signal: And, write_x_signal: And, write_y_signal: And, mem_write_signal: And, use_x_signal: And, use_y_signal: And, is_update_flags_1: Or, is_update_flags_2: Or, is_update_flags: Or, update_flags_signal: And, is_sec_clc: Or, update_c_only_signal: And, set_c_signal: And, clear_c_signal: And },
  nodeArgs: { STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, SUB0: { value: 0 }, SUB1: { value: 1 }, SUB2: { value: 2 }, LDA_IMM: { value: 169 }, LDX_IMM: { value: 162 }, LDY_IMM: { value: 160 }, ADC_IMM: { value: 105 }, STX_ZP: { value: 134 }, STY_ZP: { value: 132 }, SEC: { value: 56 }, CLC: { value: 24 }, one: { value: 1 }, zero: { value: 0 } },
  connect: ({ in: inp, out, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, SUB0, SUB1, SUB2, LDA_IMM, LDX_IMM, LDY_IMM, ADC_IMM, STX_ZP, STY_ZP, SEC, CLC, is_fetch, is_decode, is_execute, at_sub0, at_sub1, at_sub2, exec_sub0, exec_sub1, exec_sub2, cmp_lda_imm, cmp_ldx_imm, cmp_ldy_imm, cmp_adc_imm, cmp_stx_zp, cmp_sty_zp, cmp_sec, cmp_clc, is_imm_1, is_imm_2, is_imm, is_zp, is_1cycle, needs_operand, one, zero, go_to_decode, go_to_execute, done_1cycle, done_imm, done_zp, done_temp, done, go_to_fetch, inc_subcycle, reset_subcycle, keep_subcycle, pc_inc_fetch, pc_inc_exec, pc_inc_signal, operand_load_signal, is_write_a, write_a_signal, write_x_signal, write_y_signal, mem_write_signal, use_x_signal, use_y_signal, is_update_flags_1, is_update_flags_2, is_update_flags, update_flags_signal, is_sec_clc, update_c_only_signal, set_c_signal, clear_c_signal }) => [
    inp.current_state.to(is_fetch.a, is_decode.a, is_execute.a, go_to_decode.in0),
    STATE_FETCH.out.to(is_fetch.b, go_to_fetch.in1),
    STATE_DECODE.out.to(is_decode.b, go_to_decode.in1),
    STATE_EXECUTE.out.to(is_execute.b, go_to_execute.in1),
    inp.subcycle.to(at_sub0.a, at_sub1.a, at_sub2.a, inc_subcycle.in),
    SUB0.out.to(at_sub0.b),
    SUB1.out.to(at_sub1.b),
    SUB2.out.to(at_sub2.b),
    is_execute.eq.to(exec_sub0.a, exec_sub1.a, exec_sub2.a, keep_subcycle.sel),
    at_sub0.eq.to(exec_sub0.b),
    at_sub1.eq.to(exec_sub1.b),
    at_sub2.eq.to(exec_sub2.b),
    inp.current_opcode.to(cmp_lda_imm.a, cmp_ldx_imm.a, cmp_ldy_imm.a, cmp_adc_imm.a, cmp_stx_zp.a, cmp_sty_zp.a, cmp_sec.a, cmp_clc.a),
    LDA_IMM.out.to(cmp_lda_imm.b),
    LDX_IMM.out.to(cmp_ldx_imm.b),
    LDY_IMM.out.to(cmp_ldy_imm.b),
    ADC_IMM.out.to(cmp_adc_imm.b),
    cmp_adc_imm.eq.to(out.is_adc_imm, is_imm.b, is_write_a.b, is_update_flags.b),
    STX_ZP.out.to(cmp_stx_zp.b),
    cmp_stx_zp.eq.to(out.is_stx_zp, is_zp.a, use_x_signal.b),
    STY_ZP.out.to(cmp_sty_zp.b),
    cmp_sty_zp.eq.to(out.is_sty_zp, is_zp.b, use_y_signal.b),
    SEC.out.to(cmp_sec.b),
    CLC.out.to(cmp_clc.b),
    cmp_lda_imm.eq.to(is_imm_1.a, is_write_a.a, is_update_flags_1.a),
    cmp_ldx_imm.eq.to(is_imm_1.b, write_x_signal.b, is_update_flags_1.b),
    is_imm_1.out.to(is_imm_2.a),
    cmp_ldy_imm.eq.to(is_imm_2.b, write_y_signal.b, is_update_flags_2.b),
    is_imm_2.out.to(is_imm.a),
    cmp_sec.eq.to(is_1cycle.a, is_sec_clc.a, set_c_signal.b),
    cmp_clc.eq.to(is_1cycle.b, is_sec_clc.b, clear_c_signal.b),
    is_imm.out.to(needs_operand.a, done_imm.b),
    is_zp.out.to(needs_operand.b, done_zp.b, mem_write_signal.b),
    is_fetch.eq.to(go_to_decode.sel, pc_inc_fetch.a, out.ir_load),
    is_decode.eq.to(go_to_execute.sel),
    go_to_decode.out.to(go_to_execute.in0),
    exec_sub0.out.to(done_1cycle.a, pc_inc_exec.a, operand_load_signal.a, update_c_only_signal.a, set_c_signal.a, clear_c_signal.a),
    is_1cycle.out.to(done_1cycle.b),
    exec_sub1.out.to(done_imm.a, write_a_signal.a, write_x_signal.a, write_y_signal.a, update_flags_signal.a),
    exec_sub2.out.to(done_zp.a, mem_write_signal.a, use_x_signal.a, use_y_signal.a),
    done_1cycle.out.to(done_temp.a),
    done_imm.out.to(done_temp.b),
    done_temp.out.to(done.a),
    done_zp.out.to(done.b),
    done.out.to(go_to_fetch.sel, reset_subcycle.sel),
    go_to_execute.out.to(go_to_fetch.in0),
    go_to_fetch.out.to(out.next_state),
    inc_subcycle.out.to(reset_subcycle.in0),
    zero.out.to(reset_subcycle.in1, keep_subcycle.in0),
    reset_subcycle.out.to(keep_subcycle.in1),
    keep_subcycle.out.to(out.next_subcycle),
    one.out.to(pc_inc_fetch.b),
    needs_operand.out.to(pc_inc_exec.b, operand_load_signal.b),
    pc_inc_fetch.out.to(pc_inc_signal.a),
    pc_inc_exec.out.to(pc_inc_signal.b),
    pc_inc_signal.out.to(out.pc_increment),
    operand_load_signal.out.to(out.operand_load, out.addr_lo_load),
    is_write_a.out.to(write_a_signal.b),
    write_a_signal.out.to(out.write_a),
    write_x_signal.out.to(out.write_x),
    write_y_signal.out.to(out.write_y),
    mem_write_signal.out.to(out.mem_write),
    use_x_signal.out.to(out.use_x_for_mem),
    use_y_signal.out.to(out.use_y_for_mem),
    is_update_flags_1.out.to(is_update_flags_2.a),
    is_update_flags_2.out.to(is_update_flags.a),
    is_update_flags.out.to(update_flags_signal.b),
    update_flags_signal.out.to(out.update_flags),
    is_sec_clc.out.to(update_c_only_signal.b),
    update_c_only_signal.out.to(out.update_c_only),
    set_c_signal.out.to(out.set_c),
    clear_c_signal.out.to(out.clear_c),
  ],
})

const Part5TestCPU = component('Part5TestCPU', {
  in: { reset: bit },
  out: { pc: bus(8), reg_a: bus(8), reg_x: bus(8), reg_y: bus(8), flag_c: bit, flag_z: bit, flag_n: bit, mem_10: bus(8), mem_11: bus(8) },
  nodes: { pc_reg: Register, pc_inc: Incrementer, zero: Constant, one: Constant, two: Constant, three: Constant, four: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, thirteen: Constant, fourteen: Constant, fifteen: Constant, sixteen: Constant, seventeen: Constant, byte_0: Constant, byte_1: Constant, byte_2: Constant, byte_3: Constant, byte_4: Constant, byte_5: Constant, byte_6: Constant, byte_7: Constant, byte_8: Constant, byte_9: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, byte_13: Constant, byte_14: Constant, byte_15: Constant, byte_16: Constant, byte_17: Constant, at_0: Comparator, at_1: Comparator, at_2: Comparator, at_3: Comparator, at_4: Comparator, at_5: Comparator, at_6: Comparator, at_7: Comparator, at_8: Comparator, at_9: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, at_16: Comparator, at_17: Comparator, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, mux11: Mux, mux12: Mux, mux13: Mux, mux14: Mux, mux15: Mux, mux16: Mux, rom_out: Mux, state_reg: Register, subcycle_reg: Register, ir_reg: Register, operand_reg: Register, addr_reg: Register, control: Part5Control, registers: RegisterFile, flags: FlagRegister, memory: SimpleMemory, mem_data_x_mux: Mux, mem_data_y_mux: Mux, adc_result: Adder, result_a_adc: Mux, always_on: Constant, pc_next: Mux, split_a: Splitter8to8, split_operand: Splitter8to8, n_value_x: Mux, n_value: Mux, z_check_a: Comparator, z_check_operand: Comparator, z_value_x: Mux, z_value: Mux, c_from_adc: Mux, c_from_sec: Mux, c_value: Mux, update_c_signal: Or, addr_10: Constant, addr_11: Constant, at_addr_10: Comparator, at_addr_11: Comparator },
  nodeArgs: { zero: { value: 0 }, one: { value: 1 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, thirteen: { value: 13 }, fourteen: { value: 14 }, fifteen: { value: 15 }, sixteen: { value: 16 }, seventeen: { value: 17 }, byte_0: { value: 24 }, byte_1: { value: 169 }, byte_2: { value: 16 }, byte_3: { value: 105 }, byte_4: { value: 5 }, byte_5: { value: 105 }, byte_6: { value: 5 }, byte_7: { value: 56 }, byte_8: { value: 105 }, byte_9: { value: 5 }, byte_10: { value: 162 }, byte_11: { value: 66 }, byte_12: { value: 134 }, byte_13: { value: 16 }, byte_14: { value: 160 }, byte_15: { value: 85 }, byte_16: { value: 132 }, byte_17: { value: 17 }, always_on: { value: 1 }, addr_10: { value: 16 }, addr_11: { value: 17 } },
  connect: ({ in: inp, out, pc_reg, pc_inc, zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, byte_0, byte_1, byte_2, byte_3, byte_4, byte_5, byte_6, byte_7, byte_8, byte_9, byte_10, byte_11, byte_12, byte_13, byte_14, byte_15, byte_16, byte_17, at_0, at_1, at_2, at_3, at_4, at_5, at_6, at_7, at_8, at_9, at_10, at_11, at_12, at_13, at_14, at_15, at_16, at_17, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, mux11, mux12, mux13, mux14, mux15, mux16, rom_out, state_reg, subcycle_reg, ir_reg, operand_reg, addr_reg, control, registers, flags, memory, mem_data_x_mux, mem_data_y_mux, adc_result, result_a_adc, always_on, pc_next, split_a, split_operand, n_value_x, n_value, z_check_a, z_check_operand, z_value_x, z_value, c_from_adc, c_from_sec, c_value, update_c_signal, addr_10, addr_11, at_addr_10, at_addr_11 }) => [
    pc_reg.q.to(pc_inc.in, at_0.a, at_1.a, at_2.a, at_3.a, at_4.a, at_5.a, at_6.a, at_7.a, at_8.a, at_9.a, at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, at_16.a, at_17.a, pc_next.in0, out.pc),
    zero.out.to(at_0.b, z_check_a.b, z_check_operand.b, c_value.in1, flags.new_v, flags.update_v),
    one.out.to(at_1.b),
    two.out.to(at_2.b),
    three.out.to(at_3.b),
    four.out.to(at_4.b),
    five.out.to(at_5.b),
    six.out.to(at_6.b),
    seven.out.to(at_7.b),
    eight.out.to(at_8.b),
    nine.out.to(at_9.b),
    ten.out.to(at_10.b),
    eleven.out.to(at_11.b),
    twelve.out.to(at_12.b),
    thirteen.out.to(at_13.b),
    fourteen.out.to(at_14.b),
    fifteen.out.to(at_15.b),
    sixteen.out.to(at_16.b),
    seventeen.out.to(at_17.b),
    at_1.eq.to(mux1.sel),
    byte_0.out.to(mux1.in0),
    byte_1.out.to(mux1.in1),
    at_2.eq.to(mux2.sel),
    mux1.out.to(mux2.in0),
    byte_2.out.to(mux2.in1),
    at_3.eq.to(mux3.sel),
    mux2.out.to(mux3.in0),
    byte_3.out.to(mux3.in1),
    at_4.eq.to(mux4.sel),
    mux3.out.to(mux4.in0),
    byte_4.out.to(mux4.in1),
    at_5.eq.to(mux5.sel),
    mux4.out.to(mux5.in0),
    byte_5.out.to(mux5.in1),
    at_6.eq.to(mux6.sel),
    mux5.out.to(mux6.in0),
    byte_6.out.to(mux6.in1),
    at_7.eq.to(mux7.sel),
    mux6.out.to(mux7.in0),
    byte_7.out.to(mux7.in1),
    at_8.eq.to(mux8.sel),
    mux7.out.to(mux8.in0),
    byte_8.out.to(mux8.in1),
    at_9.eq.to(mux9.sel),
    mux8.out.to(mux9.in0),
    byte_9.out.to(mux9.in1),
    at_10.eq.to(mux10.sel),
    mux9.out.to(mux10.in0),
    byte_10.out.to(mux10.in1),
    at_11.eq.to(mux11.sel),
    mux10.out.to(mux11.in0),
    byte_11.out.to(mux11.in1),
    at_12.eq.to(mux12.sel),
    mux11.out.to(mux12.in0),
    byte_12.out.to(mux12.in1),
    at_13.eq.to(mux13.sel),
    mux12.out.to(mux13.in0),
    byte_13.out.to(mux13.in1),
    at_14.eq.to(mux14.sel),
    mux13.out.to(mux14.in0),
    byte_14.out.to(mux14.in1),
    at_15.eq.to(mux15.sel),
    mux14.out.to(mux15.in0),
    byte_15.out.to(mux15.in1),
    at_16.eq.to(mux16.sel),
    mux15.out.to(mux16.in0),
    byte_16.out.to(mux16.in1),
    at_17.eq.to(rom_out.sel),
    mux16.out.to(rom_out.in0),
    byte_17.out.to(rom_out.in1),
    state_reg.q.to(control.current_state),
    ir_reg.q.to(control.current_opcode),
    subcycle_reg.q.to(control.subcycle),
    flags.flag_c.to(control.flag_c, adc_result.carry_in, c_from_adc.in0, out.flag_c),
    addr_reg.q.to(memory.addr, at_addr_10.a, at_addr_11.a),
    control.mem_write.to(memory.write_enable),
    control.use_x_for_mem.to(mem_data_x_mux.sel),
    registers.reg_a.to(mem_data_x_mux.in0, adc_result.a, out.reg_a),
    registers.reg_x.to(mem_data_x_mux.in1, out.reg_x),
    control.use_y_for_mem.to(mem_data_y_mux.sel),
    mem_data_x_mux.out.to(mem_data_y_mux.in0),
    registers.reg_y.to(mem_data_y_mux.in1, out.reg_y),
    mem_data_y_mux.out.to(memory.data_in),
    operand_reg.q.to(adc_result.b, result_a_adc.in0, registers.data_x, registers.data_y, split_operand.in, z_check_operand.a),
    control.is_adc_imm.to(result_a_adc.sel, c_from_adc.sel),
    adc_result.sum.to(result_a_adc.in1),
    result_a_adc.out.to(registers.data_a, split_a.in, z_check_a.a),
    control.write_a.to(registers.write_a),
    control.write_x.to(registers.write_x, n_value_x.sel, z_value_x.sel),
    control.write_y.to(registers.write_y, n_value.sel, z_value.sel),
    always_on.out.to(state_reg.we, subcycle_reg.we, pc_reg.we, c_from_sec.in1),
    control.next_state.to(state_reg.data),
    control.next_subcycle.to(subcycle_reg.data),
    control.ir_load.to(ir_reg.we),
    rom_out.out.to(ir_reg.data, operand_reg.data, addr_reg.data),
    control.operand_load.to(operand_reg.we),
    control.addr_lo_load.to(addr_reg.we),
    control.pc_increment.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reg.data),
    split_a.bit7.to(n_value_x.in0),
    split_operand.bit7.to(n_value_x.in1, n_value.in1),
    n_value_x.out.to(n_value.in0),
    n_value.out.to(flags.new_n),
    z_check_a.eq.to(z_value_x.in0),
    z_check_operand.eq.to(z_value_x.in1, z_value.in1),
    z_value_x.out.to(z_value.in0),
    z_value.out.to(flags.new_z),
    adc_result.carry_out.to(c_from_adc.in1),
    control.set_c.to(c_from_sec.sel),
    c_from_adc.out.to(c_from_sec.in0),
    control.clear_c.to(c_value.sel),
    c_from_sec.out.to(c_value.in0),
    c_value.out.to(flags.new_c),
    control.update_flags.to(flags.update_n, flags.update_z, update_c_signal.a),
    control.update_c_only.to(update_c_signal.b),
    update_c_signal.out.to(flags.update_c),
    flags.flag_z.to(out.flag_z),
    flags.flag_n.to(out.flag_n),
    addr_10.out.to(at_addr_10.b),
    addr_11.out.to(at_addr_11.b),
    memory.data_out.to(out.mem_10, out.mem_11),
  ],
})

const Part5Test = component('Part5Test', {
  out: { pc: bus(8), reg_a: bus(8), reg_x: bus(8), reg_y: bus(8), flag_c: bit, flag_z: bit, flag_n: bit },
  nodes: { zero: Constant, cpu: Part5TestCPU },
  nodeArgs: { zero: { value: 0 } },
  connect: ({ in: inp, out, zero, cpu }) => [
    zero.out.to(cpu.reset),
    cpu.pc.to(out.pc),
    cpu.reg_a.to(out.reg_a),
    cpu.reg_x.to(out.reg_x),
    cpu.reg_y.to(out.reg_y),
    cpu.flag_c.to(out.flag_c),
    cpu.flag_z.to(out.flag_z),
    cpu.flag_n.to(out.flag_n),
  ],
})
