// Auto-generated from DSL

const SimpleMemory = component('SimpleMemory', {
  in: { addr: bus(8), data_in: bus(8), write_enable: bit },
  out: { data_out: bus(8) },
  nodes: { zero: Constant, addr_10: Constant, addr_11: Constant, at_10: Comparator, at_11: Comparator, mem_10: Register, mem_11: Register, we_10: And, we_11: And, out_10: Mux, out_11: Mux },
  nodeArgs: { zero: { value: 0 }, addr_10: { value: 16 }, addr_11: { value: 17 } },
  connect: ({ in: inp, out, zero, addr_10, addr_11, at_10, at_11, mem_10, mem_11, we_10, we_11, out_10, out_11 }) => [
    inp.addr.to(at_10.a, at_11.a),
    addr_10.out.to(at_10.b),
    addr_11.out.to(at_11.b),
    inp.data_in.to(mem_10.data, mem_11.data),
    inp.write_enable.to(we_10.a, we_11.a),
    at_10.eq.to(we_10.b, out_10.sel),
    at_11.eq.to(we_11.b, out_11.sel),
    we_10.out.to(mem_10.we),
    we_11.out.to(mem_11.we),
    zero.out.to(out_10.in0),
    mem_10.q.to(out_10.in1),
    out_10.out.to(out_11.in0),
    mem_11.q.to(out_11.in1),
    out_11.out.to(out.data_out),
  ],
})

const Part8TestCPU = component('Part8TestCPU', {
  in: { reset: bit },
  out: { pc: bus(8), reg_a: bus(8), mem_10: bus(8), mem_11: bus(8), flag_n: bit, flag_z: bit },
  nodes: { zero: Constant, one: Constant, pc_reg: Register, pc_inc: Incrementer, state_reg: Register, always_on: Constant, STATE_FETCH: Constant, STATE_DECODE: Constant, STATE_EXECUTE: Constant, is_fetch: Comparator, is_decode: Comparator, is_execute: Comparator, subcycle_reg: Register, sub_inc: Incrementer, subcycle_next: Mux, two: Constant, three: Constant, four: Constant, is_sub0: Comparator, is_sub1: Comparator, is_sub2: Comparator, is_sub3: Comparator, is_sub4: Comparator, ir_reg: Register, operand_reg: Register, a_reg: Register, n_reg: Register, z_reg: Register, byte_00: Constant, byte_01: Constant, byte_02: Constant, byte_03: Constant, byte_04: Constant, byte_05: Constant, byte_06: Constant, byte_07: Constant, byte_08: Constant, byte_09: Constant, byte_0A: Constant, byte_0B: Constant, byte_0C: Constant, byte_0D: Constant, byte_0E: Constant, byte_0F: Constant, byte_10: Constant, byte_11: Constant, byte_12: Constant, byte_13: Constant, byte_14: Constant, byte_15: Constant, five: Constant, six: Constant, seven: Constant, eight: Constant, nine: Constant, ten: Constant, eleven: Constant, twelve: Constant, thirteen: Constant, fourteen: Constant, fifteen: Constant, sixteen: Constant, seventeen: Constant, eighteen: Constant, nineteen: Constant, twenty: Constant, twentyone: Constant, at_00: Comparator, at_01: Comparator, at_02: Comparator, at_03: Comparator, at_04: Comparator, at_05: Comparator, at_06: Comparator, at_07: Comparator, at_08: Comparator, at_09: Comparator, at_0A: Comparator, at_0B: Comparator, at_0C: Comparator, at_0D: Comparator, at_0E: Comparator, at_0F: Comparator, at_10: Comparator, at_11: Comparator, at_12: Comparator, at_13: Comparator, at_14: Comparator, at_15: Comparator, mux_01: Mux, mux_02: Mux, mux_03: Mux, mux_04: Mux, mux_05: Mux, mux_06: Mux, mux_07: Mux, mux_08: Mux, mux_09: Mux, mux_0A: Mux, mux_0B: Mux, mux_0C: Mux, mux_0D: Mux, mux_0E: Mux, mux_0F: Mux, mux_10: Mux, mux_11: Mux, mux_12: Mux, mux_13: Mux, mux_14: Mux, rom: Mux, LDA_IMM: Constant, LDA_ZP: Constant, STA_ZP: Constant, INC_ZP: Constant, DEC_ZP: Constant, cmp_lda_imm: Comparator, cmp_lda_zp: Comparator, cmp_sta_zp: Comparator, cmp_inc_zp: Comparator, cmp_dec_zp: Comparator, is_rmw: Or, is_zp_1: Or, is_zp: Or, exec_sub0: And, exec_sub1: And, exec_sub2: And, exec_sub3: And, exec_sub4: And, done_lda_imm: And, not_rmw: Not, is_zp_non_rmw: And, done_zp: And, done_rmw: And, done_temp: Or, exec_done: Or, next_from_fetch: Mux, next_from_decode: Mux, next_from_execute: Mux, next_state: Mux, needs_operand: Or, pc_inc_sub0: And, pc_inc_signal: Or, pc_next: Mux, pc_reset: Mux, operand_load: And, memory: SimpleMemory, is_load_or_rmw: Or, mem_read: And, mem_write_sta: And, mem_write_rmw: And, mem_write: Or, inc_mem: Incrementer, dec_mem: Subtractor, rmw_result: Mux, mem_data_in: Mux, load_a_imm: And, load_a_zp: And, load_a: Or, a_data: Mux, update_flags: And, const_128: Constant, n_check: Comparator, n_flag_val: Or, z_check: Comparator },
  nodeArgs: { zero: { value: 0 }, one: { value: 1 }, always_on: { value: 1 }, STATE_FETCH: { value: 0 }, STATE_DECODE: { value: 1 }, STATE_EXECUTE: { value: 2 }, two: { value: 2 }, three: { value: 3 }, four: { value: 4 }, byte_00: { value: 169 }, byte_01: { value: 5 }, byte_02: { value: 133 }, byte_03: { value: 16 }, byte_04: { value: 230 }, byte_05: { value: 16 }, byte_06: { value: 165 }, byte_07: { value: 16 }, byte_08: { value: 198 }, byte_09: { value: 16 }, byte_0A: { value: 165 }, byte_0B: { value: 16 }, byte_0C: { value: 169 }, byte_0D: { value: 0 }, byte_0E: { value: 133 }, byte_0F: { value: 17 }, byte_10: { value: 198 }, byte_11: { value: 17 }, byte_12: { value: 165 }, byte_13: { value: 17 }, byte_14: { value: 230 }, byte_15: { value: 17 }, five: { value: 5 }, six: { value: 6 }, seven: { value: 7 }, eight: { value: 8 }, nine: { value: 9 }, ten: { value: 10 }, eleven: { value: 11 }, twelve: { value: 12 }, thirteen: { value: 13 }, fourteen: { value: 14 }, fifteen: { value: 15 }, sixteen: { value: 16 }, seventeen: { value: 17 }, eighteen: { value: 18 }, nineteen: { value: 19 }, twenty: { value: 20 }, twentyone: { value: 21 }, LDA_IMM: { value: 169 }, LDA_ZP: { value: 165 }, STA_ZP: { value: 133 }, INC_ZP: { value: 230 }, DEC_ZP: { value: 198 }, const_128: { value: 128 } },
  connect: ({ in: inp, out, zero, one, pc_reg, pc_inc, state_reg, always_on, STATE_FETCH, STATE_DECODE, STATE_EXECUTE, is_fetch, is_decode, is_execute, subcycle_reg, sub_inc, subcycle_next, two, three, four, is_sub0, is_sub1, is_sub2, is_sub3, is_sub4, ir_reg, operand_reg, a_reg, n_reg, z_reg, byte_00, byte_01, byte_02, byte_03, byte_04, byte_05, byte_06, byte_07, byte_08, byte_09, byte_0A, byte_0B, byte_0C, byte_0D, byte_0E, byte_0F, byte_10, byte_11, byte_12, byte_13, byte_14, byte_15, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone, at_00, at_01, at_02, at_03, at_04, at_05, at_06, at_07, at_08, at_09, at_0A, at_0B, at_0C, at_0D, at_0E, at_0F, at_10, at_11, at_12, at_13, at_14, at_15, mux_01, mux_02, mux_03, mux_04, mux_05, mux_06, mux_07, mux_08, mux_09, mux_0A, mux_0B, mux_0C, mux_0D, mux_0E, mux_0F, mux_10, mux_11, mux_12, mux_13, mux_14, rom, LDA_IMM, LDA_ZP, STA_ZP, INC_ZP, DEC_ZP, cmp_lda_imm, cmp_lda_zp, cmp_sta_zp, cmp_inc_zp, cmp_dec_zp, is_rmw, is_zp_1, is_zp, exec_sub0, exec_sub1, exec_sub2, exec_sub3, exec_sub4, done_lda_imm, not_rmw, is_zp_non_rmw, done_zp, done_rmw, done_temp, exec_done, next_from_fetch, next_from_decode, next_from_execute, next_state, needs_operand, pc_inc_sub0, pc_inc_signal, pc_next, pc_reset, operand_load, memory, is_load_or_rmw, mem_read, mem_write_sta, mem_write_rmw, mem_write, inc_mem, dec_mem, rmw_result, mem_data_in, load_a_imm, load_a_zp, load_a, a_data, update_flags, const_128, n_check, n_flag_val, z_check }) => [
    pc_reg.q.to(pc_inc.in, at_00.a, at_01.a, at_02.a, at_03.a, at_04.a, at_05.a, at_06.a, at_07.a, at_08.a, at_09.a, at_0A.a, at_0B.a, at_0C.a, at_0D.a, at_0E.a, at_0F.a, at_10.a, at_11.a, at_12.a, at_13.a, at_14.a, at_15.a, pc_next.in0, out.pc),
    always_on.out.to(state_reg.we, subcycle_reg.we, pc_reg.we),
    state_reg.q.to(is_fetch.a, is_decode.a, is_execute.a, next_from_fetch.in0),
    STATE_FETCH.out.to(is_fetch.b, next_from_execute.in1, next_state.in1),
    STATE_DECODE.out.to(is_decode.b, next_from_fetch.in1),
    STATE_EXECUTE.out.to(is_execute.b, next_from_decode.in1),
    subcycle_reg.q.to(sub_inc.in, is_sub0.a, is_sub1.a, is_sub2.a, is_sub3.a, is_sub4.a),
    is_execute.eq.to(subcycle_next.sel, exec_sub0.a, exec_sub1.a, exec_sub2.a, exec_sub3.a, exec_sub4.a),
    zero.out.to(subcycle_next.in0, is_sub0.b, at_00.b, pc_reset.in1, dec_mem.borrow_in, z_check.b),
    sub_inc.out.to(subcycle_next.in1),
    subcycle_next.out.to(subcycle_reg.data),
    one.out.to(is_sub1.b, at_01.b, dec_mem.b),
    two.out.to(is_sub2.b, at_02.b),
    three.out.to(is_sub3.b, at_03.b),
    four.out.to(is_sub4.b, at_04.b),
    is_fetch.eq.to(ir_reg.we, next_from_fetch.sel, pc_inc_signal.a),
    five.out.to(at_05.b),
    six.out.to(at_06.b),
    seven.out.to(at_07.b),
    eight.out.to(at_08.b),
    nine.out.to(at_09.b),
    ten.out.to(at_0A.b),
    eleven.out.to(at_0B.b),
    twelve.out.to(at_0C.b),
    thirteen.out.to(at_0D.b),
    fourteen.out.to(at_0E.b),
    fifteen.out.to(at_0F.b),
    sixteen.out.to(at_10.b),
    seventeen.out.to(at_11.b),
    eighteen.out.to(at_12.b),
    nineteen.out.to(at_13.b),
    twenty.out.to(at_14.b),
    twentyone.out.to(at_15.b),
    at_01.eq.to(mux_01.sel),
    byte_00.out.to(mux_01.in0),
    byte_01.out.to(mux_01.in1),
    at_02.eq.to(mux_02.sel),
    mux_01.out.to(mux_02.in0),
    byte_02.out.to(mux_02.in1),
    at_03.eq.to(mux_03.sel),
    mux_02.out.to(mux_03.in0),
    byte_03.out.to(mux_03.in1),
    at_04.eq.to(mux_04.sel),
    mux_03.out.to(mux_04.in0),
    byte_04.out.to(mux_04.in1),
    at_05.eq.to(mux_05.sel),
    mux_04.out.to(mux_05.in0),
    byte_05.out.to(mux_05.in1),
    at_06.eq.to(mux_06.sel),
    mux_05.out.to(mux_06.in0),
    byte_06.out.to(mux_06.in1),
    at_07.eq.to(mux_07.sel),
    mux_06.out.to(mux_07.in0),
    byte_07.out.to(mux_07.in1),
    at_08.eq.to(mux_08.sel),
    mux_07.out.to(mux_08.in0),
    byte_08.out.to(mux_08.in1),
    at_09.eq.to(mux_09.sel),
    mux_08.out.to(mux_09.in0),
    byte_09.out.to(mux_09.in1),
    at_0A.eq.to(mux_0A.sel),
    mux_09.out.to(mux_0A.in0),
    byte_0A.out.to(mux_0A.in1),
    at_0B.eq.to(mux_0B.sel),
    mux_0A.out.to(mux_0B.in0),
    byte_0B.out.to(mux_0B.in1),
    at_0C.eq.to(mux_0C.sel),
    mux_0B.out.to(mux_0C.in0),
    byte_0C.out.to(mux_0C.in1),
    at_0D.eq.to(mux_0D.sel),
    mux_0C.out.to(mux_0D.in0),
    byte_0D.out.to(mux_0D.in1),
    at_0E.eq.to(mux_0E.sel),
    mux_0D.out.to(mux_0E.in0),
    byte_0E.out.to(mux_0E.in1),
    at_0F.eq.to(mux_0F.sel),
    mux_0E.out.to(mux_0F.in0),
    byte_0F.out.to(mux_0F.in1),
    at_10.eq.to(mux_10.sel),
    mux_0F.out.to(mux_10.in0),
    byte_10.out.to(mux_10.in1),
    at_11.eq.to(mux_11.sel),
    mux_10.out.to(mux_11.in0),
    byte_11.out.to(mux_11.in1),
    at_12.eq.to(mux_12.sel),
    mux_11.out.to(mux_12.in0),
    byte_12.out.to(mux_12.in1),
    at_13.eq.to(mux_13.sel),
    mux_12.out.to(mux_13.in0),
    byte_13.out.to(mux_13.in1),
    at_14.eq.to(mux_14.sel),
    mux_13.out.to(mux_14.in0),
    byte_14.out.to(mux_14.in1),
    at_15.eq.to(rom.sel),
    mux_14.out.to(rom.in0),
    byte_15.out.to(rom.in1),
    rom.out.to(ir_reg.data, operand_reg.data),
    ir_reg.q.to(cmp_lda_imm.a, cmp_lda_zp.a, cmp_sta_zp.a, cmp_inc_zp.a, cmp_dec_zp.a),
    LDA_IMM.out.to(cmp_lda_imm.b),
    LDA_ZP.out.to(cmp_lda_zp.b),
    STA_ZP.out.to(cmp_sta_zp.b),
    INC_ZP.out.to(cmp_inc_zp.b),
    DEC_ZP.out.to(cmp_dec_zp.b),
    cmp_inc_zp.eq.to(is_rmw.a, rmw_result.sel),
    cmp_dec_zp.eq.to(is_rmw.b),
    cmp_lda_zp.eq.to(is_zp_1.a, is_load_or_rmw.a, load_a_zp.b, a_data.sel),
    cmp_sta_zp.eq.to(is_zp_1.b, mem_write_sta.b),
    is_zp_1.out.to(is_zp.a),
    is_rmw.out.to(is_zp.b, not_rmw.in, done_rmw.b, is_load_or_rmw.b, mem_write_rmw.b, mem_data_in.sel, update_flags.b),
    is_sub0.eq.to(exec_sub0.b),
    is_sub1.eq.to(exec_sub1.b),
    is_sub2.eq.to(exec_sub2.b),
    is_sub3.eq.to(exec_sub3.b),
    is_sub4.eq.to(exec_sub4.b),
    exec_sub1.out.to(done_lda_imm.a, load_a_imm.a),
    cmp_lda_imm.eq.to(done_lda_imm.b, needs_operand.a, load_a_imm.b),
    is_zp.out.to(is_zp_non_rmw.a, needs_operand.b),
    not_rmw.out.to(is_zp_non_rmw.b),
    exec_sub3.out.to(done_zp.a, mem_write_rmw.a, load_a_zp.a, update_flags.a),
    is_zp_non_rmw.out.to(done_zp.b),
    exec_sub4.out.to(done_rmw.a),
    done_lda_imm.out.to(done_temp.a),
    done_zp.out.to(done_temp.b),
    done_temp.out.to(exec_done.a),
    done_rmw.out.to(exec_done.b),
    is_decode.eq.to(next_from_decode.sel),
    next_from_fetch.out.to(next_from_decode.in0),
    exec_done.out.to(next_from_execute.sel),
    next_from_decode.out.to(next_from_execute.in0),
    inp.reset.to(next_state.sel, pc_reset.sel),
    next_from_execute.out.to(next_state.in0),
    next_state.out.to(state_reg.data),
    exec_sub0.out.to(pc_inc_sub0.a, operand_load.a),
    needs_operand.out.to(pc_inc_sub0.b, operand_load.b),
    pc_inc_sub0.out.to(pc_inc_signal.b),
    pc_inc_signal.out.to(pc_next.sel),
    pc_inc.out.to(pc_next.in1),
    pc_next.out.to(pc_reset.in0),
    pc_reset.out.to(pc_reg.data),
    operand_load.out.to(operand_reg.we),
    operand_reg.q.to(memory.addr, a_data.in0),
    exec_sub2.out.to(mem_read.a, mem_write_sta.a),
    is_load_or_rmw.out.to(mem_read.b),
    mem_write_sta.out.to(mem_write.a),
    mem_write_rmw.out.to(mem_write.b),
    mem_write.out.to(memory.write_enable),
    memory.data_out.to(inc_mem.in, dec_mem.a, a_data.in1, out.mem_10, out.mem_11),
    dec_mem.difference.to(rmw_result.in0),
    inc_mem.out.to(rmw_result.in1),
    a_reg.q.to(mem_data_in.in0, out.reg_a),
    rmw_result.out.to(mem_data_in.in1, n_check.a, z_check.a),
    mem_data_in.out.to(memory.data_in),
    load_a_imm.out.to(load_a.a),
    load_a_zp.out.to(load_a.b),
    load_a.out.to(a_reg.we),
    a_data.out.to(a_reg.data),
    update_flags.out.to(n_reg.we, z_reg.we),
    const_128.out.to(n_check.b),
    n_check.gt.to(n_flag_val.a),
    n_check.eq.to(n_flag_val.b),
    n_flag_val.out.to(n_reg.data),
    z_check.eq.to(z_reg.data),
    n_reg.q.to(out.flag_n),
    z_reg.q.to(out.flag_z),
  ],
})

const Part8Test = component('Part8Test', {
  out: { pc: bus(8), reg_a: bus(8), flag_n: bit, flag_z: bit },
  nodes: { zero: Constant, cpu: Part8TestCPU },
  nodeArgs: { zero: { value: 0 } },
  connect: ({ in: inp, out, zero, cpu }) => [
    zero.out.to(cpu.reset),
    cpu.pc.to(out.pc),
    cpu.reg_a.to(out.reg_a),
    cpu.flag_n.to(out.flag_n),
    cpu.flag_z.to(out.flag_z),
  ],
})
