/**
 * Terms of Service page.
 *
 * Source of truth: /TERMS.md at the repository root. When that file
 * changes, mirror the changes here. The prose is duplicated rather than
 * MDX-imported to keep this route SSR-friendly and dependency-free.
 */

import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/terms')({
  component: TermsPage,
  head: () => ({
    meta: [
      { title: 'Terms of Service | Simten' },
      {
        name: 'description',
        content: 'Acceptance, acceptable use, warranty disclaimer, and liability terms for Simten.',
      },
    ],
  }),
});

function TermsPage() {
  return (
    <article className="mx-auto max-w-3xl px-4 py-16 text-foreground">
      <header className="mb-10">
        <h1 className="text-3xl font-semibold tracking-tight">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Effective: 2026-05-28</p>
      </header>

      <Prose>
        <H2>1. Acceptance</H2>
        <p>
          By using simten.dev, the <code>@simten/*</code> npm packages, the MCP server, the embed
          library, or any other service or software made available under the &ldquo;Simten&rdquo;
          name (collectively, &ldquo;the Service&rdquo;), you agree to these Terms. If you
          don&apos;t agree, don&apos;t use the Service.
        </p>

        <H2>2. What Simten is</H2>
        <p>
          Simten is a hardware-design tool: a TypeScript DSL for describing digital circuits, a
          browser-based simulator, an MCP server for editor integration, an embed library, and a
          pipeline for synthesizing circuits to FPGA bitstreams. It&apos;s provided to you free of
          charge.
        </p>

        <H2>3. Acceptable use</H2>
        <p>Don&apos;t:</p>
        <ul>
          <li>
            Use the Service to host, share, or transmit content that&apos;s illegal under any
            applicable law (this includes the circuit-sharing feature at{' '}
            <code>/circuit/s/&lt;hash&gt;</code>).
          </li>
          <li>
            Attempt to defeat or abuse rate limits, the sandbox, or other technical protections.
          </li>
          <li>
            Use automated means (scripts, bots) to overwhelm the Service or any of its endpoints.
          </li>
          <li>
            Use the Service to attack other systems, mine cryptocurrency, or otherwise consume
            resources beyond what an ordinary developer workflow would.
          </li>
          <li>Misrepresent the Service as your own or as endorsed by Simten.</li>
        </ul>
        <p>
          We may rate-limit, remove content, or block access from accounts/IPs that violate these
          rules, with or without notice.
        </p>

        <H2>4. User content (shared circuits)</H2>
        <p>
          When you press &ldquo;Share&rdquo; on a circuit, you (a) confirm you have the right to
          share that content, and (b) grant Simten a non-exclusive, worldwide, royalty-free licence
          to store the source in our infrastructure and serve it to anyone with the link, for as
          long as the link remains active. You retain all other rights.
        </p>
        <p>
          We may remove shared content at our discretion, for example if it&apos;s reported as
          illegal or abusive, or if it appears to be used to circumvent acceptable-use rules. Email{' '}
          <a
            href="mailto:security@simten.dev"
            className="text-foreground underline underline-offset-2 hover:text-foreground/80"
          >
            security@simten.dev
          </a>{' '}
          with the hash (the part after <code>/circuit/s/</code>) to request removal of a specific
          entry.
        </p>

        <H2>5. Open source</H2>
        <p>
          The simten source code is published under{' '}
          <ExternalLink href="https://github.com/simtenHQ/simten/blob/main/LICENSE">
            the licence in the repository
          </ExternalLink>
          . These Terms govern your use of the hosted Service at simten.dev and any official
          binaries we distribute; the licence governs the source. Where the two might conflict
          regarding the source code itself, the licence wins.
        </p>

        <H2>6. Warranty disclaimer</H2>
        <p>
          The Service is provided{' '}
          <strong>
            &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranty of any kind
          </strong>
          , express or implied, including without limitation any warranty of merchantability,
          fitness for a particular purpose, accuracy, non-infringement, or availability.
        </p>
        <p>In particular, and without limiting the generality of the above:</p>
        <ul>
          <li>
            <strong>Hardware outputs are not guaranteed.</strong> Verilog, bitstreams,
            place-and-route reports, and similar artifacts generated by the Service may contain
            bugs. <strong>Synthesize, flash, and run at your own risk.</strong> Do not use
            Simten&apos;s output in safety-critical systems, medical devices, financial systems, or
            any application where failure could cause harm, loss, or significant damage without
            performing your own independent verification.
          </li>
          <li>
            <strong>Simulation results may not match hardware.</strong> Simten&apos;s TypeScript
            simulator is an engineering approximation. Behavioural equivalence to a particular
            silicon target is not guaranteed.
          </li>
          <li>
            <strong>The Service may change, break, or disappear at any time</strong> with no advance
            notice and no obligation to migrate your data or workflows.
          </li>
        </ul>

        <H2>7. Limitation of liability</H2>
        <p>
          To the maximum extent permitted by law, Simten and its contributors shall not be liable
          for any indirect, incidental, special, consequential, exemplary, or punitive damages,
          including loss of profits, data, use, goodwill, or other intangible losses, arising out of
          or relating to your use of (or inability to use) the Service, even if advised of the
          possibility of such damages.
        </p>
        <p>
          Where law prohibits exclusion of liability, our aggregate liability is limited to the
          amount you have paid us for the Service in the twelve months preceding the claim, which,
          for a free Service, is zero.
        </p>

        <H2>8. Indemnity</H2>
        <p>
          You agree to defend, indemnify, and hold harmless Simten and its contributors from any
          claim, loss, or damage (including legal fees) arising out of (a) your use of the Service,
          (b) content you share via the Service, or (c) your violation of these Terms.
        </p>

        <H2>9. Governing law and disputes</H2>
        <p>
          These Terms are governed by the laws of England and Wales, without regard to
          conflict-of-laws rules. Disputes will be resolved in the courts of England and Wales,
          unless mandatory consumer-protection law in your jurisdiction requires otherwise.
        </p>

        <H2>10. Changes</H2>
        <p>
          We may update these Terms. The &ldquo;Effective&rdquo; date at the top reflects the
          current version. Material changes will be noted in the repository changelog. Continued use
          of the Service after a change constitutes acceptance.
        </p>

        <H2>11. Contact</H2>
        <p>
          <a
            href="mailto:security@simten.dev"
            className="text-foreground underline underline-offset-2 hover:text-foreground/80"
          >
            security@simten.dev
          </a>
        </p>
        <p className="text-sm text-muted-foreground">
          For source of truth: this content lives at{' '}
          <ExternalLink href="https://github.com/simtenHQ/simten/blob/main/TERMS.md">
            TERMS.md
          </ExternalLink>{' '}
          in the simten repository.
        </p>
      </Prose>
    </article>
  );
}

function Prose({ children }: { children: React.ReactNode }) {
  return <div className="space-y-4 leading-relaxed text-foreground/90">{children}</div>;
}

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-10 mb-3 text-xl font-semibold tracking-tight text-foreground">{children}</h2>
  );
}

function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="text-foreground underline underline-offset-2 hover:text-foreground/80"
    >
      {children}
    </a>
  );
}
