// Auto-generated from DSL

const ALU = circuit('ALU', {
  in: { a: bus(8), b: bus(8), op0: bit, op1: bit, op2: bit },
  out: { result: bus(8), zero: bit, carry: bit, negative: bit },
  meta: { description: "8-bit ALU — 8 operations, 3 status flags, the heart of every CPU" },
  nodes: { gnd: Constant, add: Adder, sub: Subtractor, band: BusAnd, bor: BusOr, bxor: BusXor, bnot: BusNot, shl: LeftShifter, shr: RightShifter, m01: Mux, m23: Mux, m45: Mux, m67: Mux, m03: Mux, m47: Mux, mfinal: Mux, split_r: Splitter8to8, or01: Or, or23: Or, or45: Or, or67: Or, or_lo: Or, or_hi: Or, or_all: Or, inv_z: Not },
  nodeArgs: { gnd: { value: 0 }, m01: { width: 8 }, m23: { width: 8 }, m45: { width: 8 }, m67: { width: 8 }, m03: { width: 8 }, m47: { width: 8 }, mfinal: { width: 8 } },
  connect: ({ in: inp, out, gnd, add, sub, band, bor, bxor, bnot, shl, shr, m01, m23, m45, m67, m03, m47, mfinal, split_r, or01, or23, or45, or67, or_lo, or_hi, or_all, inv_z }) => [
    inp.a.to(add.a, sub.a, band.a, bor.a, bxor.a, bnot.in, shl.value, shr.value),
    inp.b.to(add.b, sub.b, band.b, bor.b, bxor.b, shl.shift, shr.shift),
    gnd.out.to(add.carry_in, sub.borrow_in),
    add.sum.to(m01.in0),
    sub.difference.to(m01.in1),
    inp.op0.to(m01.sel, m23.sel, m45.sel, m67.sel),
    band.out.to(m23.in0),
    bor.out.to(m23.in1),
    bxor.out.to(m45.in0),
    bnot.out.to(m45.in1),
    shl.result.to(m67.in0),
    shr.result.to(m67.in1),
    m01.out.to(m03.in0),
    m23.out.to(m03.in1),
    inp.op1.to(m03.sel, m47.sel),
    m45.out.to(m47.in0),
    m67.out.to(m47.in1),
    m03.out.to(mfinal.in0),
    m47.out.to(mfinal.in1),
    inp.op2.to(mfinal.sel),
    mfinal.out.to(out.result, split_r.in),
    add.carry_out.to(out.carry),
    split_r.bit7.to(out.negative, or67.b),
    split_r.bit0.to(or01.a),
    split_r.bit1.to(or01.b),
    split_r.bit2.to(or23.a),
    split_r.bit3.to(or23.b),
    split_r.bit4.to(or45.a),
    split_r.bit5.to(or45.b),
    split_r.bit6.to(or67.a),
    or01.out.to(or_lo.a),
    or23.out.to(or_lo.b),
    or45.out.to(or_hi.a),
    or67.out.to(or_hi.b),
    or_lo.out.to(or_all.a),
    or_hi.out.to(or_all.b),
    or_all.out.to(inv_z.in),
    inv_z.out.to(out.zero),
  ],
})

const ALUDemo = circuit('ALUDemo', {
  meta: { description: "Interactive ALU — toggle opcode switches to change operations in real time" },
  nodes: { a: Input, b: Input, op0: Switch, op1: Switch, op2: Switch, alu: ALU, disp_a: HexDisplay, disp_b: HexDisplay, disp_result: HexDisplay, led_zero: Led, led_carry: Led, led_neg: Led },
  nodeArgs: { a: { value: 42 }, b: { value: 13 } },
  connect: ({ in: inp, out, a, b, op0, op1, op2, alu, disp_a, disp_b, disp_result, led_zero, led_carry, led_neg }) => [
    a.out.to(alu.a, disp_a.in),
    b.out.to(alu.b, disp_b.in),
    op0.out.to(alu.op0),
    op1.out.to(alu.op1),
    op2.out.to(alu.op2),
    alu.result.to(disp_result.in),
    alu.zero.to(led_zero.in),
    alu.carry.to(led_carry.in),
    alu.negative.to(led_neg.in),
  ],
})
