// Auto-generated from DSL

const BouncingBall2D = component('BouncingBall2D', {
  nodes: { ballX: Register, ballY: Register, prevX: Register, prevY: Register, dirX: DFlipFlop, dirY: DFlipFlop, framePhase: DFlipFlop, xInc: Incrementer, xDec: Adder, xNegOne: Constant, xNext: Mux, yInc: Incrementer, yDec: Adder, yNegOne: Constant, yNext: Mux, x3bit: BitSlice, y3bit: BitSlice, prevX3bit: BitSlice, prevY3bit: BitSlice, xZero: Constant, xSeven: Constant, cmpXZero: Comparator, cmpXSeven: Comparator, yZero: Constant, ySeven: Constant, cmpYZero: Comparator, cmpYSeven: Comparator, dirXInv: Not, hitXLeft: And, hitXRight: And, shouldFlipX: Or, flipX: Xor, dirYInv: Not, hitYTop: And, hitYBottom: And, shouldFlipY: Or, flipY: Xor, eight: Constant, yTimes8: Multiplier, addr: Adder, prevYTimes8: Multiplier, prevAddr: Adder, addrMux: Mux, pixelMux: Mux, zero: Constant, one: Constant, phaseInv: Not, enable: Constant, fb: DualPortRAM, display: Screen },
  nodeArgs: { ballX: { initial: 1 }, ballY: { initial: 1 }, prevX: { initial: 1 }, prevY: { initial: 1 }, dirX: { initial: 1 }, dirY: { initial: 1 }, xNegOne: { value: 255 }, yNegOne: { value: 255 }, x3bit: { low: 0, high: 2 }, y3bit: { low: 0, high: 2 }, prevX3bit: { low: 0, high: 2 }, prevY3bit: { low: 0, high: 2 }, xZero: { value: 0 }, xSeven: { value: 7 }, yZero: { value: 0 }, ySeven: { value: 7 }, eight: { value: 8 }, zero: { value: 0 }, one: { value: 1 }, enable: { value: 1 } },
  connect: ({ in: inp, out, ballX, ballY, prevX, prevY, dirX, dirY, framePhase, xInc, xDec, xNegOne, xNext, yInc, yDec, yNegOne, yNext, x3bit, y3bit, prevX3bit, prevY3bit, xZero, xSeven, cmpXZero, cmpXSeven, yZero, ySeven, cmpYZero, cmpYSeven, dirXInv, hitXLeft, hitXRight, shouldFlipX, flipX, dirYInv, hitYTop, hitYBottom, shouldFlipY, flipY, eight, yTimes8, addr, prevYTimes8, prevAddr, addrMux, pixelMux, zero, one, phaseInv, enable, fb, display }) => [
    ballX.q.to(xInc.in, xDec.a, prevX.data, x3bit.in),
    xNegOne.out.to(xDec.b),
    flipX.out.to(xNext.sel, dirX.d),
    xInc.out.to(xNext.in1),
    xDec.sum.to(xNext.in0),
    xNext.out.to(ballX.data),
    framePhase.q.to(ballX.we, ballY.we, prevX.we, prevY.we, phaseInv.in, addrMux.sel, pixelMux.sel),
    ballY.q.to(yInc.in, yDec.a, prevY.data, y3bit.in),
    yNegOne.out.to(yDec.b),
    flipY.out.to(yNext.sel, dirY.d),
    yInc.out.to(yNext.in1),
    yDec.sum.to(yNext.in0),
    yNext.out.to(ballY.data),
    prevX.q.to(prevX3bit.in),
    prevY.q.to(prevY3bit.in),
    x3bit.out.to(cmpXZero.a, cmpXSeven.a, addr.b),
    xZero.out.to(cmpXZero.b),
    xSeven.out.to(cmpXSeven.b),
    y3bit.out.to(cmpYZero.a, cmpYSeven.a, yTimes8.a),
    yZero.out.to(cmpYZero.b),
    ySeven.out.to(cmpYSeven.b),
    dirX.q.to(dirXInv.in, hitXRight.b, flipX.a),
    cmpXZero.eq.to(hitXLeft.a),
    dirXInv.out.to(hitXLeft.b),
    cmpXSeven.eq.to(hitXRight.a),
    hitXLeft.out.to(shouldFlipX.a),
    hitXRight.out.to(shouldFlipX.b),
    shouldFlipX.out.to(flipX.b),
    dirY.q.to(dirYInv.in, hitYBottom.b, flipY.a),
    cmpYZero.eq.to(hitYTop.a),
    dirYInv.out.to(hitYTop.b),
    cmpYSeven.eq.to(hitYBottom.a),
    hitYTop.out.to(shouldFlipY.a),
    hitYBottom.out.to(shouldFlipY.b),
    shouldFlipY.out.to(flipY.b),
    eight.out.to(yTimes8.b, prevYTimes8.b),
    yTimes8.product.to(addr.a),
    prevY3bit.out.to(prevYTimes8.a),
    prevYTimes8.product.to(prevAddr.a),
    prevX3bit.out.to(prevAddr.b),
    phaseInv.out.to(framePhase.d),
    prevAddr.sum.to(addrMux.in0),
    addr.sum.to(addrMux.in1),
    zero.out.to(pixelMux.in0),
    one.out.to(pixelMux.in1),
    addrMux.out.to(fb.addrA),
    pixelMux.out.to(fb.dataA),
    enable.out.to(fb.weA),
    display.addrB.to(fb.addrB),
    fb.outB.to(display.dataIn),
  ],
})
