// Auto-generated from DSL

const BouncingBallDamped = circuit('BouncingBallDamped', {
  nodes: { ballX: Register, ballY: Register, prevX: Register, prevY: Register, dirY: DFlipFlop, maxReach: Register, framePhase: DFlipFlop, yInc: Incrementer, yDec: Adder, yNegOne: Constant, yNext: Mux, ground: Constant, cmpGround: Comparator, cmpMaxReach: Comparator, dirYInv: Not, hitGround: And, hitTop: And, shouldFlip: Or, flipY: Xor, maxReachInc: Incrementer, maxReachNext: Mux, eight: Constant, yTimes8: Multiplier, addr: Adder, prevYTimes8: Multiplier, prevAddr: Adder, addrMux: Mux, pixelMux: Mux, zero: Constant, one: Constant, phaseInv: Not, enable: Constant, fb: DualPortRAM, display: Screen, debugMaxReach: HexDisplay, y3bit: BitSlice, x3bit: BitSlice, prevY3bit: BitSlice, prevX3bit: BitSlice, maxReach3bit: BitSlice },
  nodeArgs: { ballX: { initial: 3 }, ballY: { initial: 7 }, prevX: { initial: 3 }, prevY: { initial: 7 }, dirY: { initial: 0 }, maxReach: { initial: 0 }, yNegOne: { value: 255 }, ground: { value: 7 }, eight: { value: 8 }, zero: { value: 0 }, one: { value: 1 }, enable: { value: 1 }, y3bit: { low: 0, high: 2 }, x3bit: { low: 0, high: 2 }, prevY3bit: { low: 0, high: 2 }, prevX3bit: { low: 0, high: 2 }, maxReach3bit: { low: 0, high: 2 } },
  connect: ({ in: inp, out, ballX, ballY, prevX, prevY, dirY, maxReach, framePhase, yInc, yDec, yNegOne, yNext, ground, cmpGround, cmpMaxReach, dirYInv, hitGround, hitTop, shouldFlip, flipY, maxReachInc, maxReachNext, eight, yTimes8, addr, prevYTimes8, prevAddr, addrMux, pixelMux, zero, one, phaseInv, enable, fb, display, debugMaxReach, y3bit, x3bit, prevY3bit, prevX3bit, maxReach3bit }) => [
    ballY.q.to(yInc.in, yDec.a, prevY.data, y3bit.in),
    yNegOne.out.to(yDec.b),
    flipY.out.to(yNext.sel, dirY.d),
    yInc.out.to(yNext.in1),
    yDec.sum.to(yNext.in0),
    yNext.out.to(ballY.data),
    framePhase.q.to(ballY.we, prevX.we, prevY.we, phaseInv.in, addrMux.sel, pixelMux.sel),
    ballX.q.to(prevX.data, x3bit.in),
    prevY.q.to(prevY3bit.in),
    prevX.q.to(prevX3bit.in),
    maxReach.q.to(maxReach3bit.in, maxReachInc.in, maxReachNext.in0, debugMaxReach.in),
    y3bit.out.to(cmpGround.a, cmpMaxReach.a, yTimes8.a),
    ground.out.to(cmpGround.b),
    maxReach3bit.out.to(cmpMaxReach.b),
    dirY.q.to(dirYInv.in, hitGround.b, flipY.a),
    cmpGround.eq.to(hitGround.a),
    cmpMaxReach.eq.to(hitTop.a),
    dirYInv.out.to(hitTop.b),
    hitGround.out.to(shouldFlip.a, maxReachNext.sel),
    hitTop.out.to(shouldFlip.b),
    shouldFlip.out.to(flipY.b),
    maxReachInc.out.to(maxReachNext.in1),
    maxReachNext.out.to(maxReach.data),
    enable.out.to(maxReach.we, fb.weA),
    eight.out.to(yTimes8.b, prevYTimes8.b),
    yTimes8.product.to(addr.a),
    x3bit.out.to(addr.b),
    prevY3bit.out.to(prevYTimes8.a),
    prevYTimes8.product.to(prevAddr.a),
    prevX3bit.out.to(prevAddr.b),
    phaseInv.out.to(framePhase.d),
    prevAddr.sum.to(addrMux.in0),
    addr.sum.to(addrMux.in1),
    zero.out.to(pixelMux.in0),
    one.out.to(pixelMux.in1),
    addrMux.out.to(fb.addrA),
    pixelMux.out.to(fb.dataA),
    display.addrB.to(fb.addrB),
    fb.outB.to(display.dataIn),
  ],
})
