// Auto-generated from DSL

const CORDICIteration = component('CORDICIteration', {
  nodes: { x: Register, y: Register, z: Register, iteration: Register, zero: Constant, one: Constant, eight: Constant, zPositive: SignedComparator, xShifted: RightShifter, yShifted: RightShifter, yShiftedNeg: BusNot, xSubtract: SignedAdder, xAdd: SignedAdder, xUpdate: Mux, xShiftedNeg: BusNot, yAdd: SignedAdder, ySubtract: SignedAdder, yUpdate: Mux, angle0: Constant, angle1: Constant, angle2: Constant, angle3: Constant, angle4: Constant, angle5: Constant, angle6: Constant, angle7: Constant, bit0: BitSlice, bit1: BitSlice, bit2: BitSlice, mux01: Mux, mux23: Mux, mux45: Mux, mux67: Mux, mux0123: Mux, mux4567: Mux, angleSel: Mux, angleNeg: BusNot, zSubtract: SignedAdder, zAdd: SignedAdder, zUpdate: Mux, iterInc: Incrementer, shouldContinue: Comparator, xDisplay: HexDisplay, yDisplay: HexDisplay, zDisplay: HexDisplay, iterDisplay: HexDisplay, doneCheck: Comparator, doneLed: Led },
  nodeArgs: { x: { initial: 80 }, y: { initial: 0 }, z: { initial: 32 }, iteration: { initial: 0 }, zero: { value: 0 }, one: { value: 1 }, eight: { value: 8 }, angle0: { value: 32 }, angle1: { value: 19 }, angle2: { value: 10 }, angle3: { value: 5 }, angle4: { value: 3 }, angle5: { value: 1 }, angle6: { value: 1 }, angle7: { value: 0 }, bit0: { low: 0, high: 0 }, bit1: { low: 1, high: 1 }, bit2: { low: 2, high: 2 } },
  connect: ({ in: inp, out, x, y, z, iteration, zero, one, eight, zPositive, xShifted, yShifted, yShiftedNeg, xSubtract, xAdd, xUpdate, xShiftedNeg, yAdd, ySubtract, yUpdate, angle0, angle1, angle2, angle3, angle4, angle5, angle6, angle7, bit0, bit1, bit2, mux01, mux23, mux45, mux67, mux0123, mux4567, angleSel, angleNeg, zSubtract, zAdd, zUpdate, iterInc, shouldContinue, xDisplay, yDisplay, zDisplay, iterDisplay, doneCheck, doneLed }) => [
    z.q.to(zPositive.a, zSubtract.a, zAdd.a, zDisplay.in),
    zero.out.to(zPositive.b, xAdd.carry_in, yAdd.carry_in, zAdd.carry_in),
    x.q.to(xShifted.value, xSubtract.a, xAdd.a, xDisplay.in),
    y.q.to(yShifted.value, yAdd.a, ySubtract.a, yDisplay.in),
    iteration.q.to(xShifted.shift, yShifted.shift, bit0.in, bit1.in, bit2.in, iterInc.in, shouldContinue.a, iterDisplay.in, doneCheck.a),
    yShifted.result.to(yShiftedNeg.in, xAdd.b),
    yShiftedNeg.out.to(xSubtract.b),
    one.out.to(xSubtract.carry_in, ySubtract.carry_in, zSubtract.carry_in),
    zPositive.gte.to(xUpdate.sel, yUpdate.sel, zUpdate.sel),
    xAdd.sum.to(xUpdate.in0),
    xSubtract.sum.to(xUpdate.in1),
    xShifted.result.to(xShiftedNeg.in, yAdd.b),
    xShiftedNeg.out.to(ySubtract.b),
    ySubtract.sum.to(yUpdate.in0),
    yAdd.sum.to(yUpdate.in1),
    bit0.out.to(mux01.sel, mux23.sel, mux45.sel, mux67.sel),
    angle0.out.to(mux01.in0),
    angle1.out.to(mux01.in1),
    angle2.out.to(mux23.in0),
    angle3.out.to(mux23.in1),
    angle4.out.to(mux45.in0),
    angle5.out.to(mux45.in1),
    angle6.out.to(mux67.in0),
    angle7.out.to(mux67.in1),
    bit1.out.to(mux0123.sel, mux4567.sel),
    mux01.out.to(mux0123.in0),
    mux23.out.to(mux0123.in1),
    mux45.out.to(mux4567.in0),
    mux67.out.to(mux4567.in1),
    bit2.out.to(angleSel.sel),
    mux0123.out.to(angleSel.in0),
    mux4567.out.to(angleSel.in1),
    angleSel.out.to(angleNeg.in, zAdd.b),
    angleNeg.out.to(zSubtract.b),
    zAdd.sum.to(zUpdate.in0),
    zSubtract.sum.to(zUpdate.in1),
    eight.out.to(shouldContinue.b, doneCheck.b),
    shouldContinue.lt.to(x.we, y.we, z.we, iteration.we),
    xUpdate.out.to(x.data),
    yUpdate.out.to(y.data),
    zUpdate.out.to(z.data),
    iterInc.out.to(iteration.data),
    doneCheck.eq.to(doneLed.in),
  ],
})
