// Auto-generated from DSL

const DrawLetterC = circuit('DrawLetterC', {
  nodes: { fb1: DualPortRAM, fb2: DualPortRAM, display: Screen, bufferSelect: DFlipFlop, readDataMux: Mux, pixelIndex: Register, drawing: DFlipFlop, done: DFlipFlop, addr0: Constant, addr1: Constant, addr2: Constant, addr3: Constant, addr4: Constant, addr5: Constant, addr6: Constant, addr7: Constant, addr8: Constant, addr9: Constant, addr10: Constant, addr11: Constant, zero: Constant, one: Constant, twelve: Constant, mux0: Mux, mux1: Mux, mux2: Mux, mux3: Mux, mux4: Mux, mux5: Mux, mux6: Mux, mux7: Mux, mux8: Mux, mux9: Mux, mux10: Mux, bit0: BitSlice, bit1: BitSlice, bit2: BitSlice, bit3: BitSlice, checkDone: Comparator, isDone: Not, shouldSetDone: And, notDone: Not, keepDrawing: And, indexInc: Incrementer, shouldIncrement: And, swapBuffers: Xor, writeEnable1: Mux, writeEnable2: Mux, statusDisplay: HexDisplay, doneLed: Led },
  nodeArgs: { pixelIndex: { initial: 0 }, drawing: { initial: 1 }, done: { initial: 0 }, addr0: { value: 10 }, addr1: { value: 11 }, addr2: { value: 12 }, addr3: { value: 13 }, addr4: { value: 17 }, addr5: { value: 22 }, addr6: { value: 24 }, addr7: { value: 32 }, addr8: { value: 41 }, addr9: { value: 46 }, addr10: { value: 50 }, addr11: { value: 51 }, zero: { value: 0 }, one: { value: 1 }, twelve: { value: 12 }, bit0: { low: 0, high: 0 }, bit1: { low: 1, high: 1 }, bit2: { low: 2, high: 2 }, bit3: { low: 3, high: 3 } },
  connect: ({ in: inp, out, fb1, fb2, display, bufferSelect, readDataMux, pixelIndex, drawing, done, addr0, addr1, addr2, addr3, addr4, addr5, addr6, addr7, addr8, addr9, addr10, addr11, zero, one, twelve, mux0, mux1, mux2, mux3, mux4, mux5, mux6, mux7, mux8, mux9, mux10, bit0, bit1, bit2, bit3, checkDone, isDone, shouldSetDone, notDone, keepDrawing, indexInc, shouldIncrement, swapBuffers, writeEnable1, writeEnable2, statusDisplay, doneLed }) => [
    pixelIndex.q.to(bit0.in, bit1.in, bit2.in, bit3.in, checkDone.a, indexInc.in, statusDisplay.in),
    bit0.out.to(mux0.sel, mux1.sel, mux2.sel, mux3.sel, mux4.sel, mux5.sel),
    addr0.out.to(mux0.in0),
    addr1.out.to(mux0.in1),
    addr2.out.to(mux1.in0),
    addr3.out.to(mux1.in1),
    addr4.out.to(mux2.in0),
    addr5.out.to(mux2.in1),
    addr6.out.to(mux3.in0),
    addr7.out.to(mux3.in1),
    addr8.out.to(mux4.in0),
    addr9.out.to(mux4.in1),
    addr10.out.to(mux5.in0),
    addr11.out.to(mux5.in1),
    bit1.out.to(mux6.sel, mux7.sel, mux8.sel),
    mux0.out.to(mux6.in0),
    mux1.out.to(mux6.in1),
    mux2.out.to(mux7.in0),
    mux3.out.to(mux7.in1),
    mux4.out.to(mux8.in0),
    mux5.out.to(mux8.in1),
    bit2.out.to(mux9.sel),
    mux6.out.to(mux9.in0),
    mux7.out.to(mux9.in1),
    bit3.out.to(mux10.sel),
    mux9.out.to(mux10.in0),
    mux8.out.to(mux10.in1),
    twelve.out.to(checkDone.b),
    checkDone.lt.to(isDone.in),
    isDone.out.to(shouldSetDone.a),
    drawing.q.to(shouldSetDone.b, keepDrawing.a, shouldIncrement.a),
    shouldSetDone.out.to(done.d, swapBuffers.b),
    done.q.to(notDone.in, doneLed.in),
    notDone.out.to(keepDrawing.b, shouldIncrement.b),
    keepDrawing.out.to(drawing.d),
    indexInc.out.to(pixelIndex.data),
    shouldIncrement.out.to(pixelIndex.we, writeEnable1.in1, writeEnable2.in0),
    bufferSelect.q.to(swapBuffers.a, writeEnable1.sel, writeEnable2.sel, readDataMux.sel),
    swapBuffers.out.to(bufferSelect.d),
    mux10.out.to(fb1.addrA, fb2.addrA),
    one.out.to(fb1.dataA, fb2.dataA),
    zero.out.to(writeEnable1.in0, writeEnable2.in1),
    writeEnable1.out.to(fb1.weA),
    writeEnable2.out.to(fb2.weA),
    display.addrB.to(fb1.addrB, fb2.addrB),
    fb1.outB.to(readDataMux.in0),
    fb2.outB.to(readDataMux.in1),
    readDataMux.out.to(display.dataIn),
  ],
})
