// Auto-generated from DSL

const EgressController = circuit('EgressController', {
  in: { pkt_ready: bit, trigger: bit },
  out: { egress_addr: bus(8), egress_re: bit, data_valid: bit, sof: bit, eof: bit, ready: bit },
  nodes: { fsm_state: Register, byte_counter: Register, read_ptr: Register, STATE_IDLE: Input, STATE_TRANSMIT: Input, ZERO: Input, ONE: Input, SEVEN: Input, EIGHT: Input, isIDLE: Comparator, isTRANSMIT: Comparator, can_start: And, idle_to_transmit: And, byte_is_seven: Comparator, transmit_complete: And, next_state_m1: Mux, next_state: Mux, fsm_state_we: Input, byte_inc: Adder, should_increment: And, should_reset: And, next_byte_counter_inc: Mux, next_byte_counter: Mux, byte_counter_we: Input, ptr_add_eight: Adder, should_advance_ptr: And, next_read_ptr: Mux, read_ptr_we: Input, egress_addr_calc: Adder, byte_is_zero: Comparator, sof_signal: And, eof_signal: And, fsm_state_display: HexDisplay, byte_counter_display: HexDisplay, read_ptr_display: HexDisplay },
  nodeArgs: { STATE_IDLE: { value: 0 }, STATE_TRANSMIT: { value: 1 }, ZERO: { value: 0 }, ONE: { value: 1 }, SEVEN: { value: 7 }, EIGHT: { value: 8 }, fsm_state_we: { value: 1 }, byte_counter_we: { value: 1 }, read_ptr_we: { value: 1 } },
  connect: ({ in: inp, out, fsm_state, byte_counter, read_ptr, STATE_IDLE, STATE_TRANSMIT, ZERO, ONE, SEVEN, EIGHT, isIDLE, isTRANSMIT, can_start, idle_to_transmit, byte_is_seven, transmit_complete, next_state_m1, next_state, fsm_state_we, byte_inc, should_increment, should_reset, next_byte_counter_inc, next_byte_counter, byte_counter_we, ptr_add_eight, should_advance_ptr, next_read_ptr, read_ptr_we, egress_addr_calc, byte_is_zero, sof_signal, eof_signal, fsm_state_display, byte_counter_display, read_ptr_display }) => [
    fsm_state.q.to(isIDLE.a, isTRANSMIT.a, next_state_m1.in0, fsm_state_display.in),
    STATE_IDLE.out.to(isIDLE.b, next_state.in1),
    STATE_TRANSMIT.out.to(isTRANSMIT.b, next_state_m1.in1),
    inp.trigger.to(can_start.a),
    inp.pkt_ready.to(can_start.b),
    isIDLE.eq.to(idle_to_transmit.a, out.ready),
    can_start.out.to(idle_to_transmit.b),
    byte_counter.q.to(byte_is_seven.a, byte_inc.a, next_byte_counter_inc.in0, egress_addr_calc.b, byte_is_zero.a, byte_counter_display.in),
    SEVEN.out.to(byte_is_seven.b),
    isTRANSMIT.eq.to(transmit_complete.a, should_increment.a, should_increment.b, out.egress_re, out.data_valid, sof_signal.a, eof_signal.a),
    byte_is_seven.eq.to(transmit_complete.b, eof_signal.b),
    idle_to_transmit.out.to(next_state_m1.sel, should_reset.a, should_reset.b),
    next_state_m1.out.to(next_state.in0),
    transmit_complete.out.to(next_state.sel, should_advance_ptr.a, should_advance_ptr.b),
    next_state.out.to(fsm_state.data),
    fsm_state_we.out.to(fsm_state.we),
    ONE.out.to(byte_inc.b),
    byte_inc.sum.to(next_byte_counter_inc.in1),
    should_increment.out.to(next_byte_counter_inc.sel),
    next_byte_counter_inc.out.to(next_byte_counter.in0),
    ZERO.out.to(next_byte_counter.in1, byte_is_zero.b),
    should_reset.out.to(next_byte_counter.sel),
    next_byte_counter.out.to(byte_counter.data),
    byte_counter_we.out.to(byte_counter.we),
    read_ptr.q.to(ptr_add_eight.a, next_read_ptr.in0, egress_addr_calc.a, read_ptr_display.in),
    EIGHT.out.to(ptr_add_eight.b),
    ptr_add_eight.sum.to(next_read_ptr.in1),
    should_advance_ptr.out.to(next_read_ptr.sel),
    next_read_ptr.out.to(read_ptr.data),
    read_ptr_we.out.to(read_ptr.we),
    egress_addr_calc.sum.to(out.egress_addr),
    byte_is_zero.eq.to(sof_signal.b),
    sof_signal.out.to(out.sof),
    eof_signal.out.to(out.eof),
  ],
})
