// Auto-generated from DSL

const PacketGenerator = component('PacketGenerator', {
  out: { byte_out: bus(8), valid: bit },
  nodes: { cycle_counter: Register, counter_inc: Adder, ONE: Input, is_nineteen: Comparator, NINETEEN: Input, ZERO: Input, next_counter: Mux, counter_we: Input, is_cycle_0: Comparator, is_cycle_1: Comparator, is_cycle_2: Comparator, TWO: Input, is_cycle_3: Comparator, THREE: Input, is_cycle_4: Comparator, FOUR: Input, is_cycle_5: Comparator, FIVE: Input, is_cycle_6: Comparator, SIX: Input, is_preamble_0_1: Or, is_preamble_2_3: Or, is_preamble_4_5: Or, is_preamble_01_23: Or, is_preamble_45_6: Or, is_preamble: Or, is_cycle_7: Comparator, SEVEN: Input, is_cycle_8: Comparator, EIGHT: Input, is_cycle_9: Comparator, NINE: Input, is_cycle_10: Comparator, TEN: Input, is_cycle_11: Comparator, ELEVEN: Input, is_cycle_12: Comparator, TWELVE: Input, is_cycle_13: Comparator, THIRTEEN: Input, is_cycle_14: Comparator, FOURTEEN: Input, is_cycle_15: Comparator, FIFTEEN: Input, is_lt_sixteen: Comparator, SIXTEEN: Input, DATA_0: Input, DATA_1: Input, DATA_2: Input, DATA_3: Input, DATA_4: Input, DATA_5: Input, DATA_6: Input, DATA_7: Input, PREAMBLE_BYTE: Input, SFD_BYTE: Input, data_mux_7: Mux, data_mux_6: Mux, data_mux_5: Mux, data_mux_4: Mux, data_mux_3: Mux, data_mux_2: Mux, data_mux_1: Mux, data_mux_0: Mux, sfd_or_data: Mux, byte_out_mux: Mux },
  nodeArgs: { ONE: { value: 1 }, NINETEEN: { value: 19 }, ZERO: { value: 0 }, counter_we: { value: 1 }, TWO: { value: 2 }, THREE: { value: 3 }, FOUR: { value: 4 }, FIVE: { value: 5 }, SIX: { value: 6 }, SEVEN: { value: 7 }, EIGHT: { value: 8 }, NINE: { value: 9 }, TEN: { value: 10 }, ELEVEN: { value: 11 }, TWELVE: { value: 12 }, THIRTEEN: { value: 13 }, FOURTEEN: { value: 14 }, FIFTEEN: { value: 15 }, SIXTEEN: { value: 16 }, DATA_0: { value: 170 }, DATA_1: { value: 187 }, DATA_2: { value: 204 }, DATA_3: { value: 221 }, DATA_4: { value: 238 }, DATA_5: { value: 255 }, DATA_6: { value: 17 }, DATA_7: { value: 34 }, PREAMBLE_BYTE: { value: 85 }, SFD_BYTE: { value: 213 } },
  connect: ({ in: inp, out, cycle_counter, counter_inc, ONE, is_nineteen, NINETEEN, ZERO, next_counter, counter_we, is_cycle_0, is_cycle_1, is_cycle_2, TWO, is_cycle_3, THREE, is_cycle_4, FOUR, is_cycle_5, FIVE, is_cycle_6, SIX, is_preamble_0_1, is_preamble_2_3, is_preamble_4_5, is_preamble_01_23, is_preamble_45_6, is_preamble, is_cycle_7, SEVEN, is_cycle_8, EIGHT, is_cycle_9, NINE, is_cycle_10, TEN, is_cycle_11, ELEVEN, is_cycle_12, TWELVE, is_cycle_13, THIRTEEN, is_cycle_14, FOURTEEN, is_cycle_15, FIFTEEN, is_lt_sixteen, SIXTEEN, DATA_0, DATA_1, DATA_2, DATA_3, DATA_4, DATA_5, DATA_6, DATA_7, PREAMBLE_BYTE, SFD_BYTE, data_mux_7, data_mux_6, data_mux_5, data_mux_4, data_mux_3, data_mux_2, data_mux_1, data_mux_0, sfd_or_data, byte_out_mux }) => [
    cycle_counter.q.to(counter_inc.a, is_nineteen.a, is_cycle_0.a, is_cycle_1.a, is_cycle_2.a, is_cycle_3.a, is_cycle_4.a, is_cycle_5.a, is_cycle_6.a, is_cycle_7.a, is_cycle_8.a, is_cycle_9.a, is_cycle_10.a, is_cycle_11.a, is_cycle_12.a, is_cycle_13.a, is_cycle_14.a, is_cycle_15.a, is_lt_sixteen.a),
    ONE.out.to(counter_inc.b, is_cycle_1.b),
    NINETEEN.out.to(is_nineteen.b),
    counter_inc.sum.to(next_counter.in0),
    ZERO.out.to(next_counter.in1, is_cycle_0.b),
    is_nineteen.eq.to(next_counter.sel),
    next_counter.out.to(cycle_counter.data),
    counter_we.out.to(cycle_counter.we),
    TWO.out.to(is_cycle_2.b),
    THREE.out.to(is_cycle_3.b),
    FOUR.out.to(is_cycle_4.b),
    FIVE.out.to(is_cycle_5.b),
    SIX.out.to(is_cycle_6.b),
    is_cycle_0.eq.to(is_preamble_0_1.a),
    is_cycle_1.eq.to(is_preamble_0_1.b),
    is_cycle_2.eq.to(is_preamble_2_3.a),
    is_cycle_3.eq.to(is_preamble_2_3.b),
    is_cycle_4.eq.to(is_preamble_4_5.a),
    is_cycle_5.eq.to(is_preamble_4_5.b),
    is_preamble_0_1.out.to(is_preamble_01_23.a),
    is_preamble_2_3.out.to(is_preamble_01_23.b),
    is_preamble_4_5.out.to(is_preamble_45_6.a),
    is_cycle_6.eq.to(is_preamble_45_6.b),
    is_preamble_01_23.out.to(is_preamble.a),
    is_preamble_45_6.out.to(is_preamble.b),
    SEVEN.out.to(is_cycle_7.b),
    EIGHT.out.to(is_cycle_8.b),
    NINE.out.to(is_cycle_9.b),
    TEN.out.to(is_cycle_10.b),
    ELEVEN.out.to(is_cycle_11.b),
    TWELVE.out.to(is_cycle_12.b),
    THIRTEEN.out.to(is_cycle_13.b),
    FOURTEEN.out.to(is_cycle_14.b),
    FIFTEEN.out.to(is_cycle_15.b),
    SIXTEEN.out.to(is_lt_sixteen.b),
    is_lt_sixteen.lt.to(out.valid),
    DATA_7.out.to(data_mux_7.in0, data_mux_7.in1),
    is_cycle_15.eq.to(data_mux_7.sel),
    data_mux_7.out.to(data_mux_6.in0),
    DATA_6.out.to(data_mux_6.in1),
    is_cycle_14.eq.to(data_mux_6.sel),
    data_mux_6.out.to(data_mux_5.in0),
    DATA_5.out.to(data_mux_5.in1),
    is_cycle_13.eq.to(data_mux_5.sel),
    data_mux_5.out.to(data_mux_4.in0),
    DATA_4.out.to(data_mux_4.in1),
    is_cycle_12.eq.to(data_mux_4.sel),
    data_mux_4.out.to(data_mux_3.in0),
    DATA_3.out.to(data_mux_3.in1),
    is_cycle_11.eq.to(data_mux_3.sel),
    data_mux_3.out.to(data_mux_2.in0),
    DATA_2.out.to(data_mux_2.in1),
    is_cycle_10.eq.to(data_mux_2.sel),
    data_mux_2.out.to(data_mux_1.in0),
    DATA_1.out.to(data_mux_1.in1),
    is_cycle_9.eq.to(data_mux_1.sel),
    data_mux_1.out.to(data_mux_0.in0),
    DATA_0.out.to(data_mux_0.in1),
    is_cycle_8.eq.to(data_mux_0.sel),
    data_mux_0.out.to(sfd_or_data.in0),
    SFD_BYTE.out.to(sfd_or_data.in1),
    is_cycle_7.eq.to(sfd_or_data.sel),
    sfd_or_data.out.to(byte_out_mux.in0),
    PREAMBLE_BYTE.out.to(byte_out_mux.in1),
    is_preamble.out.to(byte_out_mux.sel),
    byte_out_mux.out.to(out.byte_out),
  ],
})
