// Auto-generated from DSL

const ScrollingHello = circuit('ScrollingHello', {
  nodes: { bitmap: ROM, scrollOffset: Register, debugScroll: HexDisplay, renderAddr: Register, renderInc: Incrementer, sixtythree: Constant, renderDone: Comparator, renderNext: Mux, zero: Constant, renderX: BitSlice, renderY: BitSlice, scrollInc: Incrementer, twentythree: Constant, scrollWrap: Comparator, scrollWrapped: Mux, twentyfour: Constant, yTimes24: Multiplier, scrollPlusX: Adder, xOffset: BitSlice, bitmapAddr: Adder, fb: DualPortRAM, display: Screen, enable: Constant },
  nodeArgs: { bitmap: { data: [1,0,1,0,1,1,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1,0,1,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] }, sixtythree: { value: 63 }, zero: { value: 0 }, renderX: { low: 0, high: 2 }, renderY: { low: 3, high: 5 }, twentythree: { value: 23 }, twentyfour: { value: 24 }, xOffset: { low: 0, high: 4 }, enable: { value: 1 } },
  connect: ({ in: inp, out, bitmap, scrollOffset, debugScroll, renderAddr, renderInc, sixtythree, renderDone, renderNext, zero, renderX, renderY, scrollInc, twentythree, scrollWrap, scrollWrapped, twentyfour, yTimes24, scrollPlusX, xOffset, bitmapAddr, fb, display, enable }) => [
    scrollOffset.q.to(scrollInc.in, debugScroll.in, scrollPlusX.a),
    scrollInc.out.to(scrollWrap.a, scrollWrapped.in0),
    twentythree.out.to(scrollWrap.b),
    scrollWrap.gt.to(scrollWrapped.sel),
    zero.out.to(scrollWrapped.in1, renderNext.in1),
    scrollWrapped.out.to(scrollOffset.data),
    renderDone.eq.to(scrollOffset.we, renderNext.sel),
    renderAddr.q.to(renderInc.in, renderDone.a, renderX.in, renderY.in, fb.addrA),
    sixtythree.out.to(renderDone.b),
    renderInc.out.to(renderNext.in0),
    renderNext.out.to(renderAddr.data),
    enable.out.to(renderAddr.we, fb.weA),
    renderY.out.to(yTimes24.a),
    twentyfour.out.to(yTimes24.b),
    renderX.out.to(scrollPlusX.b),
    scrollPlusX.sum.to(xOffset.in),
    yTimes24.product.to(bitmapAddr.a),
    xOffset.out.to(bitmapAddr.b),
    bitmapAddr.sum.to(bitmap.addr),
    bitmap.data_out.to(fb.dataA),
    display.addrB.to(fb.addrB),
    fb.outB.to(display.dataIn),
  ],
})
