// Auto-generated from DSL

const ProcessingElement = circuit('ProcessingElement', {
  in: { dataIn: bus(8), weightIn: bus(8), partialSumIn: bus(16), loadWeight: bit, resetAccum: bit },
  out: { dataOut: bus(8), result: bus(16) },
  nodes: { weightReg: Register, mult: Multiplier, adder: Adder, accum: Register, dataPipe: Register, accum_mux: Mux, one: Constant, zero: Constant, zero16: Constant },
  nodeArgs: { adder: { width: 16 }, one: { value: 1 }, zero: { value: 0 }, zero16: { value: 0 } },
  connect: ({ in: inp, out, weightReg, mult, adder, accum, dataPipe, accum_mux, one, zero, zero16 }) => [
    inp.weightIn.to(weightReg.data),
    inp.loadWeight.to(weightReg.we),
    inp.dataIn.to(mult.a, dataPipe.data),
    weightReg.q.to(mult.b),
    mult.product.to(adder.a),
    accum.q.to(adder.b, out.result),
    zero.out.to(adder.carry_in),
    inp.resetAccum.to(accum_mux.sel),
    adder.sum.to(accum_mux.in0),
    zero16.out.to(accum_mux.in1),
    accum_mux.out.to(accum.data),
    one.out.to(accum.we, dataPipe.we),
    dataPipe.q.to(out.dataOut),
  ],
})

const Systolic2x2_CounterBased = circuit('Systolic2x2_CounterBased', {
  in: { a00: bus(8), a01: bus(8), a10: bus(8), a11: bus(8), b00: bus(8), b01: bus(8), b10: bus(8), b11: bus(8), start: bit },
  out: { c00: bus(16), c01: bus(16), c10: bus(16), c11: bus(16), done: bit },
  nodes: { pe00: ProcessingElement, pe01: ProcessingElement, pe10: ProcessingElement, pe11: ProcessingElement, reg_a00: Register, reg_a01: Register, reg_a10: Register, reg_a11: Register, reg_b00: Register, reg_b01: Register, reg_b10: Register, reg_b11: Register, global_cycle: Register, global_inc: Incrementer, global_mux: Mux, k_phase: Register, k_inc: Incrementer, k_mux: Mux, running: DFlipFlop, start_or_running: Or, is_cycle_0: Comparator, is_cycle_1: Comparator, is_cycle_2: Comparator, is_cycle_3: Comparator, is_cycle_4: Comparator, is_cycle_5: Comparator, is_cycle_6: Comparator, is_cycle_7: Comparator, is_cycle_8: Comparator, is_cycle_9: Comparator, k_is_0: Comparator, k_is_1: Comparator, loadWeights_or: Or, done_latch: DFlipFlop, done_hold: Or, a_row0_mux: Mux, a_row1_mux: Mux, b_col0_mux: Mux, b_col1_mux: Mux, a_row0_inject: Or, a_row1_inject: Or, a_row0_gate: Mux, a_row1_gate: Mux, zero8: Constant, zero16: Constant, one: Constant, zero: Constant, const_0: Constant, const_1: Constant, const_2: Constant, const_3: Constant, const_4: Constant, const_5: Constant, const_6: Constant, const_7: Constant, const_8: Constant, const_9: Constant },
  nodeArgs: { zero8: { value: 0 }, zero16: { value: 0 }, one: { value: 1 }, zero: { value: 0 }, const_0: { value: 0 }, const_1: { value: 1 }, const_2: { value: 2 }, const_3: { value: 3 }, const_4: { value: 4 }, const_5: { value: 5 }, const_6: { value: 6 }, const_7: { value: 7 }, const_8: { value: 8 }, const_9: { value: 9 } },
  connect: ({ in: inp, out, pe00, pe01, pe10, pe11, reg_a00, reg_a01, reg_a10, reg_a11, reg_b00, reg_b01, reg_b10, reg_b11, global_cycle, global_inc, global_mux, k_phase, k_inc, k_mux, running, start_or_running, is_cycle_0, is_cycle_1, is_cycle_2, is_cycle_3, is_cycle_4, is_cycle_5, is_cycle_6, is_cycle_7, is_cycle_8, is_cycle_9, k_is_0, k_is_1, loadWeights_or, done_latch, done_hold, a_row0_mux, a_row1_mux, b_col0_mux, b_col1_mux, a_row0_inject, a_row1_inject, a_row0_gate, a_row1_gate, zero8, zero16, one, zero, const_0, const_1, const_2, const_3, const_4, const_5, const_6, const_7, const_8, const_9 }) => [
    inp.a00.to(reg_a00.data),
    inp.a01.to(reg_a01.data),
    inp.a10.to(reg_a10.data),
    inp.a11.to(reg_a11.data),
    inp.b00.to(reg_b00.data),
    inp.b01.to(reg_b01.data),
    inp.b10.to(reg_b10.data),
    inp.b11.to(reg_b11.data),
    inp.start.to(reg_a00.we, reg_a01.we, reg_a10.we, reg_a11.we, reg_b00.we, reg_b01.we, reg_b10.we, reg_b11.we, start_or_running.a, global_mux.sel),
    running.q.to(start_or_running.b),
    start_or_running.out.to(running.d, global_cycle.we, k_phase.we),
    global_cycle.q.to(global_inc.in, is_cycle_0.a, is_cycle_1.a, is_cycle_2.a, is_cycle_3.a, is_cycle_4.a, is_cycle_5.a, is_cycle_6.a, is_cycle_7.a, is_cycle_8.a, is_cycle_9.a),
    global_inc.out.to(global_mux.in0),
    zero.out.to(global_mux.in1, k_is_0.b),
    global_mux.out.to(global_cycle.data),
    k_phase.q.to(k_inc.in, k_mux.in0, k_is_0.a, k_is_1.a),
    is_cycle_4.eq.to(k_mux.sel),
    k_inc.out.to(k_mux.in1),
    k_mux.out.to(k_phase.data),
    one.out.to(k_is_1.b),
    const_0.out.to(is_cycle_0.b),
    const_1.out.to(is_cycle_1.b),
    const_2.out.to(is_cycle_2.b),
    const_3.out.to(is_cycle_3.b),
    const_4.out.to(is_cycle_4.b),
    const_5.out.to(is_cycle_5.b),
    const_6.out.to(is_cycle_6.b),
    const_7.out.to(is_cycle_7.b),
    const_8.out.to(is_cycle_8.b),
    const_9.out.to(is_cycle_9.b),
    is_cycle_1.eq.to(loadWeights_or.a),
    is_cycle_5.eq.to(loadWeights_or.b),
    is_cycle_2.eq.to(a_row0_inject.a),
    is_cycle_6.eq.to(a_row0_inject.b),
    is_cycle_3.eq.to(a_row1_inject.a),
    is_cycle_7.eq.to(a_row1_inject.b),
    k_is_1.eq.to(a_row0_mux.sel, a_row1_mux.sel, b_col0_mux.sel, b_col1_mux.sel),
    reg_a00.q.to(a_row0_mux.in0),
    reg_a01.q.to(a_row0_mux.in1),
    reg_a10.q.to(a_row1_mux.in0),
    reg_a11.q.to(a_row1_mux.in1),
    a_row0_inject.out.to(a_row0_gate.sel),
    zero8.out.to(a_row0_gate.in0, a_row1_gate.in0),
    a_row0_mux.out.to(a_row0_gate.in1),
    a_row1_inject.out.to(a_row1_gate.sel),
    a_row1_mux.out.to(a_row1_gate.in1),
    reg_b00.q.to(b_col0_mux.in0),
    reg_b10.q.to(b_col0_mux.in1),
    reg_b01.q.to(b_col1_mux.in0),
    reg_b11.q.to(b_col1_mux.in1),
    b_col0_mux.out.to(pe00.weightIn, pe10.weightIn),
    b_col1_mux.out.to(pe01.weightIn, pe11.weightIn),
    loadWeights_or.out.to(pe00.loadWeight, pe01.loadWeight, pe10.loadWeight, pe11.loadWeight),
    is_cycle_0.eq.to(pe00.resetAccum, pe01.resetAccum, pe10.resetAccum, pe11.resetAccum),
    a_row0_gate.out.to(pe00.dataIn),
    pe00.dataOut.to(pe01.dataIn),
    a_row1_gate.out.to(pe10.dataIn),
    pe10.dataOut.to(pe11.dataIn),
    zero16.out.to(pe00.partialSumIn, pe01.partialSumIn, pe10.partialSumIn, pe11.partialSumIn),
    is_cycle_9.eq.to(done_hold.a),
    done_latch.q.to(done_hold.b, out.done),
    done_hold.out.to(done_latch.d),
    pe00.result.to(out.c00),
    pe01.result.to(out.c01),
    pe10.result.to(out.c10),
    pe11.result.to(out.c11),
  ],
})

const TestCounterBased = circuit('TestCounterBased', {
  nodes: { sys: Systolic2x2_CounterBased, a00: Input, a01: Input, a10: Input, a11: Input, b00: Input, b01: Input, b10: Input, b11: Input, start: Switch, display_c00: HexDisplay, display_c01: HexDisplay, display_c10: HexDisplay, display_c11: HexDisplay, done_led: Led },
  nodeArgs: { a00: { value: 1 }, a01: { value: 2 }, a10: { value: 3 }, a11: { value: 4 }, b00: { value: 5 }, b01: { value: 6 }, b10: { value: 7 }, b11: { value: 8 } },
  connect: ({ in: inp, out, sys, a00, a01, a10, a11, b00, b01, b10, b11, start, display_c00, display_c01, display_c10, display_c11, done_led }) => [
    a00.out.to(sys.a00),
    a01.out.to(sys.a01),
    a10.out.to(sys.a10),
    a11.out.to(sys.a11),
    b00.out.to(sys.b00),
    b01.out.to(sys.b01),
    b10.out.to(sys.b10),
    b11.out.to(sys.b11),
    start.out.to(sys.start),
    sys.c00.to(display_c00.in),
    sys.c01.to(display_c01.in),
    sys.c10.to(display_c10.in),
    sys.c11.to(display_c11.in),
    sys.done.to(done_led.in),
  ],
})
