// Auto-generated from DSL

const ProcessingElement = circuit('ProcessingElement', {
  in: { dataIn: bus(8), weightIn: bus(8), partialSumIn: bus(16), loadWeight: bit, resetAccum: bit },
  out: { dataOut: bus(8), result: bus(16) },
  nodes: { weightReg: Register, mult: Multiplier, adder: Adder, accum: Register, dataPipe: Register, accum_mux: Mux, one: Constant, zero: Constant, zero16: Constant },
  nodeArgs: { adder: { width: 16 }, one: { value: 1 }, zero: { value: 0 }, zero16: { value: 0 } },
  connect: ({ in: inp, out, weightReg, mult, adder, accum, dataPipe, accum_mux, one, zero, zero16 }) => [
    inp.weightIn.to(weightReg.data),
    inp.loadWeight.to(weightReg.we),
    inp.dataIn.to(mult.a, dataPipe.data),
    weightReg.q.to(mult.b),
    mult.product.to(adder.a),
    accum.q.to(adder.b, out.result),
    zero.out.to(adder.carry_in),
    inp.resetAccum.to(accum_mux.sel),
    adder.sum.to(accum_mux.in0),
    zero16.out.to(accum_mux.in1),
    accum_mux.out.to(accum.data),
    one.out.to(accum.we, dataPipe.we),
    dataPipe.q.to(out.dataOut),
  ],
})

const Systolic3x3_CounterBased = circuit('Systolic3x3_CounterBased', {
  in: { a00: bus(8), a01: bus(8), a02: bus(8), a10: bus(8), a11: bus(8), a12: bus(8), a20: bus(8), a21: bus(8), a22: bus(8), b00: bus(8), b01: bus(8), b02: bus(8), b10: bus(8), b11: bus(8), b12: bus(8), b20: bus(8), b21: bus(8), b22: bus(8), start: bit },
  out: { c00: bus(16), c01: bus(16), c02: bus(16), c10: bus(16), c11: bus(16), c12: bus(16), c20: bus(16), c21: bus(16), c22: bus(16), done: bit },
  nodes: { pe00: ProcessingElement, pe01: ProcessingElement, pe02: ProcessingElement, pe10: ProcessingElement, pe11: ProcessingElement, pe12: ProcessingElement, pe20: ProcessingElement, pe21: ProcessingElement, pe22: ProcessingElement, reg_a00: Register, reg_a01: Register, reg_a02: Register, reg_a10: Register, reg_a11: Register, reg_a12: Register, reg_a20: Register, reg_a21: Register, reg_a22: Register, reg_b00: Register, reg_b01: Register, reg_b02: Register, reg_b10: Register, reg_b11: Register, reg_b12: Register, reg_b20: Register, reg_b21: Register, reg_b22: Register, global_cycle: Register, global_inc: Incrementer, global_mux: Mux, k_phase: Register, k_inc: Incrementer, k_mux_01: Mux, k_mux_reset: Mux, running: DFlipFlop, start_or_running: Or, is_cycle_0: Comparator, is_cycle_1: Comparator, is_cycle_2: Comparator, is_cycle_3: Comparator, is_cycle_4: Comparator, is_cycle_5: Comparator, is_cycle_6: Comparator, is_cycle_7: Comparator, is_cycle_8: Comparator, is_cycle_9: Comparator, is_cycle_10: Comparator, is_cycle_11: Comparator, is_cycle_12: Comparator, is_cycle_13: Comparator, is_cycle_14: Comparator, is_cycle_15: Comparator, is_cycle_16: Comparator, k_is_0: Comparator, k_is_1: Comparator, k_is_2: Comparator, loadWeights_or1: Or, loadWeights_or2: Or, done_latch: DFlipFlop, done_hold: Or, a_row0_mux_01: Mux, a_row0_mux_final: Mux, a_row0_inject_01: Or, a_row0_inject_final: Or, a_row0_gate: Mux, a_row1_mux_01: Mux, a_row1_mux_final: Mux, a_row1_inject_01: Or, a_row1_inject_final: Or, a_row1_gate: Mux, a_row2_mux_01: Mux, a_row2_mux_final: Mux, a_row2_inject_01: Or, a_row2_inject_final: Or, a_row2_gate: Mux, b_col0_mux_01: Mux, b_col0_mux_final: Mux, b_col1_mux_01: Mux, b_col1_mux_final: Mux, b_col2_mux_01: Mux, b_col2_mux_final: Mux, k_inc_trigger: Or, zero8: Constant, zero16: Constant, one: Constant, zero: Constant, const_0: Constant, const_1: Constant, const_2: Constant, const_3: Constant, const_4: Constant, const_5: Constant, const_6: Constant, const_7: Constant, const_8: Constant, const_9: Constant, const_10: Constant, const_11: Constant, const_12: Constant, const_13: Constant, const_14: Constant, const_15: Constant, const_16: Constant },
  nodeArgs: { zero8: { value: 0 }, zero16: { value: 0 }, one: { value: 1 }, zero: { value: 0 }, const_0: { value: 0 }, const_1: { value: 1 }, const_2: { value: 2 }, const_3: { value: 3 }, const_4: { value: 4 }, const_5: { value: 5 }, const_6: { value: 6 }, const_7: { value: 7 }, const_8: { value: 8 }, const_9: { value: 9 }, const_10: { value: 10 }, const_11: { value: 11 }, const_12: { value: 12 }, const_13: { value: 13 }, const_14: { value: 14 }, const_15: { value: 15 }, const_16: { value: 16 } },
  connect: ({ in: inp, out, pe00, pe01, pe02, pe10, pe11, pe12, pe20, pe21, pe22, reg_a00, reg_a01, reg_a02, reg_a10, reg_a11, reg_a12, reg_a20, reg_a21, reg_a22, reg_b00, reg_b01, reg_b02, reg_b10, reg_b11, reg_b12, reg_b20, reg_b21, reg_b22, global_cycle, global_inc, global_mux, k_phase, k_inc, k_mux_01, k_mux_reset, running, start_or_running, is_cycle_0, is_cycle_1, is_cycle_2, is_cycle_3, is_cycle_4, is_cycle_5, is_cycle_6, is_cycle_7, is_cycle_8, is_cycle_9, is_cycle_10, is_cycle_11, is_cycle_12, is_cycle_13, is_cycle_14, is_cycle_15, is_cycle_16, k_is_0, k_is_1, k_is_2, loadWeights_or1, loadWeights_or2, done_latch, done_hold, a_row0_mux_01, a_row0_mux_final, a_row0_inject_01, a_row0_inject_final, a_row0_gate, a_row1_mux_01, a_row1_mux_final, a_row1_inject_01, a_row1_inject_final, a_row1_gate, a_row2_mux_01, a_row2_mux_final, a_row2_inject_01, a_row2_inject_final, a_row2_gate, b_col0_mux_01, b_col0_mux_final, b_col1_mux_01, b_col1_mux_final, b_col2_mux_01, b_col2_mux_final, k_inc_trigger, zero8, zero16, one, zero, const_0, const_1, const_2, const_3, const_4, const_5, const_6, const_7, const_8, const_9, const_10, const_11, const_12, const_13, const_14, const_15, const_16 }) => [
    inp.a00.to(reg_a00.data),
    inp.a01.to(reg_a01.data),
    inp.a02.to(reg_a02.data),
    inp.a10.to(reg_a10.data),
    inp.a11.to(reg_a11.data),
    inp.a12.to(reg_a12.data),
    inp.a20.to(reg_a20.data),
    inp.a21.to(reg_a21.data),
    inp.a22.to(reg_a22.data),
    inp.b00.to(reg_b00.data),
    inp.b01.to(reg_b01.data),
    inp.b02.to(reg_b02.data),
    inp.b10.to(reg_b10.data),
    inp.b11.to(reg_b11.data),
    inp.b12.to(reg_b12.data),
    inp.b20.to(reg_b20.data),
    inp.b21.to(reg_b21.data),
    inp.b22.to(reg_b22.data),
    inp.start.to(reg_a00.we, reg_a01.we, reg_a02.we, reg_a10.we, reg_a11.we, reg_a12.we, reg_a20.we, reg_a21.we, reg_a22.we, reg_b00.we, reg_b01.we, reg_b02.we, reg_b10.we, reg_b11.we, reg_b12.we, reg_b20.we, reg_b21.we, reg_b22.we, start_or_running.a, global_mux.sel, k_mux_reset.sel),
    running.q.to(start_or_running.b),
    start_or_running.out.to(running.d, global_cycle.we, k_phase.we),
    global_cycle.q.to(global_inc.in, is_cycle_0.a, is_cycle_1.a, is_cycle_2.a, is_cycle_3.a, is_cycle_4.a, is_cycle_5.a, is_cycle_6.a, is_cycle_7.a, is_cycle_8.a, is_cycle_9.a, is_cycle_10.a, is_cycle_11.a, is_cycle_12.a, is_cycle_13.a, is_cycle_14.a, is_cycle_15.a, is_cycle_16.a),
    global_inc.out.to(global_mux.in0),
    zero.out.to(global_mux.in1, k_mux_reset.in1),
    global_mux.out.to(global_cycle.data),
    k_phase.q.to(k_inc.in, k_mux_01.in0, k_is_0.a, k_is_1.a, k_is_2.a),
    is_cycle_5.eq.to(k_inc_trigger.a),
    is_cycle_10.eq.to(k_inc_trigger.b),
    k_inc_trigger.out.to(k_mux_01.sel),
    k_inc.out.to(k_mux_01.in1),
    k_mux_01.out.to(k_mux_reset.in0),
    k_mux_reset.out.to(k_phase.data),
    const_0.out.to(k_is_0.b, is_cycle_0.b),
    const_1.out.to(k_is_1.b, is_cycle_1.b),
    const_2.out.to(k_is_2.b, is_cycle_2.b),
    const_3.out.to(is_cycle_3.b),
    const_4.out.to(is_cycle_4.b),
    const_5.out.to(is_cycle_5.b),
    const_6.out.to(is_cycle_6.b),
    const_7.out.to(is_cycle_7.b),
    const_8.out.to(is_cycle_8.b),
    const_9.out.to(is_cycle_9.b),
    const_10.out.to(is_cycle_10.b),
    const_11.out.to(is_cycle_11.b),
    const_12.out.to(is_cycle_12.b),
    const_13.out.to(is_cycle_13.b),
    const_14.out.to(is_cycle_14.b),
    const_15.out.to(is_cycle_15.b),
    const_16.out.to(is_cycle_16.b),
    is_cycle_1.eq.to(loadWeights_or1.a),
    is_cycle_6.eq.to(loadWeights_or1.b),
    loadWeights_or1.out.to(loadWeights_or2.a),
    is_cycle_11.eq.to(loadWeights_or2.b),
    is_cycle_2.eq.to(a_row0_inject_01.a),
    is_cycle_7.eq.to(a_row0_inject_01.b),
    a_row0_inject_01.out.to(a_row0_inject_final.a),
    is_cycle_12.eq.to(a_row0_inject_final.b),
    is_cycle_3.eq.to(a_row1_inject_01.a),
    is_cycle_8.eq.to(a_row1_inject_01.b),
    a_row1_inject_01.out.to(a_row1_inject_final.a),
    is_cycle_13.eq.to(a_row1_inject_final.b),
    is_cycle_4.eq.to(a_row2_inject_01.a),
    is_cycle_9.eq.to(a_row2_inject_01.b),
    a_row2_inject_01.out.to(a_row2_inject_final.a),
    is_cycle_14.eq.to(a_row2_inject_final.b),
    k_is_1.eq.to(a_row0_mux_01.sel, a_row1_mux_01.sel, a_row2_mux_01.sel, b_col0_mux_01.sel, b_col1_mux_01.sel, b_col2_mux_01.sel),
    reg_a00.q.to(a_row0_mux_01.in0),
    reg_a01.q.to(a_row0_mux_01.in1),
    k_is_2.eq.to(a_row0_mux_final.sel, a_row1_mux_final.sel, a_row2_mux_final.sel, b_col0_mux_final.sel, b_col1_mux_final.sel, b_col2_mux_final.sel),
    a_row0_mux_01.out.to(a_row0_mux_final.in0),
    reg_a02.q.to(a_row0_mux_final.in1),
    a_row0_inject_final.out.to(a_row0_gate.sel),
    zero8.out.to(a_row0_gate.in0, a_row1_gate.in0, a_row2_gate.in0),
    a_row0_mux_final.out.to(a_row0_gate.in1),
    reg_a10.q.to(a_row1_mux_01.in0),
    reg_a11.q.to(a_row1_mux_01.in1),
    a_row1_mux_01.out.to(a_row1_mux_final.in0),
    reg_a12.q.to(a_row1_mux_final.in1),
    a_row1_inject_final.out.to(a_row1_gate.sel),
    a_row1_mux_final.out.to(a_row1_gate.in1),
    reg_a20.q.to(a_row2_mux_01.in0),
    reg_a21.q.to(a_row2_mux_01.in1),
    a_row2_mux_01.out.to(a_row2_mux_final.in0),
    reg_a22.q.to(a_row2_mux_final.in1),
    a_row2_inject_final.out.to(a_row2_gate.sel),
    a_row2_mux_final.out.to(a_row2_gate.in1),
    reg_b00.q.to(b_col0_mux_01.in0),
    reg_b10.q.to(b_col0_mux_01.in1),
    b_col0_mux_01.out.to(b_col0_mux_final.in0),
    reg_b20.q.to(b_col0_mux_final.in1),
    reg_b01.q.to(b_col1_mux_01.in0),
    reg_b11.q.to(b_col1_mux_01.in1),
    b_col1_mux_01.out.to(b_col1_mux_final.in0),
    reg_b21.q.to(b_col1_mux_final.in1),
    reg_b02.q.to(b_col2_mux_01.in0),
    reg_b12.q.to(b_col2_mux_01.in1),
    b_col2_mux_01.out.to(b_col2_mux_final.in0),
    reg_b22.q.to(b_col2_mux_final.in1),
    b_col0_mux_final.out.to(pe00.weightIn, pe10.weightIn, pe20.weightIn),
    b_col1_mux_final.out.to(pe01.weightIn, pe11.weightIn, pe21.weightIn),
    b_col2_mux_final.out.to(pe02.weightIn, pe12.weightIn, pe22.weightIn),
    loadWeights_or2.out.to(pe00.loadWeight, pe01.loadWeight, pe02.loadWeight, pe10.loadWeight, pe11.loadWeight, pe12.loadWeight, pe20.loadWeight, pe21.loadWeight, pe22.loadWeight),
    is_cycle_0.eq.to(pe00.resetAccum, pe01.resetAccum, pe02.resetAccum, pe10.resetAccum, pe11.resetAccum, pe12.resetAccum, pe20.resetAccum, pe21.resetAccum, pe22.resetAccum),
    a_row0_gate.out.to(pe00.dataIn),
    pe00.dataOut.to(pe01.dataIn),
    pe01.dataOut.to(pe02.dataIn),
    a_row1_gate.out.to(pe10.dataIn),
    pe10.dataOut.to(pe11.dataIn),
    pe11.dataOut.to(pe12.dataIn),
    a_row2_gate.out.to(pe20.dataIn),
    pe20.dataOut.to(pe21.dataIn),
    pe21.dataOut.to(pe22.dataIn),
    zero16.out.to(pe00.partialSumIn, pe01.partialSumIn, pe02.partialSumIn, pe10.partialSumIn, pe11.partialSumIn, pe12.partialSumIn, pe20.partialSumIn, pe21.partialSumIn, pe22.partialSumIn),
    is_cycle_16.eq.to(done_hold.a),
    done_latch.q.to(done_hold.b, out.done),
    done_hold.out.to(done_latch.d),
    pe00.result.to(out.c00),
    pe01.result.to(out.c01),
    pe02.result.to(out.c02),
    pe10.result.to(out.c10),
    pe11.result.to(out.c11),
    pe12.result.to(out.c12),
    pe20.result.to(out.c20),
    pe21.result.to(out.c21),
    pe22.result.to(out.c22),
  ],
})

const TestSystolic3x3 = circuit('TestSystolic3x3', {
  nodes: { sys: Systolic3x3_CounterBased, a00: Input, a01: Input, a02: Input, a10: Input, a11: Input, a12: Input, a20: Input, a21: Input, a22: Input, b00: Input, b01: Input, b02: Input, b10: Input, b11: Input, b12: Input, b20: Input, b21: Input, b22: Input, start: Switch, display_c00: HexDisplay, display_c01: HexDisplay, display_c02: HexDisplay, display_c10: HexDisplay, display_c11: HexDisplay, display_c12: HexDisplay, display_c20: HexDisplay, display_c21: HexDisplay, display_c22: HexDisplay, done_led: Led },
  nodeArgs: { a00: { value: 1 }, a01: { value: 2 }, a02: { value: 3 }, a10: { value: 4 }, a11: { value: 5 }, a12: { value: 6 }, a20: { value: 7 }, a21: { value: 8 }, a22: { value: 9 }, b00: { value: 9 }, b01: { value: 8 }, b02: { value: 7 }, b10: { value: 6 }, b11: { value: 5 }, b12: { value: 4 }, b20: { value: 3 }, b21: { value: 2 }, b22: { value: 1 } },
  connect: ({ in: inp, out, sys, a00, a01, a02, a10, a11, a12, a20, a21, a22, b00, b01, b02, b10, b11, b12, b20, b21, b22, start, display_c00, display_c01, display_c02, display_c10, display_c11, display_c12, display_c20, display_c21, display_c22, done_led }) => [
    a00.out.to(sys.a00),
    a01.out.to(sys.a01),
    a02.out.to(sys.a02),
    a10.out.to(sys.a10),
    a11.out.to(sys.a11),
    a12.out.to(sys.a12),
    a20.out.to(sys.a20),
    a21.out.to(sys.a21),
    a22.out.to(sys.a22),
    b00.out.to(sys.b00),
    b01.out.to(sys.b01),
    b02.out.to(sys.b02),
    b10.out.to(sys.b10),
    b11.out.to(sys.b11),
    b12.out.to(sys.b12),
    b20.out.to(sys.b20),
    b21.out.to(sys.b21),
    b22.out.to(sys.b22),
    start.out.to(sys.start),
    sys.c00.to(display_c00.in),
    sys.c01.to(display_c01.in),
    sys.c02.to(display_c02.in),
    sys.c10.to(display_c10.in),
    sys.c11.to(display_c11.in),
    sys.c12.to(display_c12.in),
    sys.c20.to(display_c20.in),
    sys.c21.to(display_c21.in),
    sys.c22.to(display_c22.in),
    sys.done.to(done_led.in),
  ],
})
