/**
 * Circuit definitions for the "Pong in Hardware" blog post.
 *
 * Each circuit builds toward the final Pong game, from ball position
 * and bounce detection to paddle movement, phased rendering, and
 * the complete PongSimple circuit.
 */

import { circuit } from "@simten/core/circuit";
import type { BlogCircuit } from '../types';
import {
  Input, HexDisplay, Constant, Switch, Led,
  Register, Adder, Comparator, Or, And, Not, Mux,
  LeftShifter, BitSlice,
  DualPortRAM, Screen,
} from "@simten/core/std";

// ── Module-level circuit definitions ──

const BallPosition = circuit('BallPosition', {
  nodes: { ballX: Register, ballY: Register, dx: Input, dy: Input, nextX: Adder, nextY: Adder, wrapX: BitSlice, wrapY: BitSlice, enable: Switch, displayX: HexDisplay, displayY: HexDisplay },
  nodeArgs: { ballX: { initial: 8 }, ballY: { initial: 8 }, dx: { value: 1 }, dy: { value: 1 }, wrapX: { low: 0, high: 3 }, wrapY: { low: 0, high: 3 } },
  connect: ({ nodes: { ballX, ballY, dx, dy, nextX, nextY, wrapX, wrapY, enable, displayX, displayY } }) => [
    ballX.q.to(nextX.a, displayX.in),
    dx.out.to(nextX.b),
    ballY.q.to(nextY.a, displayY.in),
    dy.out.to(nextY.b),
    nextX.sum.to(wrapX.in),
    nextY.sum.to(wrapY.in),
    wrapX.out.to(ballX.data),
    wrapY.out.to(ballY.data),
    enable.out.to(ballX.we, ballY.we),
  ],
});

const BounceDetection = circuit('BounceDetection', {
  nodes: { ballY: Input, zero: Constant, fifteen: Constant, atTop: Comparator, atBottom: Comparator, shouldBounce: Or, bounceLed: Led, one: Constant, minus1: Constant, newDY: Mux, display: HexDisplay },
  nodeArgs: { ballY: { value: 15 }, zero: { value: 0 }, fifteen: { value: 15 }, one: { value: 1 }, minus1: { value: 255 }, newDY: { width: 8 } },
  connect: ({ nodes: { ballY, zero, fifteen, atTop, atBottom, shouldBounce, bounceLed, one, minus1, newDY, display } }) => [
    ballY.out.to(atTop.a, atBottom.a),
    zero.out.to(atTop.b),
    fifteen.out.to(atBottom.b),
    atTop.eq.to(shouldBounce.a),
    atBottom.eq.to(shouldBounce.b, newDY.sel),
    shouldBounce.out.to(bounceLed.in),
    one.out.to(newDY.in0),
    minus1.out.to(newDY.in1),
    newDY.out.to(display.in),
  ],
});

const PaddleMovement = circuit('PaddleMovement', {
  nodes: { keyboard: Input, zero: Constant, one: Constant, minus1: Constant, keyW: Constant, keyS: Constant, isW: Comparator, isS: Comparator, upDelta: Mux, delta: Mux, paddleY: Register, newY: Adder, wrapY: BitSlice, enable: Switch, display: HexDisplay, deltaDisplay: HexDisplay },
  nodeArgs: { keyboard: { value: 17 }, zero: { value: 0 }, one: { value: 1 }, minus1: { value: 255 }, keyW: { value: 17 }, keyS: { value: 31 }, upDelta: { width: 8 }, delta: { width: 8 }, paddleY: { initial: 6 }, wrapY: { low: 0, high: 3 } },
  connect: ({ nodes: { keyboard, zero, one, minus1, keyW, keyS, isW, isS, upDelta, delta, paddleY, newY, wrapY, enable, display, deltaDisplay } }) => [
    keyboard.out.to(isW.a, isS.a),
    keyW.out.to(isW.b),
    keyS.out.to(isS.b),
    zero.out.to(upDelta.in0),
    minus1.out.to(upDelta.in1),
    isW.eq.to(upDelta.sel),
    upDelta.out.to(delta.in0),
    one.out.to(delta.in1),
    isS.eq.to(delta.sel),
    paddleY.q.to(newY.a, display.in),
    delta.out.to(newY.b, deltaDisplay.in),
    newY.sum.to(wrapY.in),
    wrapY.out.to(paddleY.data),
    enable.out.to(paddleY.we),
  ],
});

const PhaseCounter14 = circuit('PhaseCounter14', {
  nodes: { phase: Register, one: Constant, zero: Constant, fourteen: Constant, phaseInc: Adder, atFourteen: Comparator, nextPhase: Mux, enable: Switch, display: HexDisplay, drawThreshold: Constant, isDrawPhase: Comparator, drawLed: Led },
  nodeArgs: { phase: { initial: 0 }, one: { value: 1 }, zero: { value: 0 }, fourteen: { value: 14 }, nextPhase: { width: 8 }, drawThreshold: { value: 6 } },
  connect: ({ nodes: { phase, one, zero, fourteen, phaseInc, atFourteen, nextPhase, enable, display, drawThreshold, isDrawPhase, drawLed } }) => [
    phase.q.to(phaseInc.a, display.in, isDrawPhase.a),
    one.out.to(phaseInc.b),
    phaseInc.sum.to(atFourteen.a, nextPhase.in0),
    fourteen.out.to(atFourteen.b),
    zero.out.to(nextPhase.in1),
    atFourteen.eq.to(nextPhase.sel),
    nextPhase.out.to(phase.data),
    enable.out.to(phase.we),
    drawThreshold.out.to(isDrawPhase.b),
    isDrawPhase.gt.to(drawLed.in),
  ],
});

const PixelAddress = circuit('PixelAddress', {
  nodes: { x: Input, y: Input, four: Input, y16: LeftShifter, addr: Adder, result: HexDisplay },
  nodeArgs: { x: { value: 4 }, y: { value: 4 }, four: { value: 4 } },
  connect: ({ nodes: { x, y, four, y16, addr, result } }) => [
    y.out.to(y16.value),
    four.out.to(y16.shift),
    y16.result.to(addr.a),
    x.out.to(addr.b),
    addr.sum.to(result.in),
  ],
});

export const PONG_CIRCUITS: Record<string, BlogCircuit> = {
  ballPosition: {
    name: "Ball Position",
    description:
      "Two registers store the ball's X and Y coordinates. An adder moves the ball by adding a velocity delta each tick.",
    layout: {
      dx: { x: 0, y: 50 },
      dy: { x: 0, y: 200 },
      enable: { x: 0, y: 370 },
      nextX: { x: 200, y: 50 },
      nextY: { x: 200, y: 200 },
      wrapX: { x: 370, y: 50 },
      wrapY: { x: 370, y: 200 },
      ballX: { x: 540, y: 50 },
      ballY: { x: 540, y: 200 },
      displayX: { x: 710, y: 50 },
      displayY: { x: 710, y: 200 },
    },
    circuit: BallPosition,
  },

  bounceDetection: {
    name: "Bounce Detection",
    description:
      "Comparators check if the ball is at a screen edge (0 or 15), signaling when it needs to reverse direction.",
    layout: {
      ballY: { x: 0, y: 120 },
      zero: { x: 0, y: 0 },
      fifteen: { x: 0, y: 240 },
      atTop: { x: 200, y: 30 },
      atBottom: { x: 200, y: 200 },
      shouldBounce: { x: 380, y: 120 },
      bounceLed: { x: 560, y: 120 },
      one: { x: 200, y: 350 },
      minus1: { x: 200, y: 450 },
      newDY: { x: 380, y: 400 },
      display: { x: 560, y: 400 },
    },
    circuit: BounceDetection,
  },

  paddleMovement: {
    name: "Paddle Movement",
    description:
      "Keyboard scan codes are compared to detect W/S key presses. A mux tree converts the result into a delta that moves the paddle register.",
    layout: {
      keyboard: { x: 0, y: 100 },
      keyW: { x: 0, y: 200 },
      keyS: { x: 0, y: 300 },
      zero: { x: 0, y: 400 },
      minus1: { x: 0, y: 0 },
      one: { x: 0, y: 500 },
      isW: { x: 200, y: 100 },
      isS: { x: 200, y: 300 },
      upDelta: { x: 370, y: 100 },
      delta: { x: 370, y: 300 },
      paddleY: { x: 540, y: 200 },
      newY: { x: 540, y: 370 },
      wrapY: { x: 540, y: 500 },
      enable: { x: 370, y: 500 },
      display: { x: 720, y: 150 },
      deltaDisplay: { x: 720, y: 330 },
    },
    circuit: PaddleMovement,
  },

  phaseCounter: {
    name: "14-Phase Rendering Pipeline",
    description:
      "A counter cycles 0-13, orchestrating: clear old ball, clear old left paddle, clear old right paddle, draw new ball, draw new left paddle, draw new right paddle.",
    layout: {
      enable: { x: 0, y: 100 },
      one: { x: 0, y: 250 },
      zero: { x: 200, y: 350 },
      fourteen: { x: 200, y: 250 },
      phase: { x: 200, y: 100 },
      phaseInc: { x: 370, y: 100 },
      atFourteen: { x: 370, y: 250 },
      nextPhase: { x: 530, y: 180 },
      display: { x: 700, y: 100 },
      drawThreshold: { x: 370, y: 400 },
      isDrawPhase: { x: 530, y: 400 },
      drawLed: { x: 700, y: 400 },
    },
    circuit: PhaseCounter14,
  },

  pixelAddress: {
    name: "Pixel Address Calculation",
    description:
      "Converts (X, Y) coordinates to a linear framebuffer address using (Y << 4) + X. In real hardware a left shift by 4 is just wiring — each bit of Y connects to a position 4 places higher — so the only real gate is the final adder.",
    layout: {
      x: { x: 0, y: 120 },
      y: { x: 0, y: 0 },
      four: { x: 0, y: 240 },
      y16: { x: 220, y: 60 },
      addr: { x: 420, y: 90 },
      result: { x: 600, y: 90 },
    },
    circuit: PixelAddress,
  },
};

/**
 * Full PongSimple — a complete Pong game on a 16x16 screen.
 * Two paddles (W/S and Up/Down), a bouncing ball, 14-phase rendering pipeline.
 */
export const PongSimple = circuit('PongSimple', {
  nodes: { ram: DualPortRAM, screen: Screen, keyboard0: Input, keyboard1: Input, ballX: Register, ballY: Register, ballDX: Register, ballDY: Register, leftPaddleY: Register, rightPaddleY: Register, oldBallX: Register, oldBallY: Register, oldLeftPaddleY: Register, oldRightPaddleY: Register, phaseCounter: Register, phaseIncrement: Adder, one: Input, phaseMod: Comparator, fourteen: Input, nextPhase: Mux, zero: Input, phaseEnable: Switch, p0c: Input, p1c: Input, p2c: Input, p3c: Input, p4c: Input, p5c: Input, p6c: Input, p7c: Input, p8c: Input, p9c: Input, p10c: Input, p11c: Input, p12c: Input, p13c: Input, isP0: Comparator, isP1: Comparator, isP2: Comparator, isP3: Comparator, isP4: Comparator, isP5: Comparator, isP6: Comparator, isP7: Comparator, isP8: Comparator, isP9: Comparator, isP10: Comparator, isP11: Comparator, isP12: Comparator, isP13: Comparator, fifteen: Input, thirteen: Input, six: Input, two: Input, four: Input, minus1: Input, halfRange: Input, keyW: Input, keyS: Input, keyUp: Input, keyDown: Input, isW_kb0: Comparator, isS_kb0: Comparator, isUp_kb0: Comparator, isDown_kb0: Comparator, isW_kb1: Comparator, isS_kb1: Comparator, isUp_kb1: Comparator, isDown_kb1: Comparator, isW: Or, isS: Or, isUp: Or, isDown: Or, leftUpDelta: Mux, leftDelta: Mux, newLeftPaddleY: Adder, rightUpDelta: Mux, rightDelta: Mux, newRightPaddleY: Adder, atTopWall: Comparator, atBottomWall: Comparator, headingUp: Comparator, headingDown: Comparator, topBounce: And, bottomBounce: And, yBounce: Or, dyIs1: Comparator, negDY: Mux, newDY: Mux, nearLeftWall: Comparator, headingLeft: Comparator, leftPaddleTop: Comparator, leftPaddleBottom: Adder, leftPaddleBot: Comparator, leftAboveOrEq: Not, leftBelowOrEq: Or, leftPaddleMatch: And, leftWallAndHeading: And, leftBounce: And, nearRightWall: Comparator, wallBounceRight: Input, headingRight: Comparator, rightPaddleTop: Comparator, rightPaddleBottom: Adder, rightPaddleBot: Comparator, rightAboveOrEq: Not, rightBelowOrEq: Or, rightPaddleMatch: And, rightWallAndHeading: And, rightBounce: And, xBounce: Or, dxIs1: Comparator, negDX: Mux, newDX: Mux, newBallX: Adder, newBallY: Adder, updateEnable: Switch, shouldUpdate: And, ballSpeedCounter: Register, ballSpeedInc: Adder, ballSpeedOne: Input, ballSpeedLimit: Comparator, ballSpeedMax: Input, ballSpeedNext: Mux, ballSpeedZero: Input, isBallTick: Comparator, shouldUpdateBall: And, wrappedBallX: BitSlice, wrappedBallY: BitSlice, leftYOver: Comparator, leftYNeg: Comparator, leftYClamped1: Mux, leftYClamped: Mux, rightYOver: Comparator, rightYNeg: Comparator, rightYClamped1: Mux, rightYClamped: Mux, isOff1a: Or, isOff1b: Or, isOffset1: Or, isOff2a: Or, isOff2b: Or, isOffset2: Or, paddleOffset: Mux, paddleOffset2: Mux, isClearLeft: Or, isClearLeft2: Or, isClearRight: Or, isClearRight2: Or, isDrawLeft: Or, isDrawLeft2: Or, isDrawRight: Or, isDrawRight2: Or, basePaddleY0: Mux, basePaddleY1: Mux, basePaddleY: Mux, paddlePixelY: Adder, isPaddlePhase1: Or, isPaddlePhase2: Or, isPaddlePhase: Or, selectBallY: Mux, selectY: Mux, isLeftPaddle: Or, isRightPaddle: Or, selectBallX: Mux, selectX0: Mux, selectX: Mux, yTimes16: LeftShifter, ramAddr: Adder, isClearPhase: Comparator, ramData: Mux, writeEnable: Switch },
  nodeArgs: { screen: { width: 16, height: 16 }, ballX: { initial: 8 }, ballY: { initial: 8 }, ballDX: { initial: 1 }, ballDY: { initial: 1 }, leftPaddleY: { initial: 6 }, rightPaddleY: { initial: 6 }, oldBallX: { initial: 8 }, oldBallY: { initial: 8 }, oldLeftPaddleY: { initial: 6 }, oldRightPaddleY: { initial: 6 }, one: { value: 1 }, fourteen: { value: 14 }, nextPhase: { width: 8 }, zero: { value: 0 }, p0c: { value: 0 }, p1c: { value: 1 }, p2c: { value: 2 }, p3c: { value: 3 }, p4c: { value: 4 }, p5c: { value: 5 }, p6c: { value: 6 }, p7c: { value: 7 }, p8c: { value: 8 }, p9c: { value: 9 }, p10c: { value: 10 }, p11c: { value: 11 }, p12c: { value: 12 }, p13c: { value: 13 }, fifteen: { value: 15 }, thirteen: { value: 13 }, six: { value: 6 }, two: { value: 2 }, four: { value: 4 }, minus1: { value: 255 }, halfRange: { value: 128 }, keyW: { value: 17 }, keyS: { value: 31 }, keyUp: { value: 72 }, keyDown: { value: 80 }, leftUpDelta: { width: 8 }, leftDelta: { width: 8 }, rightUpDelta: { width: 8 }, rightDelta: { width: 8 }, negDY: { width: 8 }, newDY: { width: 8 }, wallBounceRight: { value: 14 }, negDX: { width: 8 }, newDX: { width: 8 }, ballSpeedCounter: { width: 2 }, ballSpeedInc: { width: 2 }, ballSpeedOne: { value: 1, width: 2 }, ballSpeedLimit: { width: 2 }, ballSpeedMax: { value: 2, width: 2 }, ballSpeedNext: { width: 2 }, ballSpeedZero: { value: 0, width: 2 }, isBallTick: { width: 2 }, wrappedBallX: { low: 0, high: 3 }, wrappedBallY: { low: 0, high: 3 }, leftYClamped1: { width: 8 }, leftYClamped: { width: 8 }, rightYClamped1: { width: 8 }, rightYClamped: { width: 8 }, paddleOffset: { width: 8 }, paddleOffset2: { width: 8 }, basePaddleY0: { width: 8 }, basePaddleY1: { width: 8 }, basePaddleY: { width: 8 }, selectBallY: { width: 8 }, selectY: { width: 8 }, selectBallX: { width: 8 }, selectX0: { width: 8 }, selectX: { width: 8 }, ramData: { width: 8 } },
  connect: ({ nodes: { ram, screen, keyboard0, keyboard1, ballX, ballY, ballDX, ballDY, leftPaddleY, rightPaddleY, oldBallX, oldBallY, oldLeftPaddleY, oldRightPaddleY, phaseCounter, phaseIncrement, one, phaseMod, fourteen, nextPhase, zero, phaseEnable, p0c, p1c, p2c, p3c, p4c, p5c, p6c, p7c, p8c, p9c, p10c, p11c, p12c, p13c, isP0, isP1, isP2, isP3, isP4, isP5, isP6, isP7, isP8, isP9, isP10, isP11, isP12, isP13, fifteen, thirteen, two, four, minus1, halfRange, keyW, keyS, keyUp, keyDown, isW_kb0, isS_kb0, isUp_kb0, isDown_kb0, isW_kb1, isS_kb1, isUp_kb1, isDown_kb1, isW, isS, isUp, isDown, leftUpDelta, leftDelta, newLeftPaddleY, rightUpDelta, rightDelta, newRightPaddleY, atTopWall, atBottomWall, headingUp, headingDown, topBounce, bottomBounce, yBounce, dyIs1, negDY, newDY, nearLeftWall, headingLeft, leftPaddleTop, leftPaddleBottom, leftPaddleBot, leftAboveOrEq, leftBelowOrEq, leftPaddleMatch, leftWallAndHeading, leftBounce, nearRightWall, wallBounceRight, headingRight, rightPaddleTop, rightPaddleBottom, rightPaddleBot, rightAboveOrEq, rightBelowOrEq, rightPaddleMatch, rightWallAndHeading, rightBounce, xBounce, dxIs1, negDX, newDX, newBallX, newBallY, updateEnable, shouldUpdate, ballSpeedCounter, ballSpeedInc, ballSpeedOne, ballSpeedLimit, ballSpeedMax, ballSpeedNext, ballSpeedZero, isBallTick, shouldUpdateBall, wrappedBallX, wrappedBallY, leftYOver, leftYNeg, leftYClamped1, leftYClamped, rightYOver, rightYNeg, rightYClamped1, rightYClamped, isOff1a, isOff1b, isOffset1, isOff2a, isOff2b, isOffset2, paddleOffset, paddleOffset2, isClearLeft, isClearLeft2, isClearRight, isClearRight2, isDrawLeft, isDrawLeft2, isDrawRight, isDrawRight2, basePaddleY0, basePaddleY1, basePaddleY, paddlePixelY, isPaddlePhase1, isPaddlePhase2, isPaddlePhase, selectBallY, selectY, isLeftPaddle, isRightPaddle, selectBallX, selectX0, selectX, yTimes16, ramAddr, isClearPhase, ramData, writeEnable } }) => [
    screen.addrB.to(ram.addrB),
    ram.outB.to(screen.dataIn),
    phaseCounter.q.to(phaseIncrement.a, isP0.a, isP1.a, isP2.a, isP3.a, isP4.a, isP5.a, isP6.a, isP7.a, isP8.a, isP9.a, isP10.a, isP11.a, isP12.a, isP13.a, isClearPhase.a),
    one.out.to(phaseIncrement.b, leftDelta.in1, rightDelta.in1, headingDown.b, dyIs1.b, negDY.in0, nearLeftWall.b, headingRight.b, dxIs1.b, negDX.in0, paddleOffset.in1, ramData.in0),
    phaseIncrement.sum.to(phaseMod.a, nextPhase.in0),
    fourteen.out.to(phaseMod.b),
    zero.out.to(nextPhase.in1, leftUpDelta.in0, rightUpDelta.in0, atTopWall.b, leftYClamped.in1, rightYClamped.in1, paddleOffset.in0, selectX0.in1, ramData.in1),
    phaseMod.eq.to(nextPhase.sel),
    nextPhase.out.to(phaseCounter.data),
    phaseEnable.out.to(phaseCounter.we),
    p0c.out.to(isP0.b),
    p1c.out.to(isP1.b),
    p2c.out.to(isP2.b),
    p3c.out.to(isP3.b),
    p4c.out.to(isP4.b),
    p5c.out.to(isP5.b),
    p6c.out.to(isP6.b),
    p7c.out.to(isP7.b, isClearPhase.b),
    p8c.out.to(isP8.b),
    p9c.out.to(isP9.b),
    p10c.out.to(isP10.b),
    p11c.out.to(isP11.b),
    p12c.out.to(isP12.b),
    p13c.out.to(isP13.b),
    keyboard0.out.to(isW_kb0.a, isS_kb0.a, isUp_kb0.a, isDown_kb0.a),
    keyW.out.to(isW_kb0.b, isW_kb1.b),
    keyS.out.to(isS_kb0.b, isS_kb1.b),
    keyUp.out.to(isUp_kb0.b, isUp_kb1.b),
    keyDown.out.to(isDown_kb0.b, isDown_kb1.b),
    keyboard1.out.to(isW_kb1.a, isS_kb1.a, isUp_kb1.a, isDown_kb1.a),
    isW_kb0.eq.to(isW.a),
    isW_kb1.eq.to(isW.b),
    isS_kb0.eq.to(isS.a),
    isS_kb1.eq.to(isS.b),
    isUp_kb0.eq.to(isUp.a),
    isUp_kb1.eq.to(isUp.b),
    isDown_kb0.eq.to(isDown.a),
    isDown_kb1.eq.to(isDown.b),
    minus1.out.to(leftUpDelta.in1, rightUpDelta.in1, headingUp.b, negDY.in1, headingLeft.b, negDX.in1),
    isW.out.to(leftUpDelta.sel),
    leftUpDelta.out.to(leftDelta.in0),
    isS.out.to(leftDelta.sel),
    leftPaddleY.q.to(newLeftPaddleY.a, leftPaddleTop.b, leftPaddleBottom.a, oldLeftPaddleY.data, basePaddleY1.in1),
    leftDelta.out.to(newLeftPaddleY.b),
    isUp.out.to(rightUpDelta.sel),
    rightUpDelta.out.to(rightDelta.in0),
    isDown.out.to(rightDelta.sel),
    rightPaddleY.q.to(newRightPaddleY.a, rightPaddleTop.b, rightPaddleBottom.a, oldRightPaddleY.data, basePaddleY.in1),
    rightDelta.out.to(newRightPaddleY.b),
    ballY.q.to(atTopWall.a, atBottomWall.a, leftPaddleTop.a, leftPaddleBot.a, rightPaddleTop.a, rightPaddleBot.a, newBallY.a, oldBallY.data, selectBallY.in0),
    fifteen.out.to(atBottomWall.b, selectX.in1),
    ballDY.q.to(headingUp.a, headingDown.a, dyIs1.a, newDY.in0),
    atTopWall.eq.to(topBounce.a),
    headingUp.eq.to(topBounce.b),
    atBottomWall.eq.to(bottomBounce.a),
    headingDown.eq.to(bottomBounce.b),
    topBounce.out.to(yBounce.a),
    bottomBounce.out.to(yBounce.b),
    dyIs1.eq.to(negDY.sel),
    negDY.out.to(newDY.in1),
    yBounce.out.to(newDY.sel),
    ballX.q.to(nearLeftWall.a, nearRightWall.a, newBallX.a, oldBallX.data, selectBallX.in0),
    ballDX.q.to(headingLeft.a, headingRight.a, dxIs1.a, newDX.in0),
    two.out.to(leftPaddleBottom.b, rightPaddleBottom.b, paddleOffset2.in1),
    leftPaddleBottom.sum.to(leftPaddleBot.b),
    leftPaddleTop.lt.to(leftAboveOrEq.in),
    leftPaddleBot.eq.to(leftBelowOrEq.a),
    leftPaddleBot.lt.to(leftBelowOrEq.b),
    leftAboveOrEq.out.to(leftPaddleMatch.a),
    leftBelowOrEq.out.to(leftPaddleMatch.b),
    nearLeftWall.eq.to(leftWallAndHeading.a),
    headingLeft.eq.to(leftWallAndHeading.b),
    leftWallAndHeading.out.to(leftBounce.a),
    leftPaddleMatch.out.to(leftBounce.b),
    wallBounceRight.out.to(nearRightWall.b),
    rightPaddleBottom.sum.to(rightPaddleBot.b),
    rightPaddleTop.lt.to(rightAboveOrEq.in),
    rightPaddleBot.eq.to(rightBelowOrEq.a),
    rightPaddleBot.lt.to(rightBelowOrEq.b),
    rightAboveOrEq.out.to(rightPaddleMatch.a),
    rightBelowOrEq.out.to(rightPaddleMatch.b),
    nearRightWall.eq.to(rightWallAndHeading.a),
    headingRight.eq.to(rightWallAndHeading.b),
    rightWallAndHeading.out.to(rightBounce.a),
    rightPaddleMatch.out.to(rightBounce.b),
    leftBounce.out.to(xBounce.a),
    rightBounce.out.to(xBounce.b),
    dxIs1.eq.to(negDX.sel),
    negDX.out.to(newDX.in1),
    xBounce.out.to(newDX.sel),
    newDX.out.to(newBallX.b, ballDX.data),
    newDY.out.to(newBallY.b, ballDY.data),
    updateEnable.out.to(shouldUpdate.a),
    isP13.eq.to(shouldUpdate.b, isOff2b.b, isDrawRight2.b),
    ballSpeedCounter.q.to(ballSpeedInc.a, ballSpeedLimit.a, isBallTick.a),
    ballSpeedOne.out.to(ballSpeedInc.b),
    ballSpeedMax.out.to(ballSpeedLimit.b),
    ballSpeedInc.sum.to(ballSpeedNext.in0),
    ballSpeedZero.out.to(ballSpeedNext.in1, isBallTick.b),
    ballSpeedLimit.eq.to(ballSpeedNext.sel),
    ballSpeedNext.out.to(ballSpeedCounter.data),
    shouldUpdate.out.to(ballSpeedCounter.we, shouldUpdateBall.a, oldLeftPaddleY.we, oldRightPaddleY.we, leftPaddleY.we, rightPaddleY.we),
    isBallTick.eq.to(shouldUpdateBall.b),
    shouldUpdateBall.out.to(oldBallX.we, oldBallY.we, ballX.we, ballY.we, ballDX.we, ballDY.we),
    newBallX.sum.to(wrappedBallX.in),
    wrappedBallX.out.to(ballX.data),
    newBallY.sum.to(wrappedBallY.in),
    wrappedBallY.out.to(ballY.data),
    newLeftPaddleY.sum.to(leftYOver.a, leftYNeg.a, leftYClamped1.in0),
    thirteen.out.to(leftYOver.b, leftYClamped1.in1, rightYOver.b, rightYClamped1.in1),
    halfRange.out.to(leftYNeg.b, rightYNeg.b),
    leftYOver.gt.to(leftYClamped1.sel),
    leftYClamped1.out.to(leftYClamped.in0),
    leftYNeg.gt.to(leftYClamped.sel),
    leftYClamped.out.to(leftPaddleY.data),
    newRightPaddleY.sum.to(rightYOver.a, rightYNeg.a, rightYClamped1.in0),
    rightYOver.gt.to(rightYClamped1.sel),
    rightYClamped1.out.to(rightYClamped.in0),
    rightYNeg.gt.to(rightYClamped.sel),
    rightYClamped.out.to(rightPaddleY.data),
    isP2.eq.to(isOff1a.a, isClearLeft.b),
    isP5.eq.to(isOff1a.b, isClearRight.b),
    isP9.eq.to(isOff1b.a, isDrawLeft.b),
    isP12.eq.to(isOff1b.b, isDrawRight.b),
    isOff1a.out.to(isOffset1.a),
    isOff1b.out.to(isOffset1.b),
    isP3.eq.to(isOff2a.a, isClearLeft2.b),
    isP6.eq.to(isOff2a.b, isClearRight2.b),
    isP10.eq.to(isOff2b.a, isDrawLeft2.b),
    isOff2a.out.to(isOffset2.a),
    isOff2b.out.to(isOffset2.b),
    isOffset1.out.to(paddleOffset.sel),
    paddleOffset.out.to(paddleOffset2.in0),
    isOffset2.out.to(paddleOffset2.sel),
    isP1.eq.to(isClearLeft.a),
    isClearLeft.out.to(isClearLeft2.a),
    isP4.eq.to(isClearRight.a),
    isClearRight.out.to(isClearRight2.a),
    isP8.eq.to(isDrawLeft.a),
    isDrawLeft.out.to(isDrawLeft2.a),
    isP11.eq.to(isDrawRight.a),
    isDrawRight.out.to(isDrawRight2.a),
    oldLeftPaddleY.q.to(basePaddleY0.in0),
    oldRightPaddleY.q.to(basePaddleY0.in1),
    isClearRight2.out.to(basePaddleY0.sel, isPaddlePhase1.b, isRightPaddle.a),
    basePaddleY0.out.to(basePaddleY1.in0),
    isDrawLeft2.out.to(basePaddleY1.sel, isPaddlePhase2.a, isLeftPaddle.b),
    basePaddleY1.out.to(basePaddleY.in0),
    isDrawRight2.out.to(basePaddleY.sel, isPaddlePhase2.b, isRightPaddle.b),
    basePaddleY.out.to(paddlePixelY.a),
    paddleOffset2.out.to(paddlePixelY.b),
    isClearLeft2.out.to(isPaddlePhase1.a, isLeftPaddle.a),
    isPaddlePhase1.out.to(isPaddlePhase.a),
    isPaddlePhase2.out.to(isPaddlePhase.b),
    oldBallY.q.to(selectBallY.in1),
    isP0.eq.to(selectBallY.sel, selectBallX.sel),
    selectBallY.out.to(selectY.in0),
    paddlePixelY.sum.to(selectY.in1),
    isPaddlePhase.out.to(selectY.sel),
    oldBallX.q.to(selectBallX.in1),
    selectBallX.out.to(selectX0.in0),
    isLeftPaddle.out.to(selectX0.sel),
    selectX0.out.to(selectX.in0),
    isRightPaddle.out.to(selectX.sel),
    selectY.out.to(yTimes16.value),
    four.out.to(yTimes16.shift),
    yTimes16.result.to(ramAddr.a),
    selectX.out.to(ramAddr.b),
    ramAddr.sum.to(ram.addrA),
    isClearPhase.lt.to(ramData.sel),
    ramData.out.to(ram.dataA),
    writeEnable.out.to(ram.weA),
  ],
});
