/**
 * Building a reduced ambient-globals shim.
 *
 * `SIMTEN_CORE_GLOBALS` declares every stdlib component at once, which is right
 * for the open editor at `/circuit` and wrong for a teaching context that hands
 * components out gradually. `buildGlobalsFor(['Nand', 'Switch', 'Led'])` returns
 * the same shim carrying only those, JSDoc intact — so an unavailable component
 * does not autocomplete and does not typecheck, rather than being offered and
 * then rejected later by a grader.
 *
 * It filters the blob in place rather than having the generator emit a second
 * artifact. A second generated file crossing from `@simten/core` into this
 * package is exactly the coupling that already caused one silent-staleness bug:
 * rebuilding core alone left Monaco reporting errors on valid code, with
 * nothing to indicate the types were old. One generated input, filtered here,
 * has no such failure mode.
 *
 * The format it parses is generated by `packages/core/scripts/
 * build-editor-globals.mjs` and is stable by construction — every component is
 * an optionally-JSDoc'd `const <Name>: typeof core.<Name>;` at one level of
 * indentation. `__tests__/globals-subset.test.ts` asserts every component in
 * the blob still parses, so a change to that generator fails loudly here
 * instead of silently dropping components from the editor.
 */

import { SIMTEN_CORE_GLOBALS } from './generated/core-types.gen';

/**
 * Names always present regardless of level: the `circuit()` API itself. Without
 * these nothing compiles at all, so they are never a reward to be earned.
 */
const ALWAYS = ['circuit', 'component', 'bit', 'bus', 'reg', 'mem'];

interface ParsedGlobals {
  /** Everything up to and including `declare global {`, plus the fixed API. */
  preamble: string;
  /** Declaration (with any JSDoc) keyed by the name it declares. */
  parts: Map<string, string>;
}

/**
 * One component: an optional JSDoc block, then the declaration. `[^\S\n]` is
 * "horizontal whitespace" — indentation without swallowing blank lines, which
 * keeps a preceding comment attached to the right declaration.
 */
const PART = /(\/\*\*[\s\S]*?\*\/\n)?[^\S\n]*const ([A-Za-z_$][\w$]*)\s*:[^\n]*\n/g;

let cached: ParsedGlobals | null = null;

function parse(): ParsedGlobals {
  if (cached) return cached;

  const source = SIMTEN_CORE_GLOBALS;
  const open = source.indexOf('declare global {');
  const preamble = open === -1 ? '' : source.slice(0, open + 'declare global {'.length);

  const parts = new Map<string, string>();
  for (const match of source.matchAll(PART)) {
    const [whole, , name] = match;
    if (name) parts.set(name, whole.trimEnd());
  }

  cached = { preamble, parts };
  return cached;
}

/** Every component name the shim knows about. Exported for the drift test. */
export function knownGlobalNames(): string[] {
  return [...parse().parts.keys()];
}

/**
 * An ambient-globals shim declaring only `names` (plus the always-present
 * `circuit()` API). Unknown names are skipped rather than throwing — a level
 * naming a component that no longer exists should lose that component, not
 * take the editor down with it.
 */
export function buildGlobalsFor(names: readonly string[]): string {
  const { preamble, parts } = parse();

  const wanted = [...new Set([...ALWAYS, ...names])];
  const lines = wanted.map((name) => parts.get(name)).filter((decl): decl is string => !!decl);

  return `${preamble}\n${lines.join('\n')}\n}\n\nexport {};\n`;
}
