/**
 * Challenge MCP tools
 *
 * Exposes challenge metadata, stage info, and progress checking.
 * Designed for Socratic tutoring — never reveals exact solution connections.
 * Hints are generated by the LLM from stage context + progress feedback.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import {
  ALL_CHALLENGES,
  getChallengeStage,
  getChallengeStages,
  checkProgress,
  getNextMissingConnection,
} from '@turing-incomplete/challenges';
import { getPreviewServer, getOrCreateServer } from '../lib/preview-singleton.js';
import { TI_URL } from '../lib/config.js';

function getNextStageId(challengeId: string, currentStageId: string): string | null {
  const stages = getChallengeStages(challengeId);
  if (!stages) return null;
  const idx = stages.findIndex(s => s.id === currentStageId);
  if (idx < 0 || idx >= stages.length - 1) return null;
  return stages[idx + 1].id;
}

export function registerChallengeTools(server: McpServer): void {
  // ── list_challenges ──────────────────────────────────────────────
  server.tool(
    'list_challenges',
    'List all available hardware challenges with title, description, difficulty, and stage count. Use this to help users discover what they can build.',
    {},
    async () => {
      const list = ALL_CHALLENGES.map(c => ({
        id: c.slug,
        title: c.title,
        description: c.description,
        difficulty: c.difficulty,
        stages: c.stages,
        tag: c.tag,
      }));

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(list, null, 2) }],
      };
    }
  );

  // ── get_challenge_stage ───────────────────────────────────────────
  server.tool(
    'get_challenge_stage',
    'Get details for a specific challenge stage: concept explanation, objective, scaffold DSL, and available nodes/ports. Does NOT return the solution — guide the user with hints instead of revealing answers.',
    {
      challengeId: z.string().describe('Challenge slug (e.g. "build-an-alu", "snake")'),
      stageId: z.string().describe('Stage ID (e.g. "and-gate", "half-adder", "framebuffer")'),
    },
    async ({ challengeId, stageId }) => {
      const stage = getChallengeStage(challengeId, stageId);
      if (!stage) {
        const stages = getChallengeStages(challengeId);
        if (!stages) {
          return {
            content: [{ type: 'text' as const, text: `Unknown challenge "${challengeId}". Use list_challenges to see available challenges.` }],
            isError: true,
          };
        }
        return {
          content: [{ type: 'text' as const, text: `Unknown stage "${stageId}" in challenge "${challengeId}". Available stages: ${stages.map(s => s.id).join(', ')}` }],
          isError: true,
        };
      }

      // Ensure preview server is running so the browser can POST challenge state
      try {
        const preview = await getOrCreateServer();
        // Navigate browser to the requested stage if already connected
        preview.navigateChallenge(challengeId, stageId);
      } catch {
        // Non-fatal — challenge info still works, just no auto-sync
      }

      const challengeUrl = `${TI_URL}/challenges/${challengeId}`;

      const result = {
        id: stage.id,
        title: stage.title,
        concept: stage.concept,
        objective: stage.objective,
        scaffold: stage.scaffold,
        hintCount: stage.hints.length,
        nextStageId: getNextStageId(challengeId, stageId),
        url: challengeUrl,
      };

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

  // ── check_challenge_progress ─────────────────────────────────────
  server.tool(
    'check_challenge_progress',
    'Check the user\'s progress on a challenge stage. If the browser challenge is open, reads the current state automatically — no parameters needed. Otherwise, pass challengeId, stageId, and userSource explicitly. Returns how many connections are correct, missing (grouped by node type), and extra. Never reveals exact solution connections.',
    {
      challengeId: z.string().optional().describe('Challenge slug (auto-detected from browser if omitted)'),
      stageId: z.string().optional().describe('Stage ID (auto-detected from browser if omitted)'),
      userSource: z.string().optional().describe('The user\'s current DSL source code (auto-read from browser if omitted)'),
    },
    async ({ challengeId, stageId, userSource }) => {
      // Auto-read from preview server if params are omitted
      if (!challengeId || !stageId || !userSource) {
        const preview = getPreviewServer();
        if (!preview) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge is open in the browser. Either open a challenge at /challenges/... or provide challengeId, stageId, and userSource manually.' }],
            isError: true,
          };
        }
        const state = preview.getChallengeState();
        if (!state) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge state received from the browser yet. Make sure a challenge is open at /challenges/... and try again.' }],
            isError: true,
          };
        }
        challengeId = challengeId ?? state.challengeId;
        stageId = stageId ?? state.stageId;
        userSource = userSource ?? state.userSource;
      }

      const stage = getChallengeStage(challengeId, stageId);
      if (!stage) {
        return {
          content: [{ type: 'text' as const, text: `Unknown challenge/stage: "${challengeId}/${stageId}"` }],
          isError: true,
        };
      }

      const result = checkProgress(userSource, stage.solution);

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

  // ── solve_next ──────────────────────────────────────────────────
  server.tool(
    'solve_next',
    'Add the next missing connection to the user\'s challenge circuit. Reads the current state from the browser automatically. Returns the connection that was added so you can explain it.',
    {
      challengeId: z.string().optional().describe('Challenge slug (auto-detected from browser if omitted)'),
      stageId: z.string().optional().describe('Stage ID (auto-detected from browser if omitted)'),
    },
    async ({ challengeId, stageId }) => {
      const preview = getPreviewServer();
      if (!preview) {
        return {
          content: [{ type: 'text' as const, text: 'No challenge is open in the browser. Open a challenge at /challenges/... first.' }],
          isError: true,
        };
      }

      const state = preview.getChallengeState();
      if (!state) {
        return {
          content: [{ type: 'text' as const, text: 'No challenge state received from the browser yet. Make sure a challenge is open and try again.' }],
          isError: true,
        };
      }

      challengeId = challengeId ?? state.challengeId;
      stageId = stageId ?? state.stageId;

      const stage = getChallengeStage(challengeId, stageId);
      if (!stage) {
        return {
          content: [{ type: 'text' as const, text: `Unknown challenge/stage: "${challengeId}/${stageId}"` }],
          isError: true,
        };
      }

      const connection = getNextMissingConnection(state.userSource, stage.solution);
      if (!connection) {
        const nextId = getNextStageId(challengeId, stageId);
        const msg = nextId
          ? `All connections complete! The circuit is fully wired. Next stage: "${nextId}"`
          : 'All connections complete! The circuit is fully wired. This is the final stage!';
        return {
          content: [{ type: 'text' as const, text: msg }],
        };
      }

      // Push the connection to the browser
      preview.addChallengeStep(challengeId, stageId, `connect ${connection}`);

      return {
        content: [{ type: 'text' as const, text: `Added connection: connect ${connection}` }],
      };
    }
  );

}
