/**
 * Challenge MCP tools
 *
 * Exposes challenge metadata, step info, and progress checking.
 * Designed for Socratic tutoring — never reveals exact solution connections.
 * Hints are generated by the LLM from step context + progress feedback.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import {
  ALL_CHALLENGES,
  getChallengeStep,
  getChallengeSteps,
  checkProgress,
} from '@turing-incomplete/challenges';
import { getPreviewServer, getOrCreateServer } from '../lib/preview-singleton.js';

export function registerChallengeTools(server: McpServer): void {
  // ── list_challenges ──────────────────────────────────────────────
  server.tool(
    'list_challenges',
    'List all available hardware challenges with title, description, difficulty, and step count. Use this to help users discover what they can build.',
    {},
    async () => {
      const list = ALL_CHALLENGES.map(c => ({
        id: c.slug,
        title: c.title,
        description: c.description,
        difficulty: c.difficulty,
        steps: c.steps,
        tag: c.tag,
      }));

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(list, null, 2) }],
      };
    }
  );

  // ── get_challenge_step ───────────────────────────────────────────
  server.tool(
    'get_challenge_step',
    'Get details for a specific challenge step: concept explanation, objective, scaffold DSL, and available nodes/ports. Does NOT return the solution — guide the user with hints instead of revealing answers.',
    {
      challengeId: z.string().describe('Challenge slug (e.g. "build-an-alu", "snake")'),
      stepId: z.string().describe('Step ID (e.g. "and-gate", "half-adder", "framebuffer")'),
    },
    async ({ challengeId, stepId }) => {
      const step = getChallengeStep(challengeId, stepId);
      if (!step) {
        const steps = getChallengeSteps(challengeId);
        if (!steps) {
          return {
            content: [{ type: 'text' as const, text: `Unknown challenge "${challengeId}". Use list_challenges to see available challenges.` }],
            isError: true,
          };
        }
        return {
          content: [{ type: 'text' as const, text: `Unknown step "${stepId}" in challenge "${challengeId}". Available steps: ${steps.map(s => s.id).join(', ')}` }],
          isError: true,
        };
      }

      // Ensure preview server is running so the browser can POST challenge state
      let previewPort: number | null = null;
      try {
        const preview = await getOrCreateServer();
        previewPort = preview.port;
        // Navigate browser to the requested step if already connected
        preview.navigateChallenge(stepId);
      } catch {
        // Non-fatal — challenge info still works, just no auto-sync
      }

      const tiUrl = process.env.TI_URL ?? 'http://localhost:3001';
      const challengeUrl = previewPort
        ? `${tiUrl}/challenges/${challengeId}?port=${previewPort}`
        : `${tiUrl}/challenges/${challengeId}`;

      const result = {
        id: step.id,
        title: step.title,
        concept: step.concept,
        objective: step.objective,
        scaffold: step.scaffold,
        hintCount: step.hints.length,
        url: challengeUrl,
      };

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

  // ── check_challenge_progress ─────────────────────────────────────
  server.tool(
    'check_challenge_progress',
    'Check the user\'s progress on a challenge step. If the browser challenge is open, reads the current state automatically — no parameters needed. Otherwise, pass challengeId, stepId, and userSource explicitly. Returns how many connections are correct, missing (grouped by node type), and extra. Never reveals exact solution connections.',
    {
      challengeId: z.string().optional().describe('Challenge slug (auto-detected from browser if omitted)'),
      stepId: z.string().optional().describe('Step ID (auto-detected from browser if omitted)'),
      userSource: z.string().optional().describe('The user\'s current DSL source code (auto-read from browser if omitted)'),
    },
    async ({ challengeId, stepId, userSource }) => {
      // Auto-read from preview server if params are omitted
      if (!challengeId || !stepId || !userSource) {
        const preview = getPreviewServer();
        if (!preview) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge is open in the browser. Either open a challenge at /challenges/... or provide challengeId, stepId, and userSource manually.' }],
            isError: true,
          };
        }
        const state = preview.getChallengeState();
        if (!state) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge state received from the browser yet. Make sure a challenge is open at /challenges/... and try again.' }],
            isError: true,
          };
        }
        challengeId = challengeId ?? state.challengeId;
        stepId = stepId ?? state.stepId;
        userSource = userSource ?? state.userSource;
      }

      const step = getChallengeStep(challengeId, stepId);
      if (!step) {
        return {
          content: [{ type: 'text' as const, text: `Unknown challenge/step: "${challengeId}/${stepId}"` }],
          isError: true,
        };
      }

      const result = checkProgress(userSource, step.solution);

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

}
