/**
 * Challenge MCP tools
 *
 * Exposes challenge metadata, level info, and progress checking.
 * Designed for Socratic tutoring — never reveals exact solution connections.
 * Hints are generated by the LLM from level context + progress feedback.
 */

import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import {
  ALL_CHALLENGES,
  getChallengeLevel,
  getChallengeLevels,
  checkProgress,
  getNextMissingConnection,
} from '@turing-incomplete/challenges';
import { getPreviewServer, getOrCreateServer } from '../lib/preview-singleton.js';
import { TI_URL } from '../lib/config.js';

function getNextLevelId(challengeId: string, currentLevelId: string): string | null {
  const levels = getChallengeLevels(challengeId);
  if (!levels) return null;
  const idx = levels.findIndex(l => l.id === currentLevelId);
  if (idx < 0 || idx >= levels.length - 1) return null;
  return levels[idx + 1].id;
}

export function registerChallengeTools(server: McpServer): void {
  // ── list_challenges ──────────────────────────────────────────────
  server.tool(
    'list_challenges',
    'List all available hardware challenges with title, description, difficulty, and level count. Use this to help users discover what they can build.',
    {},
    async () => {
      const list = ALL_CHALLENGES.map(c => ({
        id: c.slug,
        title: c.title,
        description: c.description,
        difficulty: c.difficulty,
        levels: c.levels,
        tag: c.tag,
      }));

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(list, null, 2) }],
      };
    }
  );

  // ── get_challenge_level ───────────────────────────────────────────
  server.tool(
    'get_challenge_level',
    'Get details for a specific challenge level: concept explanation, objective, scaffold DSL, and available nodes/ports. Does NOT return the solution — guide the user with hints instead of revealing answers.',
    {
      challengeId: z.string().describe('Challenge slug (e.g. "build-an-alu", "snake")'),
      levelId: z.string().describe('Level ID (e.g. "and-gate", "half-adder", "framebuffer")'),
    },
    async ({ challengeId, levelId }) => {
      const level = getChallengeLevel(challengeId, levelId);
      if (!level) {
        const levels = getChallengeLevels(challengeId);
        if (!levels) {
          return {
            content: [{ type: 'text' as const, text: `Unknown challenge "${challengeId}". Use list_challenges to see available challenges.` }],
            isError: true,
          };
        }
        return {
          content: [{ type: 'text' as const, text: `Unknown level "${levelId}" in challenge "${challengeId}". Available levels: ${levels.map(l => l.id).join(', ')}` }],
          isError: true,
        };
      }

      // Ensure studio server is running so the browser can report challenge state
      try {
        const preview = await getOrCreateServer();
        // Navigate browser to the requested level if already connected
        preview.navigateChallenge(challengeId, levelId);
      } catch {
        // Non-fatal — challenge info still works, just no auto-sync
      }

      const challengeUrl = `${TI_URL}/challenges/${challengeId}`;

      const result = {
        id: level.id,
        title: level.title,
        concept: level.concept,
        objective: level.objective,
        scaffold: level.scaffold,
        hintCount: level.hints.length,
        nextLevelId: getNextLevelId(challengeId, levelId),
        url: challengeUrl,
      };

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

  // ── check_challenge_progress ─────────────────────────────────────
  server.tool(
    'check_challenge_progress',
    'Check the user\'s progress on a challenge level. If the browser challenge is open, reads the current state automatically — no parameters needed. Otherwise, pass challengeId, levelId, and userSource explicitly. Returns how many connections are correct, missing (grouped by node type), and extra. Never reveals exact solution connections.',
    {
      challengeId: z.string().optional().describe('Challenge slug (auto-detected from browser if omitted)'),
      levelId: z.string().optional().describe('Level ID (auto-detected from browser if omitted)'),
      userSource: z.string().optional().describe('The user\'s current DSL source code (auto-read from browser if omitted)'),
    },
    async ({ challengeId, levelId, userSource }) => {
      // Auto-read from preview server if params are omitted
      if (!challengeId || !levelId || !userSource) {
        const preview = getPreviewServer();
        if (!preview) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge is open in the browser. Either open a challenge at /challenges/... or provide challengeId, levelId, and userSource manually.' }],
            isError: true,
          };
        }
        const state = await preview.getChallengeState();
        if (!state) {
          return {
            content: [{ type: 'text' as const, text: 'No challenge state received from the browser. The tab may be closed or unresponsive. Make sure a challenge is open at /challenges/... and try again.' }],
            isError: true,
          };
        }
        challengeId = challengeId ?? state.challengeId;
        levelId = levelId ?? state.levelId;
        userSource = userSource ?? state.userSource;
      }

      const level = getChallengeLevel(challengeId, levelId);
      if (!level) {
        return {
          content: [{ type: 'text' as const, text: `Unknown challenge/level: "${challengeId}/${levelId}"` }],
          isError: true,
        };
      }

      const result = checkProgress(userSource, level.solution);

      return {
        content: [{ type: 'text' as const, text: JSON.stringify(result, null, 2) }],
      };
    }
  );

  // ── solve_next ──────────────────────────────────────────────────
  server.tool(
    'solve_next',
    'Add the next missing connection to the user\'s challenge circuit. Reads the current state from the browser automatically. Returns the connection that was added so you can explain it.',
    {
      challengeId: z.string().optional().describe('Challenge slug (auto-detected from browser if omitted)'),
      levelId: z.string().optional().describe('Level ID (auto-detected from browser if omitted)'),
    },
    async ({ challengeId, levelId }) => {
      const preview = getPreviewServer();
      if (!preview) {
        return {
          content: [{ type: 'text' as const, text: 'No challenge is open in the browser. Open a challenge at /challenges/... first.' }],
          isError: true,
        };
      }

      const state = await preview.getChallengeState();
      if (!state) {
        return {
          content: [{ type: 'text' as const, text: 'No challenge state received from the browser. The tab may be closed or unresponsive. Make sure a challenge is open and try again.' }],
          isError: true,
        };
      }

      challengeId = challengeId ?? state.challengeId;
      levelId = levelId ?? state.levelId;

      const level = getChallengeLevel(challengeId, levelId);
      if (!level) {
        return {
          content: [{ type: 'text' as const, text: `Unknown challenge/level: "${challengeId}/${levelId}"` }],
          isError: true,
        };
      }

      const connection = getNextMissingConnection(state.userSource, level.solution);
      if (!connection) {
        const nextId = getNextLevelId(challengeId, levelId);
        const msg = nextId
          ? `All connections complete! The circuit is fully wired. Next level: "${nextId}"`
          : 'All connections complete! The circuit is fully wired. This is the final level!';
        return {
          content: [{ type: 'text' as const, text: msg }],
        };
      }

      // Push the connection to the browser
      preview.addChallengeStep(challengeId, levelId, `connect ${connection}`);

      return {
        content: [{ type: 'text' as const, text: `Added connection: connect ${connection}` }],
      };
    }
  );

}
